### ISSUE TITLE
Cannot build with frameworks: KSCrash/KSCrashAdvanced.h file not found

### ISSUE THREAD

**Issue by SSheldon** [bugsnag/bugsnag-cocoa#101]
I'm integrating Bugsnag 5.0.2 via CocoaPods with a Podfile set to `use_frameworks!` and get a compiler error when compiling Bugsnag:
```
Pods/Bugsnag/Source/Bugsnag.m:32:9: 'KSCrash/KSCrashAdvanced.h' file not found
```

The issue does not occur when building static libraries, i.e. with `use_frameworks!` removed from the Podfile.

It appears that `KSCrashAdvanced.h` is a private header in KSCrash 1.0.1. Starting with kstenerud/KSCrash@0114ae0, only certain headers are public in KSCrash. This was noticed and fixed in kstenerud/KSCrash#124 by adding a KSCrash/Reporting/Advanced subspec. However, a new version of KSCrash has not yet been published.

I believe to fix this:

1. A new 1.0.2 version of KSCrash will need to be published
2. Bugsnag will need to be updated to include a KSCrash/Reporting/Advanced dependency at version 1.0.2

**Comment by SSheldon** [comment]
Alternatively, since KSCrashAdvanced.h wasn't private in version 1.0.0 of KSCrash, this could potentially be resolved by downgrading the dependency to allow that version, but I'm not sure if anything was changed in 1.0.1 of KSCrash that Bugsnag depends on.

**Comment by SSheldon** [comment]
Okay, version 1.0.2 of KSCrash was tagged, but the changes to its spec in 1.0.2 now have caused it to not build with `use_frameworks!`. I'll look into that some more.

**Comment by SSheldon** [comment]
:tada: wooh with the kstenerud/KSCrash#127 PR I opened I'm finally able to build with frameworks!

Working podfile looks like:
``` ruby
platform :ios, '8.0'
use_frameworks!

target 'PodsTest' do
  pod 'Bugsnag', '5.0.2'
  pod 'KSCrash/RecordingAdvanced', :git => 'git@github.com:SSheldon/KSCrash.git', :branch => 'frameworks_advanced'
end
```

**Comment by kattrali** [comment]
Awesome work, @SSheldon. Thanks for looking into this. I'm taking a look at fixing #100 and shipping a patch release for this along with it. Hopefully now the subspecs are divided as needed.
