### ISSUE TITLE
Add error time to device payload

### ISSUE THREAD

**Issue by eanakashima** [bugsnag/bugsnag-cocoa#103]
The bugsnag-android notifier seems to include an [error time](https://github.com/bugsnag/bugsnag-android/blob/97eca13c7aa604a6578a231abb83cdfa5e14bf49/src/androidTest/java/com/bugsnag/android/DeviceStateTest.java#L20) in the Device state. Would it be possible to have the [cocoa notifier](https://github.com/bugsnag/bugsnag-cocoa/blob/8c99da70060f587d96612d58a6683f7e94d25516/Source/BugsnagCrashReport.m#L299-L316) report that time as well?

**Comment by kattrali** [comment]
I don't see why not, just need to know the format. We already have the information needed to add it to the payload.
