### ISSUE TITLE
Incorporate module-based and file-based filtering

### ISSUE THREAD

**Issue by sethfri** [bugsnag/bugsnag-cocoa#1087]
### Description

Large iOS apps typically have multiple engineering teams that work on them. These teams typically work on a subset of features, comprised of a subset of modules in the app.

In this world, it's rather overwhelming to look at the giant list of crashes in Bugsnag and try to determine which are the ones you need to care about. Meanwhile, Bugsnag offers powerful functionality with Bookmarks, that allow engineers to create custom dashboards for a subset of crashes.

**Describe the solution you'd like**

We are very attracted to [Sentry's ownership rules](https://docs.sentry.io/product/issues/issue-owners/#creating-rules) as a way of solving this problem. It allows engineers to filter based on file path or module. Meanwhile, Swift offers the `#fileID` macro and Obj-C offers the `__FILE__` macro. Both of these would allow Bugsnag to attract file and module information for segmenting in Bugsnag.

We would love Bugsnag to incorporate some form of module-based or file-based filtering so that our feature teams can get a better handle on the crashes and errors that are most relevant to them.

**Describe alternatives you've considered**
We have tried passing this in as metadata to Bugsnag. While this works for non-fatal errors since we know exactly when we're going to call `notifyError`, it does not work for crashes.

#927 was a previous form of this request, but we believe the approach in this new issue is much more straightforward.

**Comment by mattdyoung** [comment]
Thanks @sethfri!

I've added your thoughts above to our internal discussions on what we're planning for adding code ownership features.

**Comment by johnkiely1** [comment]
Hey @sethfri, just to let you know we have released our code ownership functionality. 

https://docs.bugsnag.com/product/automatic-error-assignment/ 

As part of this, we have added functionality to allow you to assign errors based on code locations as present in the error stacktrace, which I believe will give you the flexibility you were looking for.  Do let us know if you have any feedback.
