### ISSUE TITLE
KSCrash crashed on app atart

### ISSUE THREAD

**Issue by pogoist** [bugsnag/bugsnag-cocoa#111]
Hey guys,

since updating to 5.2.1 we register a lot of crashes on app start. It's hard to reproduce because for me issue occurs 5 of 100 app starts. I read some threads on kscrash github repo about this or similar problems e.g. https://github.com/kstenerud/KSCrash/issues/144 or https://github.com/kstenerud/KSCrash/issues/155

Thanks!

`EXC_BAD_ACCESS Attempted to dereference garbage pointer 0x18b. 
    /usr/lib/libobjc.A.dylib objc_msgSend
    Frameworks/KSCrash.framework/KSCrash handleDealloc_NSObject
    Frameworks/CoreFoundation.framework/CoreFoundation <redacted>
    /usr/lib/libobjc.A.dylib _ZN11objc_object17sidetable_releaseEb
    /usr/lib/libobjc.A.dylib _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv
    PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices <redacted>
    PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices <redacted>
    PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices <redacted>
    Frameworks/CoreFoundation.framework/CoreFoundation <redacted>
    Frameworks/CoreFoundation.framework/CoreFoundation <redacted>
    Frameworks/CoreFoundation.framework/CoreFoundation <redacted>
    Frameworks/CoreFoundation.framework/CoreFoundation CFRunLoopRunSpecific
    Frameworks/CoreFoundation.framework/CoreFoundation CFRunLoopRunInMode
    Frameworks/UIKit.framework/UIKit <redacted>
    Frameworks/UIKit.framework/UIKit UIApplicationMain`

**Comment by kattrali** [comment]
Thanks for the report, @pogoist. Can you provide your KSCrash version as well? I'm taking a look.

**Comment by pogoist** [comment]
Thank you @kattrali ! KSCrash version is 1.5.11. Bugsnag 5.2.0 dependency is installed via cocoa pods

**Comment by kattrali** [comment]
Thanks! After a bit of tests, I think this is kstenerud/KSCrash#160; I'm drafting a patch to move the minimum version we use.

**Comment by kattrali** [comment]
Closed via v5.3.0

**Comment by pogoist** [comment]
Great news, thank you very much!
