### ISSUE TITLE
Possible Documentation problem

### ISSUE THREAD

**Issue by cjcoimbra** [bugsnag/bugsnag-cocoa#114]
Hi, in the Objective-C (iOS) documentation there is this example:
`+ (void)notify:(NSException *_Nonnull)exception withBlock:(BugsnagNotifyBlock _Nullable)block;`

However there is no "withBlock" method the correct I believe is this one:
`+ (void)notify:(NSException *_Nonnull)exception block:(BugsnagNotifyBlock _Nullable)block;`

**Comment by kattrali** [comment]
Hi @cjcoimbra, thank you for the report. I've updated the docs accordingly, and the change should show up shortly.
