### ISSUE TITLE
BugsnagConfiguration#addBeforeNotifyHook: deprecated without a replacement

### ISSUE THREAD

**Issue by schluete** [bugsnag/bugsnag-cocoa#116]
We're treating all warnings as errors in our iOS app. After updating to the latest Bugsnag CocoaPod 5.4.2 the app stopped compiling due to a deprecation warning in [BugsnagConfiguration line 156](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/BugsnagConfiguration.h#L156). The suggested replacement `addBeforeNotifyBlock:` is nowhere to be found in master though.

**Comment by schluete** [comment]
Clarifying the issue a little bit: I realise that the method is actually called `addBeforeSendBlock:`, the report is about changing the deprecation warning.

**Comment by kattrali** [comment]
Thanks for the report, @schluete. I’ll fix the deprecation warning to reference `addBeforeSendBlock:`.
