### ISSUE TITLE
Enable the "Require Only App-Extension-Safe API" build setting

### ISSUE THREAD

**Issue by jeffhunter** [bugsnag/bugsnag-cocoa#117]
Please turn on the "Require Only App-Extension-Safe API" (APPLICATION_EXTENSION_API_ONLY) build setting for the Bugsnag framework. This is required to use Bugsnag in iOS app extensions.

I turned on the setting locally, and everything seemed to build fine.

**Comment by kattrali** [comment]
Thanks! Updated and released in v5.5.0

**Comment by jeffhunter** [comment]
Great, thanks!
