### ISSUE TITLE
Missing support for SSL Pinning

### ISSUE THREAD

**Issue by tomleavy** [bugsnag/bugsnag-cocoa#118]
We currently use Bugsnag with an on premise setup. It would be great if you guys could support SSL Pinning so that we can use our own custom certificates

**Comment by kattrali** [comment]
Thank you for the report, @tleavy86. This is a great idea.

**Comment by kattrali** [comment]
Fixed in 5.7.0 with the addition of the [`session`](https://docs.bugsnag.com/platforms/ios/configuration-options/#session) configuration option.
