### ISSUE TITLE
Support specifying grouping hash at the client notify[Error] call site

### ISSUE THREAD

**Issue by dcow** [bugsnag/bugsnag-cocoa#1191]
### Description
Allow specifying custom grouping when calling notify[Error].

**Describe the solution you'd like**
Right now, you can only modify the grouping hash using the `BugsnagOnSendErrorBlock`. However, in reality, the grouping hash may be error-specific. It would be awesome to see an optional parameter on the `BugsnagClient` notify methods or a blessed metadata key that you can use to convey the appropriate hash with per-error granularity.

**Describe alternatives you've considered**
I've considered globally introspecting all errors with a `BugsnagOnSendErrorBlock` and applying the hash, however it's a rather roundabout way to achieve the result and further by the time the callback runs you may no longer have the relevant context to generate an appropriate hash since the callback is global and notify calls happen locally.

**Additional context**
I am running some JS code in a webview (not react native) and need to report a fair amount of handled errors from the JS which, without a custom grouping hash, all essentially have the same stack frame. I don't want a custom grouping hash for *all* the errors in my app, just these ones in the relevant section of the app. The hash depends on some information local to the execution environment at the time the error is reported which is unavailable to a global handler.

**Comment by nickdowell** [comment]
Hi @dcow

You can also modify the grouping hash ([or any other data](https://docs.bugsnag.com/platforms/ios/reporting-handled-exceptions/#customizing-diagnostic-data)) by providing a block to the notify call, like so:

```Swift
Bugsnag.notifyError(error) {
    $0.groupingHash = "something"
    return true
}
```

```Objective-C
[Bugsnag notifyError:error block:^BOOL(BugsnagEvent *event) {
    event.groupingHash = @"something";
    return YES;
}];
```

Does that help solve your issue?

**Comment by dcow** [comment]
That will do! Thanks for the info. Now I'm wondering how I missed that 😕 I skimmed the implementation a few times looking for something... must be the hour.
