### ISSUE TITLE
Allow configuring of exclusion of urlParams for Network Request Breadcrumbs

### ISSUE THREAD

**Issue by mdcarter1** [bugsnag/bugsnag-cocoa#1223]
### Description
Network Request Breadcrumbs are a great feature.  Presently the breadcrumbs sent to Bugsnag via the notifier include the urlParams.  In some apps this may not be desirable as those params may hold sensitive data that we would not want shared.

**Describe the solution you'd like**
Please provide a configuration option to not send the urlParams with the network request breadcrumb.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nickdowell** [comment]
Hi @mdcarter1 glad to hear you say Network Request Breadcrumbs are a great feature 😁 

If you have some specific urlParams that are sensitive they can be filtered out by specifying them in [configuration.redactedKeys](https://docs.bugsnag.com/platforms/ios/configuration-options/#redactedkeys).

For example, given a network request to `https://example.com?item=123&authKey=abcdef` and the following configuration:

```swift
configuration.redactedKeys = ["authKey"]
```

Bugsnag would omit the `authKeys` parameter from `urlParams`.

Note: `redactedKeys` defaults to `["password"]`.

Or to remove all `urlParams` you can use an `OnBreadcrumb` callback:

```swift
configuration.addOnBreadcrumb {
    if $0.type == .request {
        $0.metadata.removeValue(forKey: "urlParams")
    }
    return true
}
```

Hope that helps!

**Comment by xander-jones** [comment]
👋  hey @mdcarter1, hope the example above has given you the info to achieve the result you're after. Drop us a message if you need any further assistance.
