### ISSUE TITLE
We need to track crashes in the background. How do we do so?

### ISSUE THREAD

**Issue by ronbarr** [bugsnag/bugsnag-cocoa#1225]
### Describe the bug
We will be unable to update to a recent supported version of Bugsnag until we are also able to monitor background hangs, crashes and watchdog violations. How do we enable this?

We are currently using an old version of Bugsnag for compatibility. We do a lot of work with background launches and background tasks, and watchdog violations are an important metric for us.

We need to be able to track background hangs. We could stay on the old version but we are already having to modify the code to handle newer versions of Xcode and Swift.

### Environment
* Bugsnag version: 6.14.3
* iOS/tvOS/macOS version(s): Any
* Simulator or physical device: Any
* Xcode version: Xcode 12.4
* Swift version (if applicable): 5.3

**Comment by johnkiely1** [comment]
Hey @ronbarr

It's currently not possible to enable background app hang detection. Although initially available, background app hang detection was found to be unreliable and so it was removed. The rationale was discussed in the PR for this change [here](https://github.com/bugsnag/bugsnag-cocoa/pull/1075). 

It would be good to understand your use case a little more. In what scenarios are you interested in the background behaviour of the application?

Which version of Bugsnag are you currently using? Particularly where you said you are unable to upgrade, do you mean past v6.9.4 where we disabled the background app hang reporting? Or something else?

**Comment by mattdyoung** [comment]
Closing as we haven't had a response. Feel free to email support@bugsnag.com with further details.
