### ISSUE TITLE
cannot make a valid archive in Xcode 8

### ISSUE THREAD

**Issue by h3r2on** [bugsnag/bugsnag-cocoa#124]
I'm having an issue where KSCrash is getting added to my archive as a product no matter what settings I use in Xcode, thereby invalidating my archive. I've tried with cocoapods and manual installation.

ENV:
Xcode 8.1
OS X 10.11.6
bug snag: v5.6.2

**Comment by kattrali** [comment]
Thanks for the report, @h3r2on. Can you share the error message or a screenshot of what you are seeing?

**Comment by h3r2on** [comment]
There isn't really an error its the fact that when I archive my app for upload to ITC, it archives as a generic product not as an application. If I open up the archive I see a products folder with an includes folder and inside is just KSCrash and it's swift files. If I remove Bugsnag and KSCrash from my project I get a valid Application archive that I can upload to ITC. Does that make sense?

I've tried all the skip install options for both the main app and Bugsnag/KSCrash and that hasn't fixed it either. I'm not sure what else to try too include it and get a valid application archive.

**Comment by kattrali** [comment]
Gotcha. How are you installing Bugsnag?

**Comment by h3r2on** [comment]
i've tried via cocapods and manually both return the same result.

**Comment by kattrali** [comment]
Can you share your Podfile @h3r2on? I’d like to reproduce in a sample project.

**Comment by h3r2on** [comment]
my issue can be resovled by fixing issue #128
