### ISSUE TITLE
Please update to KSKrash 1.11.2

### ISSUE THREAD

**Issue by markuswinkler** [bugsnag/bugsnag-cocoa#128]
Hi,

can you please update the SDK to utilize KSKrash 1.11.2?
A lot of other packages have shifted to 1.11.2 and I can't compile with support
for Bugsnag anymore.

Thanks!
Markus

**Comment by kattrali** [comment]
Thanks for the report, @markuswinkler. Working on it. 1.11.2 includes some breaking changes, which is why I assume other libraries have updated already as well.
