### ISSUE TITLE
configuration.addOnSendError potentially triggered multiple times without any matching events in the Bugsnag dashboard

### ISSUE THREAD

**Issue by cwalo** [bugsnag/bugsnag-cocoa#1289]
### Describe the bug
For some color, we use the `configuration.addOnSendError` block as a hook to send an event through our internal events pipeline. Recently, we've seen an increase in App Hang and Out of Memory events sent to our internal events db _without_ ANY matching events in the Bugsnag dashboard for some users. For example, a single user has emitted 9k+ app hang events to our internal db and none to Bugsnag. These generally occur sometime after app launch and in rapid succession. We haven't been able to reproduce this yet, but we're trying to understand under what circumstances `addOnSendError` might be invoked multiple times for the same event. If Bugsnag fails to upload the event, would this block be invoked on retry, for instance?

We considered the possibility that our analytics publisher could be the culprit, but all events go through the same pipeline and these are the only events we see multiples of. Let me know if there's anything I can clarify or questions I can answer.

### Steps to reproduce
1. No repro steps at this time

### Environment
* Bugsnag version: 6.16.1
* CocoaPods version: N/A
* Carthage version (if any): N/A
* iOS/tvOS/macOS version(s): iOS 15.2
* Simulator or physical device: Device
* Xcode version: Xcode 13.2.1
* Swift version (if applicable):

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by xander-jones** [comment]
Hey @cwalo, to clarify the behaviour and methods here: the `addOnSendError` is called once every time you make a call to this method, most likely when you're creating the `BugsnagConfiguration` object before calling `Bugsnag.start(with: config)`. The `OnSendError` block (which you're adding in the config), is called each and every time an error is attempted to be sent, with one difference:

* in versions < 6.15.2: `OnSendError` changes to the `event` are persisted regardless of whether _this_ send completes.
* in versions >= [6.15.2](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.15.2): `OnSendError` changes are not persisted to the `event` if delivery needs to be retried.

So to answer: "If Bugsnag fails to upload the event, would this block be invoked on retry, for instance?", the quick answer is yes! However, this retry only occurs when the event store is flushed under the following conditions, so I would not expect this to 'spam' a load of events in quick succession:

* a new event is to be sent
* the network connectivity state changes
* the app starts, and Bugsnag is initialized.

For the 9k events that user sent through, were they unique? Or do they appear to be the same error repeated 9k times? One key reason that you might be seeing data in your db, but not on Bugsnag is if the event is getting rejected at the Bugsnag server for one of a few reasons like the error is discarded, the error payload is malformed, the event class or context is discarded, your organization or project is getting sampled? If you drop us a message at support@bugsnag.com with some more details of the events you're seeing and what project you'd expect to see them on Bugsnag we can investigate this a little further.

**Comment by cwalo** [comment]
> For the 9k events that user sent through, were they unique? Or do they appear to be the same error repeated 9k times?

They appear to be exclusively fatal app hangs and out-of-memory events, which I would only expect to see once per app launch. For that reason, I'm led to believe they're for the same event.

**Comment by xander-jones** [comment]
Agreed – a (fatal) App Hang or OOM should only occur once per app launch by definition as the event would crash and close the application. What I mean to ask is are all of, or a subset of the events exactly the same, do the metadata and breadcrumbs match exactly? This would suggest that the event is being sent multiple times.

Additionally, are the payloads greater than 1MB? These would be rejected by the Bugsnag servers as they'd be oversize. It's unlikely for OOMs because these don't have stacktraces or threads included, but worth mentioning just in case.

Are you able to send over a sample of these events that you're seeing to support@bugsnag.com so that we can investigate this a bit further?

**Comment by cwalo** [comment]
We don't seem to log a unique identifier that might connect our internal events to an event in Bugsnag except for the the error message ("The application was terminated while unresponsive."), "type" (app_hang, app_crash, etc.), and the event's timestamp which are all captured at the moment our event is logged (not published) - this only occurs from the `onSendError` block. I'll follow up with you over email.

**Comment by xander-jones** [comment]
Continuing this conversation in email. For future travellers, this is not an issue that will affect normal Bugsnag usage, but sending payloads from an on error callback will require you to handle deduplication if a recoverable delivery error occurs as the callback will be called for each delivery attempt.

**Comment by cwalo** [comment]
@xander-jones quick follow up. Is there a prescribed method of validating the payload size for the event?

**Comment by xander-jones** [comment]
Hey @cwalo, there's not a defined method for validating the payload size client-side I'm afraid. You could calculate the size of the properties in [the `BugsnagEvent`](https://docs.bugsnag.com/platforms/ios/customizing-error-reports/#the-bugsnagevent-class) in the callback to get a rough idea of the payload size, as the 1MB limit is calculated against the body of the payload.

**Comment by cwalo** [comment]
Gotcha. I haven't been able to create a payload that large (as best I can tell, though it's not exactly trivial to re-implement the encoder that's used during upload) so I'm finding that scenario less likely, but a few follow ups:
* Can you point me to where this payload size check happens? I couldn't find it.
* Will bugsnag perpetually retry to send an event with a payload that's too large?
* If for whatever reason the reachability class can't reach `notify.bugsnag.com`, will that trigger a perpetual retry? I saw the status page hasn't reported any outages, but stranger things have happened.
* I've been able to reliably trigger duplicate `onSend` triggers by logging an event when in airplane mode and then reconnecting. That said, reachability doesn't seem likely to cause events to spam like this. In our production logs I can see that network reachability was fine and the `createdAt` and `loggedAt` timestamps are all within a second of eachother, all suggesting the app had a reliable enough connection. That said, I _am_ seeing events logged that did not reach Bugsnag while testing the reachability scenario. 

Thanks for your help with this!

**Comment by cwalo** [comment]
Yep, that helps. What property of `BugsnagEvent` can I leverage for uniqueness? On the dashboard I see CrashReporter Key which appears to be a UUID, but I don't see that on the client. At this point I'm looking to log when we see a duplicate event and ignore it from the onSendError block.

**Comment by cwalo** [comment]
@yousif-bugsnag Replied to the original email thread with @xander-jones and included some additional details. I never know what's safe to link to via Github issues.
