### ISSUE TITLE
ios Manual Installation xcode 8

### ISSUE THREAD

**Issue by radiofrequency** [bugsnag/bugsnag-cocoa#130]
In Xcode 8 you need to add the frameworks to the embedded binaries section of the general tab or the app crashes with:

image not found

Another problem is after adding the frameworks the app is no longer recognized as an iOS app.

Should update the documentation with the correct steps for Xcode 8.

**Comment by kattrali** [comment]
Thanks for the report, @radiofrequency. I'll update the docs to indicate the Bugsnag framework needs to be added to the embedded binaries. There seems to be an issue with the headers included in KSCrash in the pinned release, as I can replicate the issue when integrating manually.
