### ISSUE TITLE
Please update to KSCrash 1.15.2

### ISSUE THREAD

**Issue by markuswinkler** [bugsnag/bugsnag-cocoa#131]
Hi,

can you please change the requirement to KSCrash 1.15.2 or tell me how to set the version in a local repo?

I tried to download bugsnag and set it manually in a local repo, but I always get the error message
```
None of your spec sources contain a spec satisfying the dependency: `KSCrash/RecordingAdvanced (> 1.11.2)`.
```
when I try to run `pod update`.

Thank you!

**Comment by kattrali** [comment]
How strange. Last time I tested 1.15.2, I had some issues building, but I'll retry.

**Comment by kattrali** [comment]
Did you try running `pod repo update`? 

```
None of your spec sources contain a spec satisfying the dependency: `KSCrash/RecordingAdvanced (= 1.15.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by kattrali** [comment]
After looking into this further, the subspec we're using (`RecordingAdvanced`) does not exist in 1.15.2, nor do some of the functions from it which we use internally. I'll have to take a deeper look at what it would mean to upgrade.

**Comment by fractalwrench** [comment]
Closing as we have forked and prefixed KSCrash within the library.
