### ISSUE TITLE
Clarify LC_FUNCTION_STARTS requirement

### ISSUE THREAD

**Issue by keith** [bugsnag/bugsnag-cocoa#1319]
Since https://github.com/bugsnag/bugsnag-cocoa/pull/1214/ bugsnag attempts to read the LC_FUNCTION_STARTS load command. Some folks, including ourselves, have generally been disabling this by passing `-no_function_starts` to the linker since locally and for release builds we have full debug info, and these otherwise don't seem to be used much* by the standard toolchain. Since this bugsnag change we've noticed some cases where we see the warning log added here:

```
[Bugsnag] [INFO] App hang detected
ERROR: BSG_KSMach.c:211: bsg_ksmachfillState(): thread_get_state: (ipc/send) invalid destination port
ERROR: BSG_Symbolicate.c:94: bsg_symbolicate(): Address 0x10c7d3092 is outside the __text section of image /Users/nvanfleet/Library/Developer/CoreSimulator/Devices/4733D9C2-18E1-40E2-BC59-4688B7356B3F/data/Containers/Bundle/Application/E1F8D5EC-5A39-4CB7-BC62-3E52E7E2C28C/Driver.app/Driver
ERROR: BSG_Symbolicate.c:157: bsg_symbolicate(): No LC_FUNCTION_STARTS, cannot symbolicate
```

Which makes sense. When adding function starts back to the binary we actually don't see a stack trace at all in this case (which I haven't traced by in the bugsnag source to understand). In general I'm hoping you can clarify what these are needed for, and what we're sacrificing by disabling them? (since general crash symbolication still appears to work correctly)

Thanks!

**Comment by xander-jones** [comment]
Hey @keith, the changes made in #1214 are designed to improve in-app symbolication of the payload _before_ it's sent to Bugsnag. This change would only be noticable if you were not uploading dSYMs for your application. If you're uploading dSYMs with full debug information, then using `-no_function_starts` should not be a problem for you at all. The drawback being if you happen to have not uploaded dSYMs for a build for any reason, and an error report is sent in, it will be less-useful than it would otherwise be if you hadn't added the `-no_function_starts` flag.

**Comment by keith** [comment]
Thanks that makes sense. We're not worried about not uploading dSYMs, so it's good to hear that our crash reporting fidelity shouldn't be affected. I'm a bit surprised that this data is preferred _over_ the debug info even for local builds. It seems like our only workarounds here are to re-enable function starts (potentially for debug builds only) or to just train folks to ignore this warning

**Comment by xander-jones** [comment]
Sure, in reality uploading dSYMs is the answer. The key goal is to not report _incorrect_ information, which can happen for example when the frame in the stack trace originates from internal private functions that have no symbols, previously we'd report the closest matching symbol, which can be very misleading (unless the dSYM was available for the stack trace to be completely symbolicated on our backend).

**Comment by keith** [comment]
Thanks for the info!
