### ISSUE TITLE
add ability to make user reports without stack trace and stopping all threads

### ISSUE THREAD

**Issue by anton-plebanovich** [bugsnag/bugsnag-cocoa#135]
Please add ability to make user reports without stack trace and stopping all threads

**Comment by kattrali** [comment]
Thanks for the suggestion, @anton-plebanovich. Currently, Bugsnag only supports reports which contain a stacktrace. Are you seeing some performance degradation or other unwanted behavior when stopping threads?

**Comment by anton-plebanovich** [comment]
Yes @kattrali, sometimes app needs to track several events at a time and this causes app glitches or freezes. Because we can include all needed data, stack trace data is excessive.

**Comment by kattrali** [comment]
Thanks for the clarification. Would you mind sending an email to support@bugsnag.com with a few links to some example error reports? I'd like to better understand the use case, maybe there is a way we could combine these better.

**Comment by anton-plebanovich** [comment]
Never mind solved my issue
