### ISSUE TITLE
BugsnagEvent.unhandled not updated when overridden

### ISSUE THREAD

**Issue by cwalo** [bugsnag/bugsnag-cocoa#1351]
### Describe the bug
While writing a test that overrides the `unhandled` value of a `BugsnagEvent`, I have observed that the value is not updated.
This property is readwrite according to the header file. https://github.com/bugsnag/bugsnag-cocoa/blob/master/Bugsnag/include/Bugsnag/BugsnagEvent.h#L91

### Steps to reproduce
```
/// The following test fails
func testUnhandledOverridden() {
    let event = BugsnagEvent()
    XCTAssertFalse(event.unhandled)
    event.unhandled = true
    XCTAssertTrue(event.unhandled) // XCTAssertTrue failed
}
```

### Environment
* Bugsnag version: 6.16.1
* CocoaPods version: N/A
* Carthage version (if any): N/A
* iOS/tvOS/macOS version(s): iOS 15.4.1
* Simulator or physical device: Simulator
* Xcode version: Xcode 13.2.1
* Swift version (if applicable): Swift 5.6

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by nickdowell** [comment]
Hi @cwalo this issue is due to `BugsnagEvent` not implementing a default initializer.

The event created with `let event = BugsnagEvent()` is missing an internal property that results in the `unhandled` getter always returning false.

The only supported way to create a `BugsnagEvent` using our public API is via `Bugsnag.notify()` or `Bugsnag.notifyError()`:

```Swift
/// The following test passes
func testUnhandledOverridden() {
    Bugsnag.notifyError(NSError(domain: "", code: 0, userInfo: nil)) { event in
        XCTAssertFalse(event.unhandled)
        event.unhandled = true
        XCTAssertTrue(event.unhandled)
        return false
    }
}
```

**Comment by cwalo** [comment]
Ah, that makes sense. In our case we're interested in being notified on non-fatal (handled) app hang events without reporting them to Bugsnag, so I'm trying to write a unit test that validates the return value of the `onSendError` block we pass to the `BugsnagConfiguration` using different `BugsnagEvent` "types". Even with the public API, I'm not seeing a straightforward way to notify Bugsnag of the same errors that it would report itself (e.g. OOMs, app hangs, thermal kills, etc.), since `BugsnagError` is not convertible to `Error`. Ideally, I could do something like this:

```
func mockAppHang(unhandled: Bool) -> BugsnagEvent {
  let error = BugsnagError()
  error.errorClass = "App Hang"
  let event = BugsnagEvent()
  event.errors = [error]
  // set event.unhandled
       
  return event
}
```

Do you have any suggestions for writing tests for the `onSendError` handler utilizing different error events?

**Comment by cwalo** [comment]
Nice! That's a decent workaround and I appreciate the suggestion. Obvious in hindsight 😅

**Comment by luke-belton** [comment]
@cwalo I've closed this issue for now, but if you have any other questions just let us know 👍
