### ISSUE TITLE
Getting an error when trying to uplaod dSYM 

### ISSUE THREAD

**Issue by yaronlevi** [bugsnag/bugsnag-cocoa#136]
I have the file "myapp.app.dSYM" located on the desktop.

From the desktop, I open the terminal and run:
`curl -F 'dsym=@/users/yaronlevi/desktop/myapp.app.dSYM' https://upload.bugsnag.com/`

But I get the error:

> curl: (43) A libcurl function was given a bad argument

This should be pretty straightforward. What am I doing wrong here?

**Comment by foygl** [comment]
`/users/yaronlevi/desktop/myapp.app.dSYM` is a path to a directory and so curl doesn't like it.

You need to send the file in `Contents/Resources/DWARF` as per the docs here: https://docs.bugsnag.com/api/dsym-upload/#manual-upload

**Comment by yaronlevi** [comment]
I've read the docs, but it is not quite clear. Should the command be:

curl -F 'dsym=@myapp.app.dSYM/users/yaronlevi/desktop' https://upload.bugsnag.com/

?

**Comment by foygl** [comment]
It should be something like `curl -F 'dsym=@myapp.app.dSYM/users/yaronlevi/desktop/Contents/Resources/DWARF/myapp' https://upload.bugsnag.com/`

Hope that helps.

**Comment by yaronlevi** [comment]
It works!
But I still can't understand it. "Contents/Resources/DWARF/myapp" is a path inside the file?

**Comment by foygl** [comment]
`myapp.app.dSYM` is actually a directory not a file, and `myapp.app.dSYM/Contents/Resources/DWARF/myapp` is the actual file you want to upload. Glad you got it working :)
