### ISSUE TITLE
Data race in UpdateAvailableMemory

### ISSUE THREAD

**Issue by randarnold** [bugsnag/bugsnag-cocoa#1381]
### Describe the bug
While running the simulator Xcode 13.4 iOS 15.5 with Bugsnag 6.17.1 and the thread sanitizer on Xcode reports a data race

### Steps to reproduce
1. Build, launch, boom

### Environment
* Bugsnag version: 6.17.1
* CocoaPods version: n/a
* Carthage version (if any): n/a
* iOS/tvOS/macOS version(s): 15.5
* Simulator or physical device: Simulator
* Xcode version: 13.4 (13F17a)
* Swift version (if applicable): 5

### Example code snippet 

Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000011f24fa9a in syscall_thread_switch ()
#1	0x000000011ef1952f in _OSSpinLockLockYield ()
#2	0x0000000112c17e05 in __tsan::ReportRace(__tsan::ThreadState*) ()
#3	0x000000011009589c in BSGRunContextUpdateTimestamp at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Helpers/BSGRunContext.m:287
#4	0x00000001100d94d7 in BSGSessionUpdateRunContext at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Payload/BugsnagSession.m:118
#5	0x000000011006f500 in -[BugsnagSessionTracker startNewSession] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/BugsnagSessionTracker.m:181
#6	0x000000011006ed8c in -[BugsnagSessionTracker startNewSessionIfAutoCaptureEnabled] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/BugsnagSessionTracker.m:142
#7	0x000000011006e8c5 in -[BugsnagSessionTracker startWithNotificationCenter:isInForeground:] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/BugsnagSessionTracker.m:63
#8	0x0000000110073fbd in -[BugsnagClient start] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Client/BugsnagClient.m:266
#9	0x000000011006b822 in +[Bugsnag startWithConfiguration:] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Bugsnag.m:62
#10	0x000000010fbb5a28 in SLAppDelegate.application(_:didFinishLaunchingWithOptions:) at /Volumes/Spotlight/Spotlight/Spotlight/App/SLAppDelegate.swift:358

Thread 7 Queue : com.apple.root.utility-qos (concurrent)
#0	0x0000000112c142b0 in __tsan_on_report ()
#1	0x0000000112c167b0 in __tsan::OutputReport(__tsan::ThreadState*, __tsan::ScopedReport const&) ()
#2	0x0000000112c17fc7 in __tsan::ReportRace(__tsan::ThreadState*) ()
#3	0x0000000110096cec in UpdateAvailableMemory at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Helpers/BSGRunContext.m:295
#4	0x0000000110096deb in __InstallTimer_block_invoke at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Helpers/BSGRunContext.m:158
#5	0x0000000112c20d96 in __tsan::dispatch_callback_wrap(void*) ()
#6	0x000000011ec45a5b in _dispatch_client_callout ()
#7	0x000000011ec4834e in _dispatch_continuation_pop ()
#8	0x000000011ec5cfe1 in _dispatch_source_invoke ()
#9	0x000000011ec57ba2 in _dispatch_root_queue_drain ()
#10	0x000000011ec5864e in _dispatch_worker_thread2 ()
#11	0x000000011efabf8a in _pthread_wqthread ()
#12	0x000000011efaaf57 in start_wqthread ()
Write of size 8 by thread 7#0	0x0000000110096cec in UpdateAvailableMemory at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Helpers/BSGRunContext.m:295
#1	0x0000000110096deb in __InstallTimer_block_invoke at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Helpers/BSGRunContext.m:158
#2	0x0000000112c20d96 in __tsan::dispatch_callback_wrap(void*) ()
#3	0x000000011ec45a5b in _dispatch_client_callout ()
Write of size 8 by thread 1#0	0x0000000110096cec in UpdateAvailableMemory at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Helpers/BSGRunContext.m:295
#1	0x00000001100965d3 in InitRunContext [inlined] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Helpers/BSGRunContext.m:67
#2	0x0000000110095ebf in BSGRunContextInit at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Helpers/BSGRunContext.m:398
#3	0x000000011007371e in -[BugsnagClient start] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Client/BugsnagClient.m:223
#4	0x000000011006b822 in +[Bugsnag startWithConfiguration:] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Bugsnag.m:62
#5	0x000000010fbb5a28 in SLAppDelegate.application(_:didFinishLaunchingWithOptions:) at /Volumes/Spotlight/Spotlight/Spotlight/App/SLAppDelegate.swift:358
#6	0x000000010fbbc4b3 in @objc SLAppDelegate.application(_:didFinishLaunchingWithOptions:) ()
#7	0x0000000129e17593 in -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] ()
#8	0x0000000112899f21 in start_sim ()
Mutex M1388 created#0	0x0000000112c1eb88 in wrap_objc_sync_enter ()
#1	0x000000011006b729 in +[Bugsnag startWithConfiguration:] at /Users/rand/Library/Developer/Xcode/DerivedData/Spotlight-gzrnvhytljuqfyflgiyhponfmupi/SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/Bugsnag.m:58
#2	0x000000010fbb5a28 in SLAppDelegate.application(_:didFinishLaunchingWithOptions:) at /Volumes/Spotlight/Spotlight/Spotlight/App/SLAppDelegate.swift:358
#3	0x000000010fbbc4b3 in @objc SLAppDelegate.application(_:didFinishLaunchingWithOptions:) ()
#4	0x0000000129e17593 in -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] ()
#5	0x0000000112899f21 in start_sim ()

Thread 7: Data race detected
Data race in UpdateAvailableMemory

**Comment by luke-belton** [comment]
Hi @randarnold - thanks for reporting, we're investigating this and will let you know about any updates.

**Comment by randarnold** [comment]
This happened several times in a row, and then not again until this morning. So not 100% reproducible, but I guess that is not surprising. Thanks!

**Comment by luke-belton** [comment]
Hi @randarnold - a [fix for this](https://github.com/bugsnag/bugsnag-cocoa/pull/1384) was released in [`v6.18.0`](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.18.0) of `bugsnag-cocoa` 🎉 thanks again for reporting!
