### ISSUE TITLE
Xcode 8.3: "ld: warning: linking against a dylib which is not safe for use in application extensions" 

### ISSUE THREAD

**Issue by anderscarling** [bugsnag/bugsnag-cocoa#140]
On Xcode 8.3, when using frameworks (`use_framework!` in `Podfile`) Bugsnag gives the following warning:
```
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/lowe/Library/Developer/Xcode/DerivedData/Test-fofohhnfxabihmakfeyfapzmetji/Build/Products/Debug-iphonesimulator/KSCrash/KSCrash.framework/KSCrash
```

Reproducible by creating a new "Single View Application" project (I went for Objective-C, probably does not matter), adding the Podfile below, installing pods and building the project.
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  use_frameworks!

  pod 'Bugsnag'
end
```

**Comment by anton-plebanovich** [comment]
set `APPLICATION_EXTENSION_API_ONLY = NO` in Bugsnag pod project fixes warning

Can't figure out how to make it work with post install script. This one doesn't work:
```
post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
end
```

**Comment by anderscarling** [comment]
@anton-plebanovich This does the trick, and only changes the Bugsnag target:
```
  bugsnag = installer.pods_project.targets.detect { |target| target.name == "Bugsnag" }
  bugsnag.build_configurations.each do |config|
    config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
  end
```

However I really feel this is something I shouldn't have to hack in my own Podfile.

**Comment by kattrali** [comment]
@anderscarling This is probably the best option. KSCrash as a whole is not extension-safe, but the subspec we are using (`KSCrash/Recording`) is safe. However, there is not a way to specify an xcconfig options for a subspec in KSCrash.podspec to prevent this warning without setting it as a global setting, which would prevent compilation for other libraries using all of KSCrash.

**Comment by anderscarling** [comment]
@kattrali  Maybe you could do a subspec of Bugsnag for people actually needing `APPLICATION_EXTENSION_API_ONLY` to be 'ON', if that is even possible?

Feels like a bad default to have the library configured in a way where it warns for everyone using use_frameworks!, when most people probably don't use it with extensions.

**Comment by kattrali** [comment]
> Maybe you could do a subspec of Bugsnag for people actually needing `APPLICATION_EXTENSION_API_ONLY` to be 'ON', if that is even possible?

It isn't possible, though in newer version of CocoaPods, removing the configuration option seems to handle the target cases correctly. I think I have a sensible solution now :)
