### ISSUE TITLE
BugsnagNetworkRequestPlugin manual logging support (no swizzling)

### ISSUE THREAD

**Issue by eseay** [bugsnag/bugsnag-cocoa#1420]
### Description

I like the extra context that `BugsnagNetworkRequestPlugin` offers in my error reports; however, I wish it didn't require that I employ method swizzling to accomplish it. Along with Bugsnag, I am using some other tooling in my app that relies upon swizzling in URLSession (I have made similar requests to the teams owning these products), and I have encountered situations where unexpected behavior occurs - including sometimes crashing - due to interference between these swizzling implementations.

While I understand that swizzling allows for a basically zero-setup implementation, which many customers may prefer, my team and I would also prefer that an API be exposed to allow for a semi-advanced, DIY usage that doesn't rely on swizzling.

**Describe the solution you'd like**

Would it be possible to expose a public function that could allow us to forward the inputs from our own `urlSession(_:task:didFinishCollecting:)` to Bugsnag without relying on method swizzling?

I don't believe that I have a strong opinion about whether that function exists on the `Bugsnag` type or on the `BugsnagNetworkRequestPlugin` (in which case the swizzling would need to also be manually started rather than occurring on init).

**Describe alternatives you've considered**

The alternative that I am using is to create my own helper function that matches the logic in `BSGURLSessionTracingDelegate.m` to craft my own breadcrumb, which I am invoking from my own URLSessionDelegate's metric collection callback.

An alternative that Bugsnag could consider is to provide a `BugsnagTracingDelegate` or something similar that can be injected at initialization of the client's `URLSession`. If clients need their own custom delegate logic, they can inherit from the Bugsnag delegate, or they can just hold a reference to a Bugsnag delegate instance in their own delegate and forward events to it.

**Additional context**

N/A

**Comment by eseay** [comment]
@luke-belton Thanks!

**Comment by nickdowell** [comment]
Support for manually logging request breadcrumbs was added in [v6.23.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.23.0) 🎉

**Comment by eseay** [comment]
@nickdowell Thank you for doing this!
