### ISSUE TITLE
User ID retaining device + app hash after it is set to `nil`

### ISSUE THREAD

**Issue by parrotbait** [bugsnag/bugsnag-cocoa#1427]
I'm working on an application whereby users can be logged out and we want to override the Bugsnag behavior which automatically sets the user ID to the app and device hash. 
We've tried setting the user ID directly on the Bugsnag client and using the `addOnSession` callback block but whenever crashes appear on the site they have the incorrect hash displayed.

<details>
<summary>Session payload</summary>

```
"sessions": [{
	"user": {},
	"id": "4F48511E-3108-4412-9AB7-91F2B0428DD4",
	"handledCount": 0,
	"unhandledCount": 0,
	"startedAt": "2022-07-07T11:09:09.812Z"
}],
```

</details>

<details>
<summary>Notify payload</summary>

```
{
	"apiKey": <redacted>,
	"payloadVersion": "4.0",
	"events": [{
		"device": {
			<redacted>
		},
		"exceptions": [{
			"message": "Unexpectedly found nil while unwrapping an Optional value",
			"errorClass": "Fatal error",
			<redacted>
			"type": "cocoa"
		}, {
			"errorReportingThread": false,
			"id": "12",
			"stacktrace": [],
			"type": "cocoa"
		}],
		"metaData": {
			"app": {
				"name": <redacted>
			},
			"device": {
				"orientation": "portrait",
				"timezone": "GMT+1",
				"wordSize": 64,
				"simulator": true,
				"batteryLevel": -1,
				"charging": false
			},
			"error": {
				"mach": {
					"code": "0x1",
					"exception_name": "EXC_BAD_INSTRUCTION",
					"subcode": "0x0",
					"exception": 2,
					"code_name": "KERN_INVALID_ADDRESS"
				},
				"type": "mach",
				"crashInfo": <redacted>,
				"address": 140734008945464
			}
		},
		"unhandled": true,
		"session": {
			"id": <redacted>,
			"startedAt": "2022-07-07T11:09:09.812Z",
			"events": {
				"handled": 0,
				"unhandled": 1
			}
		},
		"severity": "error",
		"severityReason": {
			"type": "unhandledException"
		},
		"user": {
			"id": "f762f46ae9fa37d54f9d87d9cc8a57c7d6c92095"
		}
	}],
	"notifier": {
		"name": "iOS Bugsnag Notifier",
		"version": "6.10.2",
		"url": "https:\/\/github.com\/bugsnag\/bugsnag-cocoa"
	}
}
```
</details>

And the event as shown in the console.

![Screenshot 2022-07-07 at 12 26 18](https://user-images.githubusercontent.com/2385924/177762730-ba2b93be-a60a-42b2-b78b-47e5cc62dc69.png)

We're using the iOS SDK 6.10.2 and using a hosted on premise Bugsnag instance. 

For now to work around this we're just going to set the user ID to "-".

**Comment by parrotbait** [comment]
I've updated the issue above further with the service calls captured via proxy, it's an on-premise hosted Bugsnag instance so you won't be able to access them. 

I can share only pseudo code of what I'm trying to do but it won't be especially useful I feel.

```
let userID: String? = AuthenticationService.shared.user.id // this can be `nil` if the user isn't logged in.
Bugsnag.setUser(userID, withEmail: email, andName: name)
```

I've also tried something like:

```
Bugsnag.addOnSession { session in
	let userID: String? = AuthenticationService.shared.user.id
	session.setUser(userID, withEmail: nil, andName: nil)
}
```

Using both of these approaches still sends along the device and app hash instead of `nil` for display on the console.

**Comment by parrotbait** [comment]
Ah ok - that makes sense.

I've called `setUser` on the config before the `starts(with:)` call, and also directly on the Bugsnag client after `start(with:)` so we clear down the Bugsnag fallback hash should the user be `nil` on the config. 

I'm also calling `setUser` on the Bugsnag client when users authenticate, which can happen at somewhat arbitrary times during the app lifecycle.

**Comment by parrotbait** [comment]
Ah, that's good to know. Thanks for looking into it.

**Comment by johnkiely1** [comment]
Hey @parrotbait, just to let you know we have updated the behaviour in [v6.22.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.22.0) to be consistent. 

We will now use `device.id` in place of `user.id ` for all events and sessions if `BugsnagClient.user.id` is set to `nil`. 

To prevent collection completely, set it to an empty string or update it in `OnSendError` / `OnSession`
