### ISSUE TITLE
KSCrash UndefinedBehaviorSanitizer

### ISSUE THREAD

**Issue by crossle** [bugsnag/bugsnag-cocoa#149]
Pods/KSCrash/Source/KSCrash/Recording/KSCrash.m:482:23: runtime error: variable length array bound evaluates to non-positive value 0
UndefinedBehaviorSanitizer: undefined-behavior xxxx/Pods/KSCrash/Source/KSCrash/Recording/KSCrash.m:482:23 in

**Comment by kattrali** [comment]
Thanks for the report, @crossle. Which version of bugsnag-cocoa are you using? Can you link to an example error report?

**Comment by crossle** [comment]
5.7.0, The lastest version 5.10 work well, thanks
