### ISSUE TITLE
Stacktrace on notifyError

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-cocoa#151]
I'm trying to migrate to Bugsnag and I'm having trouble figuring out the right way to log non-fatal errors.  Here's what I've got:

```
func LogNonFatal(_ message: String) {
	let isMainThead = Thread.isMainThread
	let error = NSError(domain: "co.recharge", code: 1)
	Bugsnag.notifyError(error, block: { report in
		report.errorMessage = message
		report.depth += 1 // Don't group by LogNonFatal always being at the top of the stack.
		report.addAttribute("isMainThread", withValue: isMainThead, toTabWithName: "extra")
	})
}
```
I've tried changing that `depth` value between 1 and 3, but none of them give me the desired result (displaying and grouping by stacktrace).  https://app.bugsnag.com/recharge-labs/ios/errors?filters[event.since][0]=30d&filters[error.status][0]=fixed is my project if you want to look at what it's generated.  

Do I need to manually attach the stacktrace?  Or somehow otherwise indicate that it should be captured?

**Comment by kattrali** [comment]
Thanks for the report, @edenman. I'm taking a look now. My guess is the depth still is off a bit, which might be a miscalculation in the library. Based on the [most recent instance](https://app.bugsnag.com/recharge-labs/ios/errors/596e67b9b1f76f0018660c09), it seems to need to be incremented by 1. Can you try 3 or 4?

**Comment by edenman** [comment]
I changed the messages so it's easier to tell what happens with various depths:

depth 4: https://app.bugsnag.com/recharge-labs/ios/errors/596fa660e303b40019d75739 (two different calls grouped together, no useful stacktrace)
depth 3: https://app.bugsnag.com/recharge-labs/ios/errors/596e63fd825d9100180bfc02 (two different calls grouped together, no useful stacktrace)
depth 2: https://app.bugsnag.com/recharge-labs/ios/errors/596e626bde94bf00198d4659 and https://app.bugsnag.com/recharge-labs/ios/errors/596e67b9b1f76f0018660c09 (grouping is fixed, but stacktraces are somehow even less useful?)
depth 1: https://app.bugsnag.com/recharge-labs/ios/errors/596e61739ec2d600193dc0ee (two different calls grouped together, no useful stacktrace)

**Comment by fractalwrench** [comment]
@edenman just to clarify, is the issue here that frames are missing from the StackTrace, or that error reports with the same caused aren't being grouped in the dashboard? If frames are missing, would you be able to paste the output of `print(Thread.callStackSymbols)` in `LogNonFatal` for comparison?

If the issue is with grouping, then it may be worth using a [custom grouping hash](https://docs.bugsnag.com/product/error-grouping/#custom-grouping-hash) while we investigate the issue further.

**Comment by edenman** [comment]
@fractalwrench it's both.  useful stacktrace and grouping based on that stacktrace.  Here's the thread output:

```
["0   recharge-consumer-ios               0x00000001003b1368 _TF21recharge_consumer_ios11LogNonFatalFSST_ + 136", "1   recharge-consumer-ios               0x000000010035df54 _TFC21recharge_consumer_ios21RequestViewController23searchCloseButtonTappedfT_T_ + 272", "2   recharge-consumer-ios               0x000000010035df90 _TToFC21recharge_consumer_ios21RequestViewController23searchCloseButtonTappedfT_T_ + 40", "3   UIKit                               0x000000018d265010 <redacted> + 96", "4   UIKit                               0x000000018d264f90 <redacted> + 80", "5   UIKit                               0x000000018d24f504 <redacted> + 440", "6   UIKit                               0x000000018d264874 <redacted> + 576", "7   UIKit                               0x000000018d264390 <redacted> + 2480", "8   UIKit                               0x000000018d25f728 <redacted> + 3192", "9   UIKit                               0x000000018d23033c <redacted> + 340", "10  UIKit                               0x000000018da2a014 <redacted> + 2400", "11  UIKit                               0x000000018da24770 <redacted> + 4268", "12  UIKit                               0x000000018da24b9c <redacted> + 148", "13  CoreFoundation                      0x00000001870ad42c <redacted> + 24", "14  CoreFoundation                      0x00000001870acd9c <redacted> + 540", "15  CoreFoundation                      0x00000001870aa9a8 <redacted> + 744", "16  CoreFoundation                      0x0000000186fdada4 CFRunLoopRunSpecific + 424", "17  GraphicsServices                    0x0000000188a44074 GSEventRunModal + 100", "18  UIKit                               0x000000018d295058 UIApplicationMain + 208", "19  recharge-consumer-ios               0x00000001003b3954 main + 76", "20  libdyld.dylib                       0x0000000185fe959c <redacted> + 4"]
```
The important thing is the call to `RequestViewController.searchCloseButtonTapped`, which is only included in the depth=2 issue, but unfortunately not in the actual stacktrace (just in the message?).

**Comment by edenman** [comment]
FWIW, I've been using depth=2 and I just encountered an instance of bad grouping in the wild: https://app.bugsnag.com/recharge-labs/ios/errors/59a17cc80516dd0018860f11 

First stacktrace:
```
0  recharge-consumer-ios LogNonFatal (UserActions.swift)
1  recharge-consumer-ios partial apply forwarder for static recharge_consumer_ios.UserActions.(signInOrStartSignUpWithFacebook () -> ()).(closure #2).(closure #4) (UserActions.swift)
2  recharge-consumer-ios static Async.AsyncBlock.((async in _E687294E1917D2F98ED787A27C7576C6) <A> (after : Swift.Double?, block : () -> A1, queue : Async.(GCD in _E687294E1917D2F98ED787A27C7576C6)) -> Async.AsyncBlock<(), A1>).(closure #1) (Async.swift:264:37)
3  libdispatch.dylib     __dispatch_block_async_invoke_and_release
4  libdispatch.dylib     __dispatch_client_callout
5  libdispatch.dylib     __dispatch_main_queue_callback_4CF
6  CoreFoundation        ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
7  CoreFoundation        ___CFRunLoopRun
8  CoreFoundation        CFRunLoopRunSpecific
9  GraphicsServices      GSEventRunModal
10 UIKit                 UIApplicationMain
11 recharge-consumer-ios main (APIErrorsGenerated.swift:43:7)
12 libdyld.dylib         start
```

Second stacktrace:
```
0  recharge-consumer-ios LogNonFatal (UserActions.swift)
1  recharge-consumer-ios signUp (PhoneNumberCodeViewController.swift)
2  UIKit                 -[UIApplication sendAction:to:from:forEvent:]
3  UIKit                 -[UIControl sendAction:to:forEvent:]
4  UIKit                 -[UIControl _sendActionsForEvents:withEvent:]
5  UIKit                 -[UIControl touchesEnded:withEvent:]
6  UIKit                 -[UIWindow _sendTouchesForEvent:]
7  UIKit                 -[UIWindow sendEvent:]
8  UIKit                 -[UIApplication sendEvent:]
9  UIKit                 __UIApplicationHandleEventQueue
10 CoreFoundation        ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
11 CoreFoundation        ___CFRunLoopDoSources0
12 CoreFoundation        ___CFRunLoopRun
13 CoreFoundation        CFRunLoopRunSpecific
14 GraphicsServices      GSEventRunModal
15 UIKit                 UIApplicationMain
16 recharge-consumer-ios main (APIErrorsGenerated.swift:43:7)
17 libdyld.dylib         start
```
