### ISSUE TITLE
Calling NSProcessInfo.thermalState from an app with bugsnag installed crashes with _os_unfair_lock_recursive_abort

### ISSUE THREAD

**Issue by ericcj** [bugsnag/bugsnag-cocoa#1511]
Apparently calling NSProcessInfo.thermalState can trigger NSProcessInfoThermalStateDidChangeNotification so the NoteThermalState receiver needs to dispatch its call to access NSProcessInfo.thermalState on the object sent to it or it can trigger recursion that crashes the app.  This appears to only happen ~10% of the time but we're not certain: 

<img width="751" alt="Screen Shot 2022-12-15 at 9 19 59 AM" src="https://user-images.githubusercontent.com/53106/207884585-22687d58-29ef-4f64-8d23-ac7db3d65c55.png">

**Comment by bcherry** [comment]
Note that all cases of this that we have seen so far are on iOS 15.1.0

**Comment by johnkiely1** [comment]
Hi, thanks for raising, we're going to take a look into addressing this as soon as we can.

**Comment by johnkiely1** [comment]
This should now be resolved in [v6.25.2](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.25.2).
