### ISSUE TITLE
Bugsnag build phase script to auto upload dsym with Xcode 14 failed to upload

### ISSUE THREAD

**Issue by halvi00** [bugsnag/bugsnag-cocoa#1513]
I am using swift package manager. I have added manual build phase script to upload the dsym files automatically whenever a build is archived/uploaded. 
The ruby script is not working. No dsym gets uploaded when any build is archived. 
However I was able to upload the dsym files manually from terminal using `bugsnag-dsym-upload`

I am using build phase script from the symbolication-guide under "Adding a build phase manually":
[symbolication Guide](https://docs.bugsnag.com/platforms/ios/symbolication-guide/)
### Environment
* Bugsnag version: 6.25.1
* Xcode version: 14.0.1 , 14.1

**Comment by johnkiely1** [comment]
Hi @halvi00. Have you double checked you have added the correct api key for your project you expect? Are you seeing any Bugsnag related warmings/messages in the logs? Are you able to share your version of the build script? Feel free to write in to support@bugsnag.com if you don't want to share this information publicly.

**Comment by halvi00** [comment]
Hi @johnkiely1 , Yes I'm using the same api key to upload manually using `bugsnag-dsym-upload`
I'm not seeing any bugsnag related warnings.
My build version is 1.0 . Do you want my manual script as well?

I'm using this script. [adding-a-build-phase-manually](https://docs.bugsnag.com/platforms/ios/symbolication-guide/#adding-a-build-phase-manually)

**Comment by halvi00** [comment]
Hey @johnkiely1 , any update on this?

**Comment by matth-bugsnag** [comment]
Hi [@halvi00](https://github.com/halvi00). We can’t see any reason why the custom build script provided in the docs wouldn’t work. Can you confirm that you have followed all of the steps provided in the documentation?

Did you follow step 5 from [the instructions](https://docs.bugsnag.com/platforms/ios/symbolication-guide/#adding-a-build-phase-manually) to add the dsym path to the input files list?

Do you have the ENABLE_USER_SCRIPT_SANDBOXING [build setting](https://developer.apple.com/documentation/xcode/build-settings-reference?changes=_9) enabled in your project?

Would you be able to share a screenshot of your custom build phase? If you would rather not share this publicly, you could write directly to the Bugsnag Support team ([support@bugsnag.com](mailto:support@bugsnag.com)), providing a link to this GitHub issue along with your screenshot.

**Comment by halvi00** [comment]
Hi @matth-bugsnag 

I am using the same script as provided in the docs. And yes I have followed all the steps.
I had not enabled ENABLE_USER_SCRIPT_SANDBOXING. Since I didn't need it. But I tried enabling it and it still won't work.

I have started getting this error now:

> cannot read /Users/**/Library/Developer/Xcode/DerivedData/bar-mobile-abiwryjtdnwesrechlnbvllrvdhp/Build/Intermediates.noindex/ArchiveIntermediates/bar-mobile (iOS)/BuildProductsPath/Release-iphoneos/bar-mobile.app.dSYM/Contents/Resources/DWARF/bar-mobile (iOS)


Im attaching the ss here. I have added the api key as well. Just not showing in the screenshot.
<img width="1126" alt="script" src="https://user-images.githubusercontent.com/106992368/211374086-84ee3e61-fae0-46ed-91b0-0b8c8e951967.png">

**Comment by halvi00** [comment]
Hi @matth-bugsnag 

Yes I started seeing this error after using ENABLE_USER_SCRIPT_SANDBOXING. I don't need it, so I have disabled it.

The path for the directory of dSYM is:

> /Users/hira/Library/Developer/Xcode/Archives/2023-01-03/barglance-mobile\ \(iOS\)\ 1-3-23\,\ 12.09\ PM.xcarchive/dSYMs

I don't see any environment variable set for DWARF_DYSM_FOLDER_PATH under arguments tab. Shouldn't this be set by default?

**Comment by halvi00** [comment]
Hi @matth-bugsnag ,

Using Xcode application build function, I was unable to see any output after adding this in custom build script :
 `puts "#{ENV['DWARF_DSYM_FOLDER_PATH']}"` 
 
 However running `xcodebuild` command in terminal gave the following output:
 
`DWARF_DSYM_FOLDER_PATH = /Users/<USER_DIRECTORY>/Library/Developer/Xcode/DerivedData/barglance-mobile-abiwryjtdnwesrndifncidnwp/Build/Products/Release-iphoneos`
  
`DWARF_DSYM_FILE_NAME = barglance-mobile.app.dSYM`

`TARGET_NAME = barglance-mobile (iOS)`

After building the app in simulator, this is the directory of dSYM folder:
This app is still in development.

> /Users/<USER_DIRECTORY>/Library/Developer/Xcode/DerivedData/barglance-mobile-abiwryjtdnwesrndifncidnwp/Build/Products/Debug-iphonesimulator/barglance-mobile.app.dSYM/Contents/Resources/DWARF

**Comment by halvi00** [comment]
Hi @matth-bugsnag, any update on this?

**Comment by matth-bugsnag** [comment]
Hi [@halvi00](https://github.com/halvi00),

Based on the directory paths you have provided we would expect the dSYM upload script to work as intended. Through our testing, and while trying to replicate your environment as closely as possible (Similar file paths, same Xcode version and build script), we have not be able to reproduce what you are experiencing.  

The dSYM script finds sourcemaps based on build time environment variables and wildcard usage (`*`) , which means that if a dSYM has been generated by Xcode, the BugSnag dSYM uploader script should be able to find and upload them using the scripts curl request. 

Given this, it may be worth reviewing your Xcode preferences and build settings, as the problems you are seeing potentially stem from the build not producing or outputting dSYM files as we would expect. 

In the meantime we would recommend continuing to use the `bugsnag-dsym-upload` tool to upload your sourcemaps. I appreciate that this does not solve your problem, however, from our end (based on the information we have been provided) we cannot see any reason why the dSYM files should not be getting uploaded.

**Comment by johnkiely1** [comment]
Going to close this out as we haven't heard back from you in a while and as mentioned above theres not a lot more we can do from our side. We suspect it will likely be an environmental issue which is very difficult for us to debug.
