### ISSUE TITLE
notifyError is _really_ slow

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-cocoa#152]
This is the code I'm using:
```
	let isMainThead = Thread.isMainThread
	let error = NSError(domain: "co.recharge", code: 1)
	Bugsnag.notifyError(error, block: { report in
		report.errorMessage = message
		report.depth += 2 // Don't group by LogNonFatal always being at the top of the stack.
		report.addAttribute("isMainThread", withValue: isMainThead, toTabWithName: "extra")
	})
``` 
On average, 494ms on an iPhone SE.  I'd stick it in an Async block but then the stacktrace wouldn't be correct :/

**Comment by fractalwrench** [comment]
Thanks for the report @edenman. It looks as though the KSCrash library which we use within the SDK is taking a while to record all the thread traces. I'll see if we can find an iPhone SE in the office to reproduce the issue more closely.

**Comment by edenman** [comment]
Any update on this, @fractalwrench?  I'm happy to drop by the Bugsnag offices if you need to borrow my SE to test :)

**Comment by fractalwrench** [comment]
@edenman I've profiled sending a non-fatal exception on an iPad Mini 2 running iOS 10.3.2 (Instruments trace attached).

The bottleneck is definitely in KSCrash - it takes around 600ms to write a report, of which around 1/3 was spent in writing thread information (`kscrw_i_writeAllThreads`), and the rest of which was spent serializing binary images (`kscrw_i_writeBinaryImages`). We're also currently using `kscrashreport_writeStandardReport` to record non-fatal crashes, when `kscrashreport_writeMinimalReport` and `kscrashreport_logCrash` exist, which presumably are faster at the expense of recording less information.

I'll investigate how we can speed up these two methods, or whether we can avoid them entirely. This could potentially result in a trade-off of having less information for non-fatal crashes, which we'll have to weigh up.

I'm in Bugsnag's UK office, so it may take you a while to drop by with your iPhone :)

[non_fatal_exception_trace_ipad.trace.zip](https://github.com/bugsnag/bugsnag-cocoa/files/1182505/non_fatal_exception_trace_ipad.trace.zip)

**Comment by edenman** [comment]
😂 

1) I'd be totally happy with non-fatal exceptions only grabbing the current thread's stacktrace.  Not sure this is true of everyone, but it's true for my app at least.
2) This library is on a pretty old version of KSCrash. I saw in some other tickets that upgrading was blocked at some point...is that still the case?  Newer versions may be faster at capturing other threads.

**Comment by snmaynard** [comment]
Unfortunately we've seen some pretty big reliability issues with the newer versions of KSCrash. We are looking into how to mitigate or fix those, but some of them are relatively complex. We reverted to an older known stable version while we do that process.

**Comment by edenman** [comment]
@snmaynard makes sense, I saw tons of reliability issues with KSCrash when I was using Sentry (links [here](https://github.com/getsentry/sentry-cocoa/issues/166)).  

I'd vote for a flag or a separate method that only captures the current stacktrace (if possible).

**Comment by edenman** [comment]
Any movement on this?  Is such a "only capture this thread's stack" flag/method possible, or are we stuck waiting for newer versions of KSCrash to stabilize?

**Comment by kattrali** [comment]
I think the winning solution in the shorter term is probably to experiment with using `kscrashreport_writeMinimalReport` as @fractalwrench mentioned. Beyond that, I think we need to retool how we are capturing crash data altogether, which has been a bit more daunting.

**Comment by edenman** [comment]
👍 I don't actually see any calls to `kscrashreport_writeStandardReport` or I'd just submit a PR myself...wanna point me in the right direction?  Or would you guys prefer to make the change yourselves?

**Comment by fractalwrench** [comment]
Using `kscrashreport_writeMinimalReport` brought the execution time down to ~128ms on an iPad Mini 2 (10.3.2). However, there are some obstacles to this approach. 

Firstly, I can't see any obvious API in KSCrash to write only minimal reports, without altering its source code directly. Secondly, the minimal report doesn't appear to be written to disk by default, meaning it isn't returned in the completion block by KSCrash and is therefore not sent to the Bugsnag API. And finally, it would be nice to reduce that execution time further, preferably below 15ms.

@edenman

**Comment by edenman** [comment]
sgtm, thanks for moving this forward!

**Comment by fractalwrench** [comment]
After debugging this further, the bottleneck appears to be within KSCrash in `kscrw_i_addJSONData`, which always calls `ksfu_writeBytesToFD`. It looks as though every time a JSON field/element is added to the crash report payload, KSCrash makes a `write` syscall.

I think the approach we'll here is to allocate a buffer of a few Kb as soon as Bugsnag initialises, as this will allow us to reduce the number of syscalls. This will hopefully get the performance for non-fatal errors to an acceptable level.

[notify_err_trace.trace.zip](https://github.com/bugsnag/bugsnag-cocoa/files/1232801/notify_err_trace.trace.zip)

**Comment by fractalwrench** [comment]
I benchmarked this again on an iPhone 7, using a development build that forked KSCrash, allowing us to buffer IO using `fwrite`. Notification of non-fatal errors took 44ms, compared to 200ms on the currently deployed version.

We might be able to squeeze a bit more performance out of `kscrw_i_writeAllThreads`, as that's now taking up around half the CPU time Another option would be to allow users to configure whether only the current thread's trace should be captured, as that would effectively halve 44ms to around 22ms.
