### ISSUE TITLE
Uploading dSYM seems to not working using Build phase script manually

### ISSUE THREAD

**Issue by Kiimlee** [bugsnag/bugsnag-cocoa#1555]
Hello,

I'm having problems getting error code line in Bugsnag consol, I don't see the line crashing code (see first screen).

<img width="1136" alt="Capture d’écran 2023-05-09 à 11 03 44" src="https://user-images.githubusercontent.com/10152608/237048432-89a5247b-350a-44cc-b9b7-c4506dcbd818.png">

I have Xcode 14.0.1 version and installed Bugsnag via cocoapods but for some reason I cannot install the plugin so I manually craeted the Run Script like suggested in ur guide https://docs.bugsnag.com/platforms/ios/symbolication-guide/#using-manual-downloads, I don't have Bitcode nor Sandbox enabled in my project.

This is what my build phase looks like (i remove the api key just for the screen shot, see second screen)
<img width="1833" alt="Capture d’écran 2023-05-09 à 11 24 12" src="https://user-images.githubusercontent.com/10152608/237053747-cf00c687-e0c9-47e8-8b2c-a1ad43a9c284.png">

Thank u in advance and wait for ur answer.

**Comment by johnkiely1** [comment]
Hey @Kiimlee, at first glance everything looks to set up correctly.  

Do you see any BugSnag related logs or error messages in your build log? 
Are the dSYMs actually being generated by your project at that Input file location? 
 
Would you mind writing in to support@bugsnag.com and tell us which project this relates to? If you could include the apikey you are using we may be able to check our logs to see if there was any issues accepting the upload. If you could include the url link to the error in question on your BugSnag dashboard it would also help.
