### ISSUE TITLE
Bugsnag keep user data after logout in crash reports

### ISSUE THREAD

**Issue by piotrtorczynski** [bugsnag/bugsnag-cocoa#1585]
### Describe the bug
I am facing an issue when user logs out from the application(and Bugsnag too) and then some crash can occur. While looking at crash reports, I've seen that crash reports still keep both user's email and id. I would expect not to see this happen. This happens only for crashes. While using `Bugsnag.notify(` I don't see that happening.

### Steps to reproduce
1. Have an all setup application with Bugsnag
2. After login use `Bugsnag.setUser(` with some user data
3. Perform logout with `Bugsnag.setUser(nil, withEmail: nil, andName: nil)`
4. Perform a crash like 
```swift
let array: Int = []
print(array[4])
```

### Environment
* Bugsnag version: 6.27.0
* iOS version(s): 16.4, 17.0
* Simulator or physical device: Simulator
* Xcode version: 14.3.1 and 15.0

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```swift
// Set user for Bugsnag
Bugsnag.setUser(String(account.user.id), withEmail: account.user.email, andName: nil)

// Do some actions

// Log out user from Bugsnag
Bugsnag.setUser(nil, withEmail: nil, andName: nil)


// Crash the app
let array: Int = []
print(array[4])
```

</details>

**Comment by mclack** [comment]
Hi @piotrtorczynski 
Thanks for bringing this to our attention. I have reproduced the behaviour you are seeing and added an item to our backlog to investigate this further.
We'll make sure to post any updates on this thread!

**Comment by clr182** [comment]
Hi @piotrtorczynski 
Thank you for your patience. We have just released a new version of our cocoa notifier. [v6.27.3](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.27.3) should fix this issue. Please let us know if you continue to see this behaviour after updating.
