### ISSUE TITLE
Propagate the message from fatalError/preconditionFailure/assertionFailure into the Bugsnag issue

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-cocoa#159]
I commented on #132 but got no response.  It'd be really helpful to do something like https://github.com/getsentry/sentry-cocoa/pull/188/files to get the message from forced crashes.

**Comment by kattrali** [comment]
Thanks for the bump, @edenman. We'll take a look.

**Comment by kattrali** [comment]
Fixed in v5.13.0

**Comment by edenman** [comment]
This rules.  Thanks so much!
