### ISSUE TITLE
Privacy manifest causing collisions through CocoaPods

### ISSUE THREAD

**Issue by nabs-m** [bugsnag/bugsnag-cocoa#1626]
The `6.28.0` release added a privacy manifest, but its current setup with CocoaPods is causing collisions with other privacy manifest files. An example error we get is:

`Error in fail: Multiple files would be placed at "PrivacyInfo.xcprivacy" in the bundle, which is not allowed.`

I believe this is because the `PrivacyInfo.xcprivacy` is referenced as a `resources` in the [podspec](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Bugsnag.podspec.json#L56-L58) instead of using `resource_bundle`. The latter would avoid collisions by putting the privacy manifest file in subfolders for each dependency, instead of going in the app bundle's root. More context on this [here](https://github.com/google/promises/pull/226#discussion_r1447871477). I think the fix would be to simple swap `resource` with `resource_bundle` here.

**Comment by clr182** [comment]
Hi @nabs-m 

Thank you for reaching out and raising this issue. 

I have passed this information onto our engineers so that they may investigating the approach you suggested further. Once we have more information to share we will be sure to update this thread.

**Comment by nabs-m** [comment]
I see this was fixed [here](https://github.com/bugsnag/bugsnag-cocoa/pull/1630). Thanks folks.
