### ISSUE TITLE
Apple Report Missing API declaration

### ISSUE THREAD

**Issue by Paladinfeng** [bugsnag/bugsnag-cocoa#1638]
ITMS-91053: Missing API declaration - Your app’s code in the file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

**Comment by clr182** [comment]
Hi @Paladinfeng 

The issues have been fixed in [v6.28.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.28.0) of the BugSnag cocoa notifier. Please update to the [latest version](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.28.1) to resolve your issue. If you see issues after updating please let us know and we can investigate further.

**Comment by regularberry** [comment]
We're seeing `NSPrivacyAccessedAPICategoryDiskSpace` still being flagged even though we're on 6.28.0. We include the project through Swift Package Manager (through Tuist)
