### ISSUE TITLE
New versions not on cocoapods?

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-cocoa#168]
I'm trying to upgrade from 5.10.1 to 5.11.1 so I can get the faster non-fatal logging, but cocoapods can't seem to find the new versions.  I tried

- `pod repo update`
- `pod update Bugsnag`
- updating cocoapods itself `gem install cocoapods` (to 1.3.1)
- manually specifying `~> 5.11` on the Bugsnag pod + `pod install`

No luck with any of them.  Am I missing something simple here?  Or are the new versions just not yet propagated to cocoapods?

**Comment by fractalwrench** [comment]
@edenman the new version hasn't been added to Cocoapods yet, this should be resolved shortly.

**Comment by fractalwrench** [comment]
sorry for the wait @edenman - `5.11.2` is now available on Cocoapods!
