### ISSUE TITLE
Warning: umbrella header for module 'Bugsnag' does not include header 'BugsnagCorrelation.h'

### ISSUE THREAD

**Issue by lawgimenez** [bugsnag/bugsnag-cocoa#1681]
### Describe the bug
After archiving our app, there's a warning thrown that says

```
...SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/include/Bugsnag/Bugsnag.h:393:1: warning: umbrella header for module 'Bugsnag' does not include header 'BugsnagCorrelation.h'

```

### Steps to reproduce
1. After archiving my app

### Environment
* Bugsnag version: 6.30.0
* CocoaPods version:
* Carthage version (if any):
* iOS/tvOS/macOS version(s): NA
* Simulator or physical device:
* Xcode version:  15.4 (15F31d)
* Swift version (if applicable):

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```
SourcePackages/checkouts/bugsnag-cocoa/Bugsnag/include/Bugsnag/Bugsnag.h:393:1: warning: umbrella header for module 'Bugsnag' does not include header 'BugsnagCorrelation.h'

```
</details>

**Comment by ivopintodasilva** [comment]
This also happens to me in the latest version ☝️

**Comment by clr182** [comment]
Hi 👋  
 
Thank you for reaching out and reporting this issue. We are investigating this issue and will be sure to update this thread when we have more information

**Comment by lawgimenez** [comment]
Thank you!
