### ISSUE TITLE
False OOM crash reports

### ISSUE THREAD

**Issue by prabhuamol** [bugsnag/bugsnag-cocoa#1687]
### Describe the bug
We are seeing a lot of crashes incorrectly reported as OOMs in bugsnag. Looking at breadcrumbs the available memory is around 2GB right before the app crashes. The memory usage of the app is around 70MB. This is causing a lot of noise in our reports. Is there a way for us to filter these false positives? Looks like Bugsnag needs better heuristics to report a crash as OOM  

Heres some breadcrumb , App and device info at the time of the crash report
<img width="1384" alt="Screenshot 2024-08-07 at 11 29 28 AM" src="https://github.com/user-attachments/assets/84166a5c-7b12-49cd-9625-0b73a89cf3b9">
<img width="1398" alt="Screenshot 2024-08-07 at 11 29 41 AM" src="https://github.com/user-attachments/assets/05338370-2b8d-44b3-915b-d26c3ea9192f">
<img width="1405" alt="Screenshot 2024-08-07 at 11 29 35 AM" src="https://github.com/user-attachments/assets/97df0fa3-3b78-4c68-8232-efd6809e39bc">
<img width="1326" alt="Screenshot 2024-08-07 at 11 29 19 AM" src="https://github.com/user-attachments/assets/a5317eb9-9f50-4fc3-990f-198ba971c251">

### Environment
* Bugsnag version: 6.28.0
* CocoaPods version:
* Carthage version (if any):
* iOS/tvOS/macOS version(s): iOS 16
* Simulator or physical device: Physical device
* Xcode version: 15.4
* Swift version (if applicable):

**Comment by prabhuamol** [comment]
@hannah-smartbear So i looked at it more and we do get a "Memory Warning" state right before the crash when the app is actually running out of memory. This state is not present for "false" OOM crashes. I wonder we can use that to categorize these errors differently. Somthing like below 

Do the following in `addOnSendErrorBlock`

```
 if([[event.errors firstObject].errorClass isEqualToString:@"Out Of Memory"]) { 
 BOOL memoryWarningReceived = NO;
 for (BugsnagBreadcrumb *breadCrumb in event.breadcrumbs) {
       if (breadCrumb.type == BSGBreadcrumbTypeState && [breadCrumb.message isEqualToString:@"Memory Warning"]) {
           memoryWarningReceived = YES;
          break;
          }
 }
   if (!memoryWarningReceived) {
          event.errors[0].errorClass = @"Unknown error";
   }

     return YES;
}
```

**Comment by hannah-smartbear** [comment]
Hi @prabhuamol,

If you find that the `UIApplicationDidReceiveMemoryWarningNotification` breadcrumb being present is an accurate way to determine that the crash is actually an OOM in your case, then yes iterating through the breadcrumbs and changing the error class if the memory warning is present is a good workaround.

However please be aware that our engineers have found the heuristic that we currently use to be more accurate than low memory warnings in determining OOMs, as: 

- The low memory warning doesn’t necessarily mean that the device was actually low on memory. iOS treats memory very fluidly in order to keep things running smoothly, and as such it could give a low memory warning when it's simply being used for caching, for example.

- That breadcrumb may not be present in the case of some OOMs, for example if there wasn’t enough free disk space to write the breadcrumb

Unfortunately we don’t have an ETA that we can give as to when we will make and release updates to our OOM reporting.

**Comment by prabhuamol** [comment]
> Hi @prabhuamol,
> 
> 
> 
> If you find that the `UIApplicationDidReceiveMemoryWarningNotification` breadcrumb being present is an accurate way to determine that the crash is actually an OOM in your case, then yes iterating through the breadcrumbs and changing the error class if the memory warning is present is a good workaround.
> 
> 
> 
> However please be aware that our engineers have found the heuristic that we currently use to be more accurate than low memory warnings in determining OOMs, as: 
> 
> 
> 
> - The low memory warning doesn’t necessarily mean that the device was actually low on memory. iOS treats memory very fluidly in order to keep things running smoothly, and as such it could give a low memory warning when it's simply being used for caching, for example.
> 
> 
> 
> - That breadcrumb may not be present in the case of some OOMs, for example if there wasn’t enough free disk space to write the breadcrumb
> 
> 
> 
> Unfortunately we don’t have an ETA that we can give as to when we will make and release updates to our OOM reporting.

Thanks @hannah-smartbear will take  that into account. Unfortunately we have seen quite a few OOMs that are not related to App memory consumption. For example the app only consuming 100MB but the device is OOM and the app is killed. So trying to see if we can at least detect that case. I also submitted https://github.com/bugsnag/bugsnag-cocoa/issues/1691
Which could help a lot as we can check free memory for the app and have some threshold.  < 1mb for example and consider that as an OOM. We do have that information for the device but not the App. And it's definitely available but just not exposed via an API. I hope you can get that request in.

**Comment by prabhuamol** [comment]
We can then use a combination of low memory warnings and free memory information for the app to detect an OOM vs device OOM. Maybe more reliable

**Comment by Kuniwak** [comment]
@hannah-smartbear

> Out of Memory errors on iOS cannot be detected directly by BugSnag, as Apple doesn’t provide an event hook for these, so we use a heuristic.

Would it be possible to use Jetsam Event Reports?
https://developer.apple.com/documentation/xcode/identifying-high-memory-use-with-jetsam-event-reports
