### ISSUE TITLE
Forced crash not uploaded when using 5.11.2

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-cocoa#170]
### Expected behavior
I'm using `fatalError` to force a crash during a very specific part of my app that only I can access.  I expect the crash to be uploaded to Bugsnag.

### Observed behavior
I just pushed a build to TestFlight that uses Bugsnag pod version `5.11.2`, and this crash does not seem to be uploaded.  https://app.bugsnag.com/recharge-labs/ios/errors/59c430573ed28e0019e60b42 is a previous occurrence of the issue.  I relaunched the app after the forced crash, waited a few minutes, and the new occurrence still does not show up in Bugsnag's web UI.

**Comment by fractalwrench** [comment]
Thanks for the report @edenman - I've confirmed that this is a regression in v5.11.2. I'm looking into this as a priority.
