### ISSUE TITLE
Try to get the stacktrace of an error to modify the context of an error

### ISSUE THREAD

**Issue by SantiagoLazzari** [bugsnag/bugsnag-cocoa#172]
### Expected behavior
I want to iterate in the stacktrace of an error to set a correct context. 

Using
``` objective-c
+ (void)addBeforeSendBlock:(MLBeforeSendBlock _Nullable)beforeSendBlock
{
	[[Bugsnag configuration] addBeforeSendBlock: ^bool (NSDictionary *_Nonnull rawEventData, BugsnagCrashReport *_Nonnull reports) {
              .
              .
              .
	}];
}
```

Using rawEventData to get the stacktrace i had to make rawEventData[@"crash"][@"threads"] to get the threads.

for each particular thread 
thread[@"backtrace"][@"contents"] to get the content of the backtrace.

### Observed behavior

When trying in debug this feature works propertly but in release doesnt works, i was wondering if bitcode doesnt let me walk through the stacktrace correctly

### Version

5.10.1

building my app in xcode 9

### Additional information

My app uses bitcode and I update the dsyms in every release

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by kattrali** [comment]
@SantiagoLazzari Depending on what is in the block (are you modifying by symbol names? file names?) the information needed to modify the stacktrace may not be available in a release build. Can you share a bit more about your use case?

**Comment by SantiagoLazzari** [comment]
@kattrali The algorithm consists in these steps
### Algorithm 
1. Iterate in the stacktrace
2. Search for de first (from the source of the exception to the main) class that is in the stacktrace that belongs to one module of my app by comparing prefixes.
3. If there is a match, set the context of the module that correspond to that prefix
4. If there is no match then set a generic context

This algorithm is implemented using the beforeSendBlock and rawEventData as mentioned in the description of the issue.
The only use of the block is to change the context of the error to the appropriate one

### Summary
The block (`beforeSendBlock`) iterate in the stacktrace (part of the `rawEventData`) and checks if there is any occurrence of a class belonging to any of my modules then will set the context of that error to the appropriate module.  

### Answering
No, there is need to modify the stacktrace, the only information needed is the stacktrace itself.

### Problem

In debug mode works properly, but when the app is in the appstore (uploaded with bitcode and dsyms in bugsnag) doesn't work.

**Comment by kattrali** [comment]
Ah, I understand now. Release builds are optimized to not have the symbol data required to make this transformation work. However, if there are some values which would be more useful as context than the default, I'd recommend suggesting some examples to support@bugsnag.com so we can see how to improve context calculation.
