### ISSUE TITLE
Xcode 8.3.3 warning due to targeting iOS 6.0

### ISSUE THREAD

**Issue by DavidPotter** [bugsnag/bugsnag-cocoa#184]
### Expected behavior
No warnings when building an Xcode project that uses CocoaPods to depend on Bugsnag.

### Observed behavior
Xcode displays a "Buildtime" warning on Pods.xcodeproj stating "Update to recommended settings".  Clicking on the warning displays a view with an issue in Bugsnag:  "An iOS Deployment Target earlier than 8.0 is not supported by this version of Xcode. This will update the value for Target 'Bugsnag' to '8.0'."

### Steps to reproduce
Add `pod 'Bugsnag'` to your Podfile
Run `pod install`
Load your Xcode project and build

### Version
Xcode 8.3.3
Bugsnag 5.11.2

**Comment by fractalwrench** [comment]
Thanks for the report @DavidPotter - this should just be a case of updating the iOS version in our podspec. I'm also seeing another warning on XCode 9 which appears to be an issue with how Cocoapods constructs the project: https://github.com/CocoaPods/CocoaPods/issues/6863

**Comment by fractalwrench** [comment]
@DavidPotter this is now available in v5.13.0.

**Comment by DavidPotter** [comment]
@fractalwrench Problem solved.  Thanks for the quick response.
