### ISSUE TITLE
Grouping behavior with custom groupingHash

### ISSUE THREAD

**Issue by keith** [bugsnag/bugsnag-cocoa#198]
### Expected behavior

Currently for logs that developers opt in to, we set the `groupingHash` to a custom value (the string from the log) with the intention that on Bugsnag all of the same logs will be grouped together.

### Observed behavior

We've ended up for different entries on bugsnag for what appear to be the same log. Example:

![image](https://user-images.githubusercontent.com/283886/32066539-fa745d38-ba34-11e7-9535-808e92cb25dc.png)

### Steps to reproduce

1. Set a custom grouping has to the same string for many logs
2. Send the same log multiple times

### Version

5.12.1

### Additional information

Links to those 3 events:

https://app.bugsnag.com/lyft-1/passenger-ios/errors/59f13f7061912c0018d549c0?filters%5Bevent.since%5D%5B%5D=7d&filters%5Bversion.seen_in%5D%5B%5D%5Bvalue%5D=5.*&filters%5Bversion.seen_in%5D%5B%5D%5Btype%5D=eq
https://app.bugsnag.com/lyft-1/passenger-ios/errors/59f13f7061912c0018d549c4?filters%5Bevent.since%5D%5B%5D=7d&filters%5Bversion.seen_in%5D%5B%5D%5Bvalue%5D=5.*&filters%5Bversion.seen_in%5D%5B%5D%5Btype%5D=eq
https://app.bugsnag.com/lyft-1/passenger-ios/errors/59f13f7061912c0018d549c6?filters%5Bevent.since%5D%5B%5D=7d&filters%5Bversion.seen_in%5D%5B%5D%5Bvalue%5D=5.*&filters%5Bversion.seen_in%5D%5B%5D%5Btype%5D=eq

**Comment by fractalwrench** [comment]
Thanks for the report @keith - I've passed this onto our backend team who will investigate why those events didn't group correctly.

**Comment by fractalwrench** [comment]
I've been told by our backend team that this occurs when separate report payloads with the same `groupingHash` are processed at exactly the same time. We have an internal ticket raised to address this issue.

**Comment by fractalwrench** [comment]
The issue on our backend has now been resolved - please get in touch if you see this happening again.

**Comment by keith** [comment]
Thanks!


--
Keith Smiley
