### ISSUE TITLE
Are breadcrumbs not thread-safe?

### ISSUE THREAD

**Issue by edenman** [bugsnag/bugsnag-cocoa#199]
https://app.bugsnag.com/recharge-labs/ios/errors/59f2781c96d78c00199afa65

### Expected behavior
non-fatal error is logged to the server, even if somebody tries to add a breadcrumb while we're in the middle of a `notifyError` call.

### Observed behavior
SIGABRT
https://app.bugsnag.com/recharge-labs/ios/errors/59f2781c96d78c00199afa65
The top level stacktrace just has one useful line #: `AppDelegate.swift:226` which is a call to `Bugsnag.leaveBreadcrumb(withMessage: logMessage.message)`
In the "threads" view, thread 19 is in the middle of doing a `Bugsnag.notifyError`

### Steps to reproduce
Unclear.  I have not been able to repro this myself.  But I imagine if you made an infinite loop that just called `leaveBreadcrumb` and then occasionally fired off calls to `notifyError`, you'd eventually trigger it.

### Version
5.13.0

### Additional information
I made the change to run notifyError from a background thread in a version of our app that went live on 10/15, and it just today (10/26) triggered this error, so I'm guessing it's a pretty rare race condition-y situation.

**Comment by fractalwrench** [comment]
Thanks for the report @edenman - I'll give those reproduction steps a go.

**Comment by fractalwrench** [comment]
The following code reproduces the issue after a few thousand iterations:
    
    for (int k = 0; k < 10000; k++) {
        NSLog(@"Attempt: %d", k);
        [Bugsnag leaveBreadcrumbWithMessage:@"generate non-fatal exception"];
        
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
            NSError *error = [NSError errorWithDomain:@"thread test" code:0 userInfo:nil];
            [Bugsnag notifyError:error];
        });
    }

This also seems to apply to other methods in our public API.

**Comment by fractalwrench** [comment]
Fixed in v5.13.2
