### ISSUE TITLE
endless loop (?) when app itself is using Reachability

### ISSUE THREAD

**Issue by tanel** [bugsnag/bugsnag-cocoa#21]
It seems, in that case there are two different instances of Reachability. Bugsnag will try to attach network information:

[event addAttribute:@"Network" withValue:self.networkReachability toTabWithName:@"device"];

but it will fail, because if the other Reachability instance is used, it has no currentReachabilityString. 

This exception will continue to be thrown:

[Reachability currentReachabilityString]: unrecognized selector sent to instance

Until the app crashes.

**Comment by snmaynard** [comment]
We've rewritten the library to use KSCrash which is likely to mean that this particular issue is fixed - let us know if you are still having problems with it!
