### ISSUE TITLE
[Crash] EXC_BAD_ACCESS in `bsg_kscrashstate_i_onIntegerElement`on Bugsnag startup, attempting to load persistent state of crash context

### ISSUE THREAD

**Issue by jessesquires** [bugsnag/bugsnag-cocoa#218]
### Expected behavior

Calling `-[Bugsnag startBugsnagWithApiKey:]` doesn't crash.

### Observed behavior

Calling `-[Bugsnag startBugsnagWithApiKey:]` crashes.

### Steps to reproduce

Unsure, but this is happening on application launch. We call `-[Bugsnag startBugsnagWithApiKey:]` in the `AppDelegate`. 

The crash is happening [here](https://github.com/bugsnag/bugsnag-cocoa/blob/516333a8553b3417a857a702b43698c97df9ced9/Source/KSCrash/Source/KSCrash/Recording/BSG_KSCrashState.c#L106), in `bsg_kscrashstate_i_onIntegerElement` in the call to [`strcmp`](http://www.cplusplus.com/reference/cstring/strcmp/). `name` is `NULL`, which seems to be the issue.

### Version

`5.13.3`, `5.14.1` (possible that earlier version are affected)

### Stack trace

![screen shot 2017-12-04 at 11 25 47 am](https://user-images.githubusercontent.com/2301114/33572684-7df8bc7c-d8e8-11e7-9dc0-5d1a7c7899d9.png)

**Comment by kattrali** [comment]
Thanks, @jessesquires. Looking into it.

**Comment by kattrali** [comment]
Which version were you using before 5.14.1?

**Comment by jessesquires** [comment]
@kattrali We were on `5.13.3`, which also experiences the issue. (Will update original comment)

**Comment by kattrali** [comment]
@jessesquires Can you send me a crash report from a device via support@bugsnag.com ? I've found some potential leads but haven't reproduced this case. In general, reading/writing to disk seems to be working correctly when using 5.14.1 (and with stored reports generated on 5.13 and earlier).
