### ISSUE TITLE
Rake task to upload RubyMotion generated binary

### ISSUE THREAD

**Issue by kapso** [bugsnag/bugsnag-cocoa#22]
I was on a HipChat room with some of your technical folks and they had mentioned adding a rake task for this. Has this been implemented?

Or it will be nice to have this info on your website.

**Comment by snmaynard** [comment]
You should be able to take the code we have to automatically upload dsyms and put it into rake.

```ruby
fork do
  Process.setsid
  STDIN.reopen("/dev/null")
  STDOUT.reopen("/dev/null", "a")
  STDERR.reopen("/dev/null", "a")

  require 'shellwords'

  Dir["#{ENV["DWARF_DSYM_FOLDER_PATH"]}/*/Contents/Resources/DWARF/*"].each do |dsym|
    system("curl -F dsym=@#{Shellwords.escape(dsym)} -F projectRoot=#{Shellwords.escape(ENV["PROJECT_DIR"])} https://upload.bugsnag.com/")
  end
end
```

This is designed to be run in the xcode build process, but the curl line is really what you need to get it to upload the dsym.
