### ISSUE TITLE
[Feature Request] Show platform word size as device property

### ISSUE THREAD

**Issue by benasher44** [bugsnag/bugsnag-cocoa#227]
For some crashes, we'd like to be able to quickly know if a crash is more common on 32-bit devices vs 64-bit devices. To do this today, you have to extrapolate this information based on device models sent up to Bugsnag. It would be amazing if this could be added as information collected in [`BSGParseDevice`](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/BugsnagKSCrashSysInfoParser.m). In a recent crash we were debugging, we found that it only happened on 32-bit devices after hours of testing, trying different scenarios, and eventually seeing a pattern. To help better triage this kind of crash in the future, a device property called "wordSize" could be collected and have as the value the size of a word in bits (i.e. 32 or 64).

Is this something that could be added easily to the SDK and then exposed on the web, so that we can make a custom filter to track it?

Thanks for your consideration!

**Comment by kattrali** [comment]
That's a great suggestion, @benasher44. It would be trivial to include `wordSize` by default too.

**Comment by benasher44** [comment]
Awesome! Hoping we can land #228 for this then :)

**Comment by fractalwrench** [comment]
Thanks for the PR :)
