### ISSUE TITLE
"Session Tick!" is continuously logged to console

### ISSUE THREAD

**Issue by ronaldsmartin** [bugsnag/bugsnag-cocoa#229]
### Expected behavior
This log is a bit noisy and should not appear while debugging. 🙂 

### Observed behavior
`Session Tick!` is logged every minute.

![image](https://user-images.githubusercontent.com/3240322/35243654-85263ffa-ff72-11e7-8307-08a5adc14129.png)

### Steps to reproduce
Nothing specific, it just happens.

### Version
5.15.0-beta0

### Additional information
Looks like it's coming from here: https://github.com/bugsnag/bugsnag-cocoa/blob/6eb9ffd2a02ed743b2c30f16e55a49d218e27f21/Source/BugsnagNotifier.m#L413

**Comment by kattrali** [comment]
Thanks for the report, @ronaldsmartin. Fixed in v5.15.3.

**Comment by ronaldsmartin** [comment]
Awesome, thanks @kattrali & @fractalwrench!
