### ISSUE TITLE
Print error information

### ISSUE THREAD

**Issue by Bitcosoftware** [bugsnag/bugsnag-cocoa#230]
Would be nice if the Bugsnag website had the ability to print out the bug information into some kind of report.

**Comment by kattrali** [comment]
Thanks for the report, @Bitcosoftware. Is the format provided by the "Raw" button on error reports similar to what you're looking for, or something else? We also have an [API](https://bugsnagapiv2.docs.apiary.io/#reference) and [ruby toolkit](https://github.com/bugsnag/bugsnag-api-ruby)

**Comment by kattrali** [comment]
Thanks for the clarification, @Bitcosoftware. I'm forwarding your request to the product team. As there isn't a next step that I can take from the library side, I'm going to close this issue but feel free to follow up via support@bugsnag.com.
