### ISSUE TITLE
No breadcrumbs on client v5.14 and above

### ISSUE THREAD

**Issue by paulz** [bugsnag/bugsnag-cocoa#249]
### Expected behavior
Expecting to see breadcrumbs in error reports

### Observed behavior
No breadcrumbs tab

### Steps to reproduce
Use latest client cocoa pod with hosted server.

### Version
5.14

### Additional information
Works with 5.13.5

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by snmaynard** [comment]
@paulz I believe your instance has just been upgraded (or possibly is in process) and that should mean that it works with the latest notifier. If that is not the case feel free to reach out to support@bugsnag.com!
