### ISSUE TITLE
Cannot use multiple Bugsnag instances

### ISSUE THREAD

**Issue by gizmosachin** [bugsnag/bugsnag-cocoa#278]
### Expected behavior
Let's say I'm a framework developer who wants to use Bugsnag for tracking crashes. I instantiate Bugsnag in my framework code:
```objective-c
BugsnagConfiguration *configuration = [BugsnagConfiguration new];
configuration.apiKey = @"apiKey1";
[Bugsnag startBugsnagWithConfiguration:configuration];
```

Separately, an app developer consuming my framework also decides to use Bugsnag:
```objective-c
BugsnagConfiguration *configuration = [BugsnagConfiguration new];
configuration.apiKey = @"apiKey2";
[Bugsnag startBugsnagWithConfiguration:configuration];
```

I expect Bugsnag to recognize that the API keys are different and internally uses different `notifier`s and other shared state so that clients with different API keys receive the information that corresponds to each respective configuration.

### Observed behavior
The one `notifier` internal to the `Bugsnag` class is set to a `BugsnagNotifier` associated with the API key that was passed to the `start` method most recently.

This means that if an app developer starts Bugsnag, then initializes my framework (which starts Bugsnag with its own configuration), the Bugsnag application associated with my framework's API key receives *all events*, and the Bugsnag application associated with the app developer's API key receives *no events*.

I've attached a sample project which demonstrates this behavior, as seen from the Bugsnag dashboards for two separate Bugsnag applications here:

<img width="876" alt="framework" src="https://user-images.githubusercontent.com/193174/39542414-816e21e6-4e16-11e8-8683-b2873a8f38eb.png">
<img width="640" alt="app" src="https://user-images.githubusercontent.com/193174/39542416-82e28b0c-4e16-11e8-9b5e-e49ec4324fc4.png">

### Steps to reproduce
- Start `Bugsnag` with configuration with API key 1
- Start `Bugsnag` with configuration with API key 2
- => The internal `BugsnagNotifier` is overwritten by the second call to `startBugsnagWithConfiguration`, so the app associated with API key 1 no longer receives any events.

### Version
`master`, and all prior releases.

### Additional information
This appears to be due to the use of internal singletons within Bugsnag. There may be other related bugs due to internal singletons such as `BSG_KSCrash`.

Related issue on Bugsnag Android: https://github.com/bugsnag/bugsnag-android/issues/285

Sample project demonstrating this bug:
[BugsnagExample.zip](https://github.com/bugsnag/bugsnag-cocoa/files/1968514/BugsnagExample.zip)

**Comment by fractalwrench** [comment]
Thanks @gizmosachin for the very detailed report and sample project - I can confirm that this appears to be an issue for any application which has two Bugsnag integrations.

I'll investigate whether there are any more singletons that might get in the way of this use-case (for instance, `BugsnagNotifier` appears to have at least one). I'll also check whether there are any hidden behaviours (e.g. ensuring reports are saved to separate locations for each Bugsnag integration). We'll get back to you as soon as we have a course of action.

**Comment by gizmosachin** [comment]
Thanks @fractalwrench!

**Comment by snmaynard** [comment]
We've had a think about this internally and we don't think that supporting multiple Bugsnag clients is a good idea. The SDK is relatively large and also hooks into global handlers. Having a non crash detector hook into these global handlers will surprise many developers and so it doesn't feel like a common use case. Happy to talk this through if you like.

**Comment by ghazel** [comment]
This was previously recommended by the Bugsnag support team. As others have discovered, it fails in several ways.

To work around it, I had to fork the Bugsnag (and bugshag-ndk) projects. Not ideal at all, but it does work.

**Comment by snmaynard** [comment]
As far as I'm aware the only use case for multiple clients is trying to monitor a library/sdk and not interfere with the application that may also be using Bugsnag. Is there another use case I haven't considered?

**Comment by madole** [comment]
Micro front-end architectures where separate apps are docked into a single bigger application need their own bugsnag instances to the respective teams can work independently. This is a big issue for us as it previously worked before the recent updates to the API.

**Comment by akinnee** [comment]
We use a microfrontend architecture. Navigating between different tools owned by different teams in our product does not trigger a full page reload. We are running into issues where errors are showing up in the wrong bugsnag project if bugsnag was initialized in one tool, then the user navigated to another tool, then an uncaught exception occurred. Having separate bugsnag instances is totally valid, and should be supported.

**Comment by selvaweavr** [comment]
> This was previously recommended by the Bugsnag support team. As others have discovered, it fails in several ways.
> 
> To work around it, I had to fork the Bugsnag (and bugsnag-ndk) projects. Not ideal at all, but it does work.

Hi, 
I am having the same issue with our SDKs too. I would like to know how did you managed to solve the problem please ?
