### ISSUE TITLE
Inaccurate free memory report

### ISSUE THREAD

**Issue by EmDee** [bugsnag/bugsnag-cocoa#288]
### Expected behavior
More accurate memory reports.

### Observed behavior
Inaccurate memory reports compared to Xcode's memory report. Most of the crashes/exceptions that are reported by Bugsnag show free memory of less than 200MB for all iPhone models.

### Steps to reproduce
- Check free memory report in Xcode
- Send handled exception
- Check free memory report on Bugsnag in the `Device` tab

### Versions
v5.15.6

### Additional information
This is not per se a bug report, maybe more a question on how Bugsnag is acquiring that information.

This is mainly interesting for us, because we see a lot of crashes and exception with very strange stack traces that don't make any sense, where each event reports rather low free memory (e.g. ~100MB for iPhone X). So we are trying to figure out if those exceptions happen due to low memory.

I know it's rather hard to get an accurate memory usage from iOS, so am I assuming correctly that these reports by Bugsnag are just a very rough estimate?

**Comment by fractalwrench** [comment]
Sorry for the late reply @EmDee - Bugsnag uses the KSCrash library internally, which handles calculation of the amount of free memory.

Memory information is collected within [this function](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/KSCrash/Source/KSCrash/Recording/Tools/BSG_KSMach.c#L58),  in KSCrash. This ultimately calls through to [this method](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/KSCrash/Source/KSCrash/Recording/Tools/BSG_KSMach.c#L489), which obtains statistics on the current host via a [`vm_statistics`](http://web.mit.edu/darwin/src/modules/xnu/osfmk/man/vm_statistics.html) struct. Ultimately we use `free_count` within this to populate the `freeMemory` field on the Bugsnag dashboard.

Hopefully this clears things up - if you think this behaviour should change please let us know, and I'll reopen the ticket.

**Comment by efratyo** [comment]
@EmDee Hi, we are experiencing the same inaccuracy between Bugsnag's and Xcode's memory reports.
Did you find a 'source of truth'?
Is the Xcode report indeed inaccurate?

**Comment by EmDee** [comment]
@efratyo I haven't looked into this issue much further. We just basically ignore the memory report altogether and rely more on Apple's `applicationDidReceiveMemoryWarning(_:)` callback and track those calls instead of caring too much about the "actual" free memory.

**Comment by efratyo** [comment]
@EmDee Ok, thanks for answering :)
