### ISSUE TITLE
please add Prefix (like "bc" for bugsnag-cocoa) to method names to avoid "multiple methods name error(s)"errors 

### ISSUE THREAD

**Issue by MirkoBrunner** [bugsnag/bugsnag-cocoa#29]
So in our big project we have a method called "mergeWith:" and we can´t rename our method name(s) quickly. And i see bugsang is very small ;) . SDWebImage adds, for example, the prefix "sd".

**Comment by snmaynard** [comment]
I agree with @Mazyod that it doesn't seem directly related to the library - but either way we have re-written the library to use KSCrash now so its likely that will help.
