### ISSUE TITLE
Include more specific OS version

### ISSUE THREAD

**Issue by sberrevoets** [bugsnag/bugsnag-cocoa#293]
In looking at our crash logs, the iOS versions listed look something like this:

<img width="60" alt="image" src="https://user-images.githubusercontent.com/3839052/42470053-3bbf24d2-836e-11e8-96bb-6bb83c11cabb.png">

Most of the time this level of detail is sufficient, but notice the iOS 12 version in there. It would be useful to also have the exact build number in there during the beta period to see if people are experiencing crashes because of iOS or because we're doing something wrong.

There's not a great API in iOS that gets this, but `[NSProcessInfo.processInfo operatingSystemVersionString]` gives this information back. The docs mention this property shouldn't be used for parsing, so 2 options are then to either:

1) Send the string that's being returned entirely, although given that it shouldn't be parsed this might also mean the format of the string could change which would make it harder to filter in the web UI
2) Use a lower-level call to get this info, using something like https://stackoverflow.com/a/5462277/751268

Either way, it seems that https://github.com/bugsnag/bugsnag-cocoa/blob/22751d43ef07294d56f34becf7b70566d175dbfc/Source/KSCrash/Source/KSCrash/Recording/BSG_KSSystemInfo.m#L366-L371 would be the right place to make this modification.

If this is something you're open to adding, please let me know and I can submit a PR with either approach.

**Comment by sberrevoets** [comment]
Are you saying current version strings are already including that build number? Because we're not seeing that in our console, although IIRC it used to be there for a little while not too long ago 🤔

If you're saying we can add a new `osBuildNumber` field with that string, that works for me as well!

**Comment by kattrali** [comment]
> Are you saying current version strings are already including that build number?

Oh no, I'm saying that's the format I currently get for `-[NSProcessInfo operatingSystemVersionString]`, which would be hard to filter by since the Bugsnag dashboard supports fuzzy matching on semantic version numbers (e.g. `1.*` or `2.4.*`). Adding a new field with the full build number makes sense though! (And maybe a radar that `-[UIDevice systemVersion]` in betas should be more specific by default)

**Comment by sberrevoets** [comment]
Yes exactly, and the docs mention that really that string is unfit for parsing so probably not wise to use for filtering like that either.

Adding a new field makes sense, but then the question becomes whether we ignore Apple's advice and parse that string anyway or to use the approach listed in https://stackoverflow.com/a/5462277/751268. It's a bit nastier but maybe safer? 🤷‍♂️

**Comment by kattrali** [comment]
> or to use the approach listed in stackoverflow.com/a/5462277/751268.

Wow that is cool. Seems safe enough to me and better than parsing the field.

**Comment by sberrevoets** [comment]
Turns out KSCrash was already reporting this and it was just a matter of including it in the Bugsnag reports. PR for this change here: https://github.com/bugsnag/bugsnag-cocoa/pull/298
