### ISSUE TITLE
Logging Configuration

### ISSUE THREAD

**Issue by fredpi** [bugsnag/bugsnag-cocoa#300]
### Expected behavior
I want to be able to use Bugsnag in my app without it logging anything while debugging. If this is possible currently, how can it be done? If it isn't, it'd be nice to have such a feature. ;)

### Observed behavior
Currently I get logs like this every time I run the app from Xcode:

```
WARN : BSG_KSCrashSentry.c (107): BSG_KSCrashType bsg_kscrashsentry_installWithContext(BSG_KSCrash_SentryContext *, BSG_KSCrashType, void (*)(void)): KSCrash: App is running in a debugger. Only user reported events will be handled.
INFO : BSG_KSCrash.m (325): -[BSG_KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
INFO : BSG_KSCrash.m (325): -[BSG_KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
```

### Version
5.16.2

**Comment by fractalwrench** [comment]
Thanks for the report @fredpi - I don't believe there's an easy way to achieve this in current versions of the SDK. Internally the log level is controlled by preprocessor macros [here](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/BugsnagLogger.h#L12) and [here](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/KSCrash/Source/KSCrash/Recording/Tools/BSG_KSLogger.h#L44), so you may be able to override these in your build settings.

I've created an internal ticket for bugsnag-cocoa to expose a nicer API for disabling logging. I'm envisioning that the API would look something similar to this: `[Bugsnag configuration].loggingEnabled = NO;`

**Comment by fredpi** [comment]
@fractalwrench Any progress on this? ;)

**Comment by kattrali** [comment]
You can actually do this already using a post-install hook in your Podfile (or by defining the macros directly in either Build Settings or an xcconfig file):

```ruby

post_install do |rep|
  rep.pods_project.targets.each do |target|
    if target.name == "Bugsnag"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'BSG_KSLogger_Level=0', 'BSG_LOG_LEVEL=0']
      end
    end
  end
end
```

**Comment by fredpi** [comment]
@kattrali Thanks for answering!

I see the this is possible when using `CocoaPods`. However, if you're using another package manager, like `Carthage`, you may be unable to do such target-based build configuration manipulation directly via the specifying file (e. g. a `Cartfile`). In those cases, having a runtime option to adjust logging is probably the only reasonable way to go.

**Comment by kattrali** [comment]
In those cases it’s even easier, as you can add the two preprocessor macros directly using build settings or in xcconfig files.

**Comment by fredpi** [comment]
MaybeI'm not getting it or there is some misunderstanding, but how should I be able to change build settings of a Carthage project without creating a fork (too much trouble) or manipulating after download (bad practice for a PM)?

**Comment by kattrali** [comment]
No worries, you can specify an xcconfig file via environment variable before running `carthage build`, and use that to change build options for any of your dependencies. To use the same example as above, create `carthage.xcconfig` with the following contents:

```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) BSG_KSLogger_Level=0 BSG_LOG_LEVEL=0
GCC_WARN_UNUSED_VARIABLE=0
```

(the latter option is needed since bugsnag-cocoa is built with `-Werror -Wunused-variable` and removing logs will create "unused" variables)

Then specify the file in your env before building the dependencies:

```
XCODE_XCCONFIG_FILE=$PWD/carthage.xcconfig carthage build
```

or use a wrapper file (also useful if you have other carthage build customizations, like [static framework optimizations](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md)):

```bash
#!/usr/bin/env bash

XCODE_XCCONFIG_FILE=$PWD/carthage.xcconfig carthage "$@"
```

which can then be run normally, like:

```
./carthage.sh build
```

**Comment by fredpi** [comment]
Thanks for the detailed answer, I'll definitely give it a try!
