### ISSUE TITLE
Stop and resume BugSnag session

### ISSUE THREAD

**Issue by fredpi** [bugsnag/bugsnag-cocoa#304]
Due to privacy requirements, I have to be able to stop and possibly resume a BugSnag session (where stopping means to stop both data collection and server connection).

As I didn't find any straightforward interface to do so, I'm wondering whether there is any suggested way to do it...? Maybe by setting empty endpoint urls or removing the api key from the configuration?

If there would be no way to do it as of today, I'd suggest to add such a feature, as the ability do so gains more and more importance with more restrictive privacy laws requesting software developers to provide their users total control over what background services are running.

**Comment by snmaynard** [comment]
There is no persistent connection between the app and the server for bugsnag. Depending on what you want to achieve you can disable session tracking by setting `shouldAutoCaptureSessions` to `false` (https://docs.bugsnag.com/platforms/ios/configuration-options/#shouldautocapturesessions).

You can disable error reporting entirely by following the guide in https://docs.bugsnag.com/platforms/ios/#disabling-error-reporting. You can return true in there to send that crash report instead. Disabling both of these will prevent all network traffic to bugsnag.

Let us know if that doesnt solve your use case or if you want something else specific and we can reopen the issue.

**Comment by fredpi** [comment]
@snmaynard Thanks for the fast reply.

Just one further question: In the documentation about before send blocks, it says

> NOTE: Segmentation faults and other similar crashes cannot be caught within handlers.

Does this mean they won't be sent at all or does it mean we cannot configure them not to be sent?

**Comment by snmaynard** [comment]
It means that if the code you write in the handler seg faults (or generates another type of fatal signal) then theres nothing we can do to stop the app terminating immediately, and your crash report will not be sent.
