### ISSUE TITLE
Ability to override app build number as well as version

### ISSUE THREAD

**Issue by Aquilosion** [bugsnag/bugsnag-cocoa#339]
We have a single project which many apps are built against (kind of like having multiple targets in Xcode, but a more custom solution). The various apps we build all have their own version/build numbers for the App Store but are built against this single project which has its own "codebase version", which is included automatically as a custom property in the Info.plist.

If there's a bug, it will typically affect all or most apps under the codebase, so it's more useful for us to have a single project on Bugsnag representing the entire codebase, rather than many, potentially hundreds of apps listed all showing the same errors.

`BugsnagConfiguration.appVersion` was useful because we can override the app's version in the Info.plist with the codebase version:

```
config.appVersion = getCodebaseVersionFromInfoPlist()
```

…and write the app's actual version as metadata attributes.

Unfortunately because all the apps have different build numbers, we still get multiple releases listed in Bugsnag, all with the codebase version but with different build numbers. We thought we might be able to override the report as so:

```
config.add(beforeSend: { (dictionary, report) -> Bool in
	report.appState?["bundleVersion"] = report.appState?["version"]
	
	return true
})
```

Which sort of works as now all bugs come under a single release, but general session tracking seems to bypass the `beforeSend` override, so I get additional releases listed anyway.

It would be useful for us to have some kind of additional `appBundleVersion` parameter on the configuration which is respected by errors and session tracking alike so that we can fully customise what releases actually appear on the Bugsnag dashboard.

By the way if what we're trying to do doesn't sound like a good idea, we'd love to hear alternate solutions!

**Comment by kattrali** [comment]
Thanks for the report, @Aquilosion.

> Which sort of works as now all bugs come under a single release, but general session tracking seems to bypass the beforeSend override, so I get additional releases listed anyway.

You're right that callbacks don't run on session payloads, however, [they do use the configured app version](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/BugsnagSessionTrackingPayload.m#L43). So you should be able to use a combination of `beforeSend` and overriding `config.appVersion` to get the effect that you're looking for. In the longer term, a callback for modifying session data would make this simpler, though would still be two callbacks (one for sessions and one for errors).
