### ISSUE TITLE
Add +[Bugsnag appDidCrashLastLaunch] to Documentation

### ISSUE THREAD

**Issue by mdcarter1** [bugsnag/bugsnag-cocoa#347]
### Description
From the 5.20.1 release notes there was a new item added to the SDK:
_Add +[Bugsnag appDidCrashLastLaunch] as a helper to determine if the previous launch of the app ended in a crash or otherwise unexpected termination._

### Issue
We only found it via perusing the source, but should update the BugSnag documentation to include this new API as we found it very useful.  Probably not Cocoa specific but not sure where else to log this.  Happy to make a PR if pointed in the right direction where.

**Comment by kattrali** [comment]
Hey @mdcarter1 - sorry about that! I've added the header doc to the integration guide sidebar. [You can see it here.](https://bugsnag.github.io/bugsnag-cocoa/Bugsnag_h/)
