### ISSUE TITLE
Fix test for serialized severity

### ISSUE THREAD

**Issue by paulz** [bugsnag/bugsnag-cocoa#358]
### Description

`testHandledReportSeverity` seems to have incorrect assertion

https://github.com/bugsnag/bugsnag-cocoa/blob/ceb02dacd86c6b63ecac1545df0fbb6dbd592871/Tests/BugsnagCrashReportTests.m#L524

It sets severity to Info but verifies it to be Warning:

```
- (void)testHandledReportSeverity {
    // handled reports should use the serialised depth
    BugsnagHandledState *state = [BugsnagHandledState handledStateWithSeverityReason:HandledException];
    NSDictionary *dict = @{@"user.state.crash.severity": @"info", @"user.handledState": [state toJson]};
    BugsnagCrashReport *report = [[BugsnagCrashReport alloc] initWithKSReport:dict];
    XCTAssertEqual(report.severity, BSGSeverityWarning);
}
```

also comment states:
`// handled reports should use the serialised depth`

may be it should be 
`// handled reports should use the serialised severity`?

**Describe the solution you'd like**
Either update the test or fix failing test. 

@fractalwrench any help/suggestions appreciated

**Comment by steve-nester-uk** [comment]
PLAT-3564

**Comment by johnkiely1** [comment]
Hi @paulz 

This test has been updated in the [v6.2.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.0) release.
