### ISSUE TITLE
Use of weak hash algorithm - SHA1

### ISSUE THREAD

**Issue by martianplatypus** [bugsnag/bugsnag-cocoa#398]
The `CC_SHA1` function is used in the body of  `+ (NSString *)deviceAndAppHash` in `BSG_KSSystemInfo.m`:
```    // SHA the whole thing.
    uint8_t sha[CC_SHA1_DIGEST_LENGTH];
    CC_SHA1([data bytes], (CC_LONG)[data length], sha);
``` 

SHA1 is considerate a cryptographically weak hash algorithm and vulnerable to collision attacks. See:  [iOS 13 CryptoKit documentation](https://developer.apple.com/documentation/cryptokit/insecure/sha1)

As described in the documentation above, prefer to use a stronger hash algorithm, like SHA512. In addition, even though your code is note used in a security context, clients of your SDK can be flagged in penetration tests because this issue violates OWASP Mobile Security policies/standards. See [M5 - Insufficient Cryptography](https://www.owasp.org/index.php/Mobile_Top_10_2016-M5-Insufficient_Cryptography) for more details.

**Comment by abigail-bugsnag** [comment]
@martianplatypus thanks for your comment. As this is not being used in a security context, this is not something we plan to pursue.

**Comment by martianplatypus** [comment]
Thanks @abigail-bugsnag
