### ISSUE TITLE
[Feature] Return last crash information in `appDidCrashLastLaunch`

### ISSUE THREAD

**Issue by rob-keepsafe** [bugsnag/bugsnag-cocoa#408]
### Description

Currently, `appDidCrashLastLaunch` just returns a `BOOL` to let us vaguely know if something happened last launch. 

However, we'd like to better understand how certain crashes cause data corruption issues and therefore need to know what the last crash was before the data was corrupted. Crashlytics offered this via `crashlyticsDidDetectReport(forLastExecution report: CLSReport)` but we are unable to find an equivalent in Bugsnag.

This allows us to focus our crash fixing efforts on those crashes which specifically cause data corruption (especially total database corruption).

Thanks for your consideration 🙌

**Comment by abigail-bugsnag** [comment]
@rob-keepsafe thanks for your comment. We will take a look at this.

**Comment by rob-keepsafe** [comment]
Thanks @abigail-bugsnag ! Even if we could do this on the website itself by creating a funnel, that would solve this as well. E.g. show me all crashes that a given user had before this current crash

Data corruption crashes are notoriously difficult to fix for this reason and you all have a lot of opportunity to help fix these types of issues event faster

**Comment by snmaynard** [comment]
Could you use https://docs.bugsnag.com/platforms/ios/configuration-options/#beforesendblocks beforeSendBlocks coupled with `appDidCrashLastLaunch` to check? The last unhandled exception on the next boot where `appDidCrashLastLaunch` is true should be the last crash? Not an ideal interface - but I think it is possible without any changes on the library side right now.

**Comment by rob-keepsafe** [comment]
Thanks @snmaynard, that might do the trick! Feel free to close this if you'd rather leave the API as-is for now

**Comment by mattdyoung** [comment]
Thanks @rob-keepsafe 

We'll close for now, although we may end up considering something similar on our future roadmap if we can see wider benefit.
