### ISSUE TITLE
Use KSCrash dependency in CocoaPods instead of self-hosting

### ISSUE THREAD

**Issue by orta** [bugsnag/bugsnag-cocoa#41]
![screen shot 2015-03-17 at 3 33 23 pm](https://cloud.githubusercontent.com/assets/49038/6695887/3545f72e-ccbb-11e4-93a5-963d03ca53db.png)

[KSCrash](http://cocoapods.org/pods/KSCrash) is it's own independent CocoaPod, people are less likely to get class collisions in their apps. If they are including both ( I am in the tests for [ARAnalytics](http://cocoapods.org/pods/ARAnalytics) )

**Comment by ConradIrwin** [comment]
Hi @orta,

For now we have a few unmerged changes to KSCrash. We'll kick off a project to get them merged upstream (it requires a bit of cleanup), so this should be fixed eventually.

(That said, Bugsnag will work without those changes, it will just block the UI thread more than we'd like).

Conrad

**Comment by orta** [comment]
:+1: good luck :)

**Comment by gsamat** [comment]
We are getting class collision with https://appmetrika.yandex.ru/ , which is quite popular in Russia.

Could you please estimate when would you be able to ship fix for that dependency?

That is important for us as we will consider forking your library in case it will take another few months for you to fix.

**Comment by jessicard** [comment]
@gsamat Unfortunately we are still a bit away before we can start this project. I'd recommend forking the notifier for now.

**Comment by crossle** [comment]
The following build commands failed:
	CompileC Bugsnag/KSCrash/Source/KSCrash/Recording/KSCrashReport.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler  (1 failure)

KSCrash compile failed, use commond compile

**Comment by joshdholtz** [comment]
I agree with @orta on this :+1: Are we any closer to getting that added in?
