### ISSUE TITLE
No such module 'Bugsnag'

### ISSUE THREAD

**Issue by ldiqual** [bugsnag/bugsnag-cocoa#428]
### Description

Using Xcode 11.1, cocoapods 1.8.1, and Bugsnag 5.22.9, importing the module fails with the following error:

```
No such module 'Bugsnag'
```

Test project: [BugsnagTest.zip](https://github.com/bugsnag/bugsnag-cocoa/files/3759327/BugsnagTest.zip)

### Environment

Library versions:

* Bugsnag version (from your Podfile, Podfile.lock, or elsewhere): 5.22.9
* CocoaPods version (if any) (`pod -v`): 1.8.1
* iOS/tvOS/macOS version(s): 13
* debug mode or production?: Debug
* How are you initializing Bugsnag?: AppDelegate
* Xcode version: 11.1 (11A1027)

### Example code snippet

```swift
import Bugsnag
```

<details><summary>Error messages:</summary>

```
No such module 'Bugsnag'
```
</details>

**Comment by mattdyoung** [comment]
Hi @ldiqual 

You need to add `use_frameworks!` to your `Podfile`.

Then after a further `pod install` your project should build.

Thanks!

**Comment by KalpeshTalkar** [comment]
I am using this inside a framework and I have installed Bugsnag dependency via SPM. I am getting this error inside my xcframework when I am trying to build the demo app.

**Comment by yousif-bugsnag** [comment]
Hi @KalpeshTalkar, this sounds like it could be a different issue. Please could you write in to support@bugsnag.com with the full details of the problems you're seeing?
