### ISSUE TITLE
Support for breadcrumbs

### ISSUE THREAD

**Issue by vocaro** [bugsnag/bugsnag-cocoa#43]
Bugsnag has a cool breadcrumb feature to help determine the sequence of events leading up to the crash:

https://bugsnag.com/blog/introducing-mobile-breadcrumbs

Breadcrumbs have been available on Android since December, but they are absent from iOS. It would be great if iOS developers could also start logging breadcrumbs.

**Comment by jessicard** [comment]
Hey @vocaro - thanks for opening this! It would be awesome to add this to the notifier. We do have plans to add it eventually, but currently we have no ETA. In the meantime, of course, we're open to PRs.

**Comment by BananaNeil** [comment]
+1

**Comment by tinman821** [comment]
+1

**Comment by joeblau** [comment]
:+1:

**Comment by trobrock** [comment]
:+1:

**Comment by joshdholtz** [comment]
:+1:
