### ISSUE TITLE
not compiling for iOS objective C

### ISSUE THREAD

**Issue by mako34** [bugsnag/bugsnag-cocoa#431]
Hi, my project uses reactnative, bugsnag is working on RN, but I need to monitor on iOS native level as well.

Not compiling with errors:

No known class method for selector 'currentAppState'

Illegal type 'id' used in a boxed expression

No known class method for selector 'isInForeground:'

<img width="1132" alt="Screen Shot 2019-11-04 at 12 40 18 pm" src="https://user-images.githubusercontent.com/207499/68095820-b1d32b00-ff00-11e9-934a-8c551e6785cc.png">

please, advise, thanks

**Comment by mattdyoung** [comment]
Hi @mako34 

I saw you contacted support@bugsnag.com on this as well so we've followed up with you there as this looks likely to be a configuration issue rather than a bug with the library.
