### ISSUE TITLE
Pruning of crash reports is not very smart, it can prune Errors

### ISSUE THREAD

**Issue by combinatorial** [bugsnag/bugsnag-cocoa#437]
### Description
`[self.crashReportStore pruneFilesLeaving:self.maxStoredReports];` can prune Error reports (e.g. crashes) if there are many Warnings added on startup. It would be better to prune Warnings first. 

### Issue
Crashes are not delivered to the server if there are too many warnings logged during startup.

### Environment
Xcode 11.2.1, iOS 13.2.3

Library versions:

* Bugsnag version: Bugsnag (5.22.10)
* CocoaPods version: 1.8.4
* Carthage version (if any): n/a
* iOS/tvOS/macOS version(s): iOS 13.2.3
* debug mode or production?: production build but not an App Store submission
* How are you initializing Bugsnag? Can you share a snippet of your
  `AppDelegate` where Bugsnag is configured?

### Example code snippet

An `addBeforeSend` block with logging confirmed the crash did not get submitted:

```
[Bugsnag.configuration addBeforeSendBlock:^bool(NSDictionary * _Nonnull rawEventData, BugsnagCrashReport * _Nonnull reports) {
            NSLog(@"bs sev: %lu", reports.severity);
}];
```

Only warnings got submitted (the ones logged during startup) and the crash was not submitted.

**Comment by mattdyoung** [comment]
Hi @combinatorial 

Thanks, we're looking into options to improve the behaviour here in some planned changes we have coming up.

**Comment by steve-nester-uk** [comment]
PLAT-3771

**Comment by nickdowell** [comment]
In release [v6.8.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.8.0) the error / event delivery mechanism was significantly overhauled, and as a result the pruning of crashes described here should no longer be an issue.

If there are many calls to `notify()` during start-up that cause the `maxPersistedEvents` limit to be reached, it is the most recent (i.e. non-crashing) events that are [now discarded](https://github.com/bugsnag/bugsnag-cocoa/blob/849f7072c1a96852bdd7317115191b31c7627049/Bugsnag/Delivery/BSGEventUploader.m#L71-L79).

@combinatorial @sethfri hope that helps!
