### ISSUE TITLE
Typo in Bugsnag API documentation

### ISSUE THREAD

**Issue by vocaro** [bugsnag/bugsnag-cocoa#45]
The [addAttribute](https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/Bugsnag/Bugsnag.h#L108) documentation has a typo.

    @param value          It's value.

should be:

    @param value          Its value.

**Comment by benwoodward** [comment]
lol

**Comment by kattrali** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Q60HtFgo&#x2F;23-cocoa-platform-improvement"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Cocoa Platform Improvement</a>
