### ISSUE TITLE
Use iOS 13 'os_proc_available_memory' for free memory reporting when available

### ISSUE THREAD

**Issue by combinatorial** [bugsnag/bugsnag-cocoa#452]
### Description
The current API used for obtaining free memory is know to be inaccurate. iOS 13 includes a very accurate way of getting the free memory available to an app. [`os_proc_available_memory`](https://developer.apple.com/documentation/os/3191911-os_proc_available_memory?language=objc). 

**Describe the solution you'd like**
In `bsg_ksmachfreeMemory`, use `os_proc_available_memory` in place of `vmStats.free_count` on iOS 13.

**Comment by mattdyoung** [comment]
Hi @combinatorial 

Thanks for the suggestion. Looks like a better approach, we'll look into this.

**Comment by steve-nester-uk** [comment]
ROAD-971

**Comment by nickdowell** [comment]
A fix for this has been released in [v6.2.1](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.3)

See #851 for more details
