### ISSUE TITLE
cocoapod install fails on KSCrashModule

### ISSUE THREAD

**Issue by xinsight** [bugsnag/bugsnag-cocoa#46]
I'm currently unable to install Bugsnag via cocoapods, due to a problem with the private submodule  `KSCrashModule`.

```
pod install
Analyzing dependencies

CocoaPods 0.37.2 is available.
To update use: `sudo gem install cocoapods`

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Installing Bugsnag (4.0.6)

[!] Error installing Bugsnag
[!] /usr/bin/git submodule update --init

Submodule 'KSCrashModule' (git@github.com:bugsnag/KSCrash.git) registered for path 'KSCrashModule'
Cloning into 'KSCrashModule'...

fatal: reference is not a tree: 76836a36603fee7475731c8826b62dc1a6c47441

Unable to checkout '76836a36603fee7475731c8826b62dc1a6c47441' in submodule path 'KSCrashModule'
```

Steps to reproduce:

- Remove Bugsnag from the `Podfile`
- `pod install`
- Re-add Bugsnag to the `Podfile`
- `pod install`

**Comment by xinsight** [comment]
If anyone else runs into this issue, an easy workaround is to fork the repo and then update your `Podfile` to point to your fork. e.g.

`pod 'Bugsnag', :git => "git@github.com:xinsight/bugsnag-cocoa.git"`

**Comment by ConradIrwin** [comment]
Hi @xinsight, I think this was caused by me forgetting to push the latest version to Cocoapods.

It should work now if you use our repository:

    pod 'Bugsnag', :git => "https://github.com/bugsnag/bugsnag-cocoa.git"

Can you confirm?

**Comment by xinsight** [comment]
Sorry, for the delay in responding. Yes, the default git location now installs without the `KSCrashModule` error. Thanks!
