### ISSUE TITLE
Add Notifier Access To GroupingHash

### ISSUE THREAD

**Issue by joeblau** [bugsnag/bugsnag-cocoa#47]
There doesn't seem to be a way to set the groupingHash on iOS.

**Comment by jessicard** [comment]
Thanks for creating an issue about this @joeblau! We would definitely like to add this to the notifier. We do have plans to add it eventually, but currently we have no ETA. In the meantime, of course, we're open to PRs.

**Comment by joeblau** [comment]
@jessicard Yep, I'm going to fix this and the breadcrumbs over this weekend.  Just had to get approval to do it.
