### ISSUE TITLE
Products contains invalid products

### ISSUE THREAD

**Issue by typcn** [bugsnag/bugsnag-cocoa#48]
binaries share the same codesign path:

/Contents/Frameworks/BugsnagOSX.framework/Versions/Current

Binaries:
/Contents/Frameworks/BugsnagOSX.framework/BugsnagOSX
/Contents/Frameworks/BugsnagOSX.framework/Versions/Current/BugsnagOSX

This can happen if your build process copies frameworks by following symlinks

Frameworks should use symlink , but bugsnag.framework downloaded from release has multiple files .

**Comment by jessicard** [comment]
@typcn Thanks for bringing this up. I fixed it here: https://github.com/bugsnag/bugsnag-cocoa/commit/94779161ebb4122c1753946c45e8c5b8350f72b0 and it should come out with our next release!
