### ISSUE TITLE
Is there a way to access the default userId?

### ISSUE THREAD

**Issue by peterdk** [bugsnag/bugsnag-cocoa#490]
### Description
I want to display the userId from Bugsnag in emails that user send to get support. I do see a currentUser property in BugsnagConfiguration, but I can't access it from Bugsnag.configuration().currentUser. Because we prefer to keep the userId across account logins, we do not want to set the user to our current user's id.

**Describe the solution you'd like**
Make Bugsnag.configuration().currentUser accessible.

**Describe alternatives you've considered**
Setting own userId, but we want to keep cross user account error logs.

**Additional context**
I checked with 5.22.10.

**Comment by phillipsam** [comment]
Hi @peterdk 

We're currently working on the next major release of bugsnag-cocoa which will include an interface to retrieve the Bugsnag generated user ID from the client object.

**Comment by steve-nester-uk** [comment]
Fixed in [6.1.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.1.0)
