### ISSUE TITLE
Spurious warning: Cache is deprecrated

### ISSUE THREAD

**Issue by xinsight** [bugsnag/bugsnag-cocoa#50]
Using Xcode 6.3.2, compiling Bugsnag (4.0.7) shows the following warning:

```
In file included from /Users/.../Pods/Bugsnag/KSCrash/Source/KSCrash/Recording/Tools/KSObjC.c:29:
/Users/.../Pods/Bugsnag/KSCrash/Source/KSCrash/Recording/Tools/KSObjCApple.h:122:5: warning: 'Cache' is deprecated: first deprecated in iOS 2.0 [-Wdeprecated-declarations]
    Cache cache;
    ^
/Users/.../Pods/Bugsnag/KSCrash/Source/KSCrash/Recording/Tools/KSObjCApple.h:51:28: note: 'Cache' has been explicitly marked deprecated here
typedef struct objc_cache *Cache;
                           ^
1 warning generated.
```

This doesn't seem to be a problem. An easy fix would be to add the a #pragma to disable the warning.

**Comment by Blackjacx** [comment]
I can confirm this issue. Can you please fuix this with a 4.0.8?

**Comment by OliverMahn-flinc** [comment]
For me too, please fix.

**Comment by joshdholtz** [comment]
:+1:

**Comment by shnhrrsn** [comment]
+1

**Comment by thisisjeffwong** [comment]
Also, seeing this. Isn't it somewhat dangerous to be using a type that was deprecated in iOS 2.0?

**Comment by alexmedearis** [comment]
@thisisjeffwong As far as I can tell, KSObjCApple.h is just KSCrash's mirror of the objc runtime.h.  Looking at the most recent runtime.h, Cache is still in there, so even though its deprecated, I think it's OK to just ignore it for now.
