### ISSUE TITLE
OOM crashes aren't accurate for watchdog kills

### ISSUE THREAD

**Issue by iwasrobbed-ks** [bugsnag/bugsnag-cocoa#539]
### Description

Bugsnag is pretty heavy handed when it comes to considering a crash an `out-of-memory` crash versus trying to classify it with other heuristics to see if it was more accurately a deadlock / watchdog kill.

### Issue

- We're receiving a lot of crashes classified as `OOM` by Bugsnag, making us think there's a memory leak / issue
- When we inspect crash logs from a device, these crashes are actually watchdog kills
- Bugsnag should do a better job at trying to classify crashes as actually being OOM or not

### Example Heuristics & Approaches

- Boot time (see https://github.com/bugsnag/bugsnag-cocoa/issues/545)
- Time since last low-memory warning 
- Rate of change of free memory
- App version change across launches
- OS version change across launches
- Thread counts / utilization to determine starvation
- Class / object allocation counts in memory
- Check if `exit()` was called (people do this even though Apple advises against it)
- Implement a thread checkpoint API where threads can report into Bugsnag in a way similar to a dispatch group so Bugsnag knows which threads were working
- Create a watchdog timer that pings a given thread/queue every so often to check if it's available for work

### Supporting Information

- From what I can tell, Bugsnag doesn't really perform any sort of heuristics around OOM (but I've only looked at this one file): https://github.com/bugsnag/bugsnag-cocoa/blob/master/Source/BSGOutOfMemoryWatchdog.m
- Other crash reports have implemented at least some conditional logic to better classify these errors:
  - Crashlytics: https://docs.fabric.io/apple/crashlytics/OOMs.html
  - Facebook: https://engineering.fb.com/ios/reducing-fooms-in-the-facebook-ios-app/
  - PLCrashReporter / HockeyApp: https://github.com/microsoft/appcenter/issues/103
    - Documentation around what they can capture as far as mach exceptions (which won't work for watchdog / OOM): https://github.com/microsoft/appcenter-sdk-apple/blob/a312728bb7d7e15e9f2f38f08608c3be44118550/Vendor/iOS/PLCrashReporter/include/CrashReporter.h#L241

### Environment

Library versions:

* Bugsnag version (from your Podfile, Podfile.lock, or elsewhere): 5.22.7
* CocoaPods version (if any) (`pod -v`): 1.8.4
* iOS/tvOS/macOS version(s): All
* debug mode or production?: Both
* How are you initializing Bugsnag? Irrelevant for this issue

**Comment by robinmacharg** [comment]
Thanks for your report @rob-keepsafe .  We actually have an upcoming piece of work that will look into improving our OOM heuristics.  We'll feed your comments into that development and keep you updated.  This is likely to be sometime in the next quarter.

**Comment by rob-keepsafe** [comment]
FYI: Apple just announced that MetricKit in iOS 14+ will provide much more information on hangs, including stack traces. This would be a great addition

https://developer.apple.com/videos/play/wwdc2020/10081/

https://developer.apple.com/documentation/metrickit/mxhangdiagnostic

**Comment by sethfri** [comment]
Hi @robinmacharg, any update on the scheduling of this work?

**Comment by mattdyoung** [comment]
Hi @sethfri 

We don't have firm timeline for release yet, but we have scoped out some ideas of approaches we're planning to prototype to improve OOM detection.

**Comment by sethfri** [comment]
Thanks @mattdyoung. Would be super interested in the `MetricKit` approach @iwasrobbed-ks described above since that seems like it's likely to be the best heuristic.

**Comment by johnkiely1** [comment]
Hi, Just to let you know as of [v6.8.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.8.0) situations where the application is in an unresponsive state and is killed by the system watchdog, or force quit by the user, the resultant error will be reported to Bugsnag as an App Hang error instead of an Out of Memory error.
