### ISSUE TITLE
All rubymotion exceptions have the same error message

### ISSUE THREAD

**Issue by BananaNeil** [bugsnag/bugsnag-cocoa#54]
Rubymotion support is really close, there just seems to be something slightly wrong with the actual exception type message

Currently all exceptions are marked as `EXC_BAD_ACCESS`

and, all error messages say 

```
Attempted to dereference garbage pointer 0x15497beb8.
```

or

```
Attempted to dereference null pointer.
```

It would be great for this to include at very least the exception class, but if possible, the exception message.

**Comment by BananaNeil** [comment]
Looking at old code that I was using to send up information about crashes, the exception object passed to the exception handler will respond to `.class` which will give the type of exception (e.g. NoMethodError) and `.backtrace`, which will return the error message. (e.g. "undefined method `[]' for nil:NilClass")

This is the information I would like to see returned rather than `EXC_BAD_ACCESS` and `Attempted to dereference null pointer.`

**Comment by fractalwrench** [comment]
Sorry for the very late response on this, we believe this should now be fixed as a result of a change to our pipeline.
