### ISSUE TITLE
OOM reporting doesn't consider device reboots

### ISSUE THREAD

**Issue by jparise** [bugsnag/bugsnag-cocoa#545]
### Description
`computeDidOOMLastLaunchWithConfig:` uses a number of heuristics to determine whether or not the last launch terminated due to an OOM condition.

One input that's not considered is the device's boot time, which can be used to determine whether or not the device was rebooted. (Reboots don't send an explicit termination signal to apps so this case could be classified as an OOM.)

**Describe the solution you'd like**

Compare the current launch's boot time to the last launch's boot time.

```objc
time_t systemBootTime = 0;
struct timeval boottime;
size_t size = sizeof(boottime);
if (sysctlbyname("kern.boottime", &boottime, &size, NULL, 0) != -1) {
    systemBootTime = boottime.tv_sec;
}
```

**Comment by phillipsam** [comment]
Hi @jparise thanks for the report! Improvements to our OOM detection heuristic is on our roadmap and we hope to improve this in a future release. We will be working on this when priorities allow.

**Comment by johnkiely1** [comment]
Hi @jparise 

We have now made OOM detection improvements in [v6.2.5](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.5) which considers whether the device was rebooted or not. 

Thanks again for suggesting this.
