### ISSUE TITLE
Bugsnag OS X and iOS frameworks ZIP files are created wrong

### ISSUE THREAD

**Issue by tomandersen** [bugsnag/bugsnag-cocoa#55]
The framework ZIP archives that are downloadable for iOS and OS X do not have the sym links, instead they have copies of the files which makes my code signing fail, among other problems. 
![screen shot 2015-09-10 at 12 37 27 pm](https://cloud.githubusercontent.com/assets/221405/9794370/bdea137a-57b8-11e5-8d5d-05fd94d4f7dd.png)

All OS X and iOS frameworks have lots of symlinks, as per https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html

Also it seems that downloading the source and building the frameworks seems to make the frameworks correctly, so it looks like an issue where your ZIP step is following the symlinks instead of leaving them alone.

![screen shot 2015-09-10 at 12 40 12 pm](https://cloud.githubusercontent.com/assets/221405/9794448/1b4ea9ea-57b9-11e5-8f29-b2b64889e5f0.png)

**Comment by frk2** [comment]
I experience this as well. Rebuilding from source fixes the issue.

**Comment by tomandersen** [comment]
What I did was use the release ZIP files and the skeleton created by a build so I did not have to make all the symlinks.

**Comment by tomandersen** [comment]
This is still in the ZIP for 4.0.9 - no symlinks, everything is duplicated, it will not codesign as is.
