### ISSUE TITLE
Better differentiation of foreground and background OOM events

### ISSUE THREAD

**Issue by jparise** [bugsnag/bugsnag-cocoa#571]
### Description
Internally, Bugsnag differentiates between foreground and background OOMs, but that information is only represented in the final crash event as part of the formatted message string.

```objc
BOOL wasInForeground = [[lastLaunchInfo valueForKeyPath:@"app.inForeground"] boolValue];
NSString *message = [NSString stringWithFormat:BSGOutOfMemoryMessageFormat, wasInForeground ? @"foreground" : @"background"];
```

**Describe the solution you'd like**
It would be helpful to programmatically differentiate foreground and background events. They could be distinct exception names or additional crash metadata attach to the existing `BSGOutOfMemoryErrorClass` event (see also #570).

**Describe alternatives you've considered**
For the moment, we can look for "foreground" or "background" in the error message string, but that's not a long-term, reliable solution.

~We can also inspect the `appState` dictionary from the `BugsnagCrashReport` to determine the application's state at the time of termination.~ `appState` isn't set for OOM events.

**Comment by phillipsam** [comment]
Hi @jparise 
Background OOM detection is no longer available. This property was removed in [v5.22.9](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v5.22.9) as determining background OOMs was found to be unreliable and caused a number of false positives.

Any OOMs reported on newer versions of bugsnag-cocoa should only be foreground OOMs.
