### ISSUE TITLE
Documentation for Swift developers

### ISSUE THREAD

**Issue by davejlong** [bugsnag/bugsnag-cocoa#60]
I'm attempting to install Bugsnag in an application using Swift 2. I have installed the library through Cocoapods and adding the import to my bridging header:

    #ifndef GoDriver_Bridging_Header_h
    #define GoDriver_Bridging_Header_h
    
    #import "Bugsnag/Bugsnag.h"
    
    #endif /* GoDriver_Bridging_Header_h */

I then attempted to initialize Bugsnag in my AppDelegate:

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        Bugsnag.startBugsnagWithApiKey("...")
        
        return true
    }

But Xcode errors with `Use of unresolved identifier 'Bugsnag'` on the line in AppDelegate.

In my opinion, Bugsnag should have documentation for using the notifier with Swift as well as Objective-C applications.

**Comment by regnerjr** [comment]
On my project we are using Bugsnag through cocoapods with the `use_frameworks!` directive in our pod file. 

```
platform :ios, '9.0'
use_frameworks!

def pods
   pod 'Bugsnag', :git => "https://github.com/bugsnag/bugsnag-cocoa.git"
end

target 'AwesomeApp' do
   pods
end
```

No bridging header required. Just `import Bugsnag` in your AppDelegate
Then 
``` Swift
Bugsnag.startBugsnagWithApiKey(myAPIKey)
Bugsnag.configuration().releaseStage = "Local Development"
```

Hope this helps.
