### ISSUE TITLE
Ignored signal via SIG_IGN is reported to dashboard

### ISSUE THREAD

**Issue by yichengchen** [bugsnag/bugsnag-cocoa#604]
### Description
Signal error is still reported even I had use SIG_IGN to ignore the signal

### Issue
I am writing a `Mac` network proxy tool. And I had handle the SIGPIPE by `signal(SIGPIPE, SIG_IGN)`. But in the dashboard, I received a lot of SIGPIPE Error every where in my code.

### Environment

Library versions: 
* Bugsnag version (from your Podfile, Podfile.lock, or elsewhere): Bugsnag (5.23.2)
* CocoaPods version (if any) (`pod -v`):1.9.1
* Carthage version (if any):none
* iOS/tvOS/macOS version(s):  Mac OS 10.15
* debug mode or production?:production
* How are you initializing Bugsnag? Can you share a snippet of your
  `AppDelegate` where Bugsnag is configured?

```
signal(SIGPIPE, SIG_IGN)
Bugsnag.start(withApiKey: "MY KEY")
```
<img width="817" alt="image" src="https://user-images.githubusercontent.com/11733500/82148061-af289980-9884-11ea-9b72-302397ff09f3.png">

How can I ignore this error on bugsnag? During the usage, I did not see crash actually happened.

**Comment by mattdyoung** [comment]
Hi @yichengchen 

If all you want to do is ignore the error on Bugsnag you can do this by returning `false` from a `beforeSend` callback for these errors, to prevent sending them to Bugsnag:
https://docs.bugsnag.com/platforms/ios/configuration-options/#beforesendblocks

or use the 'Discard by error class' setting in the dashboard for an error class of `SIGPIPE` to discard these when they're received.

Are you confident these signals don't crash your app? If you have further questions on this I'd suggest writing in to support@bugsnag.com with details of which of your projects this is for so we can look at the errors you describe in more detail.
