### ISSUE TITLE
OSX OS version missing

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-cocoa#61]
Looking at KSCrash the os version field only works on iOS.

https://github.com/kstenerud/KSCrash/blob/1561f1c34e25440c03a20e27aab6ef81706a29f5/Source/KSCrash/Recording/KSSystemInfo.m#L310

**Comment by kattrali** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Q60HtFgo&#x2F;23-cocoa-platform-improvement"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Cocoa Platform Improvement</a>

**Comment by kattrali** [comment]
Fixed in KSCrash 1.4.6
