### ISSUE TITLE
Xcode 7 BugSnag 4.0.9

### ISSUE THREAD

**Issue by allenbriggs** [bugsnag/bugsnag-cocoa#62]
After upgrading to Xcode 7, I pulled the latest BugSnag library into my project.  Now, I'm running into many warnings from Xcode (please see attached screen).  Has anyone else ran into this issue?

![2015-10-09_09-30-59](https://cloud.githubusercontent.com/assets/8330731/10395072/02fa7cc2-6e69-11e5-8d5e-e61417331c76.png)

**Comment by andrewroycarter** [comment]
I'm having this as well- looks like it's happening with a good bit of frameworks released by other people too. The fix is easily google-able
