### ISSUE TITLE
5.23.2 includes deprecation without replacement

### ISSUE THREAD

**Issue by keith** [bugsnag/bugsnag-cocoa#657]
### Description

When updating to v5.23.2 we found that `setBreadcrumbCapacity:` is deprecated for `setMaxBreadcrumbs:` but `setMaxBreadcrumbs:` is not in the BugsnagConfiguration header file yet, only the implementation file.

### Issue

This deprecation exists https://github.com/bugsnag/bugsnag-cocoa/blob/release-v5.23.2/Source/Bugsnag.h#L274-L275 but this header https://github.com/bugsnag/bugsnag-cocoa/blob/release-v5.23.2/Source/BugsnagConfiguration.h doesn't have the new function. This blocks updates if you use warnings as errors

### Environment

Library versions: v5.23.2

**Comment by xander-jones** [comment]
Hi @keith, thanks for the report. We'll take a look into this.

**Comment by xander-jones** [comment]
Hey @keith, the `maxBreadcrumbs` property is declared here https://github.com/bugsnag/bugsnag-cocoa/blob/release-v5.23.2/Source/BugsnagConfiguration.h#L253 which synthesizes the getters and setters. 

Testing this with `v5.23.2` I see no issues when using the new method (`setMaxBreadcrumbs`), and a warning (or error if you've enabled warnings as errors) if I use `setBreadcrumbCapacity`.

Can you please let us know some more details of what you see if you try using the new method?

**Comment by keith** [comment]
Ah sorry I took the conversion instructions too literally and tried to use `configuration.setMaxBreadcrumbs(100)` in Swift instead of `configuration.maxBreadcrumbs = 100`
