### ISSUE TITLE
Device.charging field is a NSNumber when it should be a BOOL

### ISSUE THREAD

**Issue by philkjacobs** [bugsnag/bugsnag-cocoa#672]
### Description
We're seeing invalid payloads returned from multiple endpoints coming only from events sourced in this SDK. The Device field is returning 1 or 0 rather than true or false. The expected behavior is documented here: https://docs.bugsnag.com/product/integrations/data-forwarding/sqs/

We can also compare to the android library: https://github.com/bugsnag/bugsnag-android/blob/7d2ae7782b018f14138f1019f4bf89ed0c9af67d/bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt#L62 which has the correct type.

**Comment by johnkiely1** [comment]
Hi @philkjacobs
Thanks for reporting this and the PR. This will be fixed in the next major release of the Cocoa notifier (v6) currently in testing which we expect will be released soon.

**Comment by philkjacobs** [comment]
Thanks!

**Comment by zhaoze1991** [comment]
hi @johnkiely1 , what is cocoa notifier? after the fix, should iOS client update to latest bugsnag SDK version?

**Comment by mattdyoung** [comment]
Hi @zhaoze1991

By the Cocoa notifier, we just mean bugsnag-cocoa. We describe our open source error reporting libraries as 'notifiers'. Once bugsnag-cocoa v6 is released you'll just need to update to that version of the library to get the fix:
https://github.com/bugsnag/bugsnag-cocoa/releases

**Comment by mattdyoung** [comment]
Fixed in [v6.0.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.0.0).

Note: There are a number of breaking changes in v6.0.0 as part of an effort to improve the interface and make it more consistent across our error reporting libraries, so please refer to the upgrade guide:
https://github.com/bugsnag/bugsnag-cocoa/blob/master/UPGRADING.md
