### ISSUE TITLE
Can't run on OS X 10.8 and 10.9

### ISSUE THREAD

**Issue by gamecat10** [bugsnag/bugsnag-cocoa#681]
### Description
[NSProcessInfo processInfo].operatingSystemVersion is using in BSG_KSSystemInfo.m but it is available only on 10.10 and later.

### Issue
Bugsnag library is not working on 10.8 and 10.9

**Comment by mattdyoung** [comment]
Hi @gamecat10 

We don't aim to support MacOS versions as old as 10.8 and 10.9. The oldest version we test against and provide full support for is 10.11.

**Comment by gamecat10** [comment]
In this case you should fix the readme file:

"The Bugsnag crash reporter for Cocoa library automatically detects crashes and fatal signals in your iOS 8.0+, **macOS 10.8+** and tvOS applications"

**Comment by twometresteve** [comment]
You're right, thank you @gamecat10 .  We'll fix this shortly.
