### ISSUE TITLE
Investigate non-descriptive stacktrace output from Swift project crashes

### ISSUE THREAD

**Issue by kattrali** [bugsnag/bugsnag-cocoa#70]
Projects with significant amounts of Swift source code have non-descriptive stacktrace output on Bugsnag when checking the value of Optionals. The output generally contains `EXC_BREAKPOINT` and not much else. Investigate whether this a library or language error.

**Comment by 14lox** [comment]
+1

**Comment by kattrali** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Q60HtFgo&#x2F;23-cocoa-platform-improvement"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Cocoa Platform Improvement</a>

**Comment by kattrali** [comment]
Patched on the backend, rolling out soon.
