### ISSUE TITLE
Duplicate interface definition for class 'KSCrashReportFilterPassthrough' and other

### ISSUE THREAD

**Issue by thepoortom** [bugsnag/bugsnag-cocoa#72]
Can't run Bugsnag.

I've added Bugsnag via Cocoapods and got several error messages "Duplicate interface definition for class 'KSCrashReportFilter..." in KSCrash target.

I have YandexMetrica (https://github.com/yandexmobile/metrica-sdk-ios) in my project which also uses KSCrash. In Podfile.lock YandexMetrica's dependences explicitly written:
  - YandexMobileMetrica (2.1.1):
    - FMDB (~> 2.2)
    - KSCrash/Recording (~> 0.0.5)
    - KSCrash/Reporting/Filters/AppleFmt (~> 0.0.5)
    - protobuf-c (~> 1.0.1)

I think Bugsnag pod should have similar dependences in its settings to run with other pods such as YandexMetrica which use same subpods.

**Comment by kattrali** [comment]
Thanks for the report, @thepoortom. We're planning to update the library to use a prefixed version of KSCrash since this is a commonly reported issue. This should be released later this week.

**Comment by thepoortom** [comment]
Thanks! I've checked update (4.1.0) but issue remains the same.
