### ISSUE TITLE
The removal of toJson() is a regression and feature loss

### ISSUE THREAD

**Issue by sobri909** [bugsnag/bugsnag-cocoa#734]
I capture the raw JSON dumps of crashes/reports and save them to local database for visible inspection in debug builds of my app. A handful of my beta testers make use of these JSON dumps to better inform their feedback. 

With the removal (deprecation is a mislabelling of the change - it is a removal) of the toJson() method, I can no longer do this.

How do you propose I continue from this point?

**Comment by mattdyoung** [comment]
Hi @sobri909 

We've removed `toJson` from the public API as it's what we use internally to serialize the error report to send to the Bugsnag service and may be subject to removal / change in the future.

We'd generally recommend serializing the `BugsnagEvent` object yourselves from methods on the documented API if you need to extract the error report for your own purposes.

For now `toJson` is still there internally on `BugsnagEvent` so you could use it by adding a class extension and doing something like this:
```
@interface BugsnagEvent ()
- (NSDictionary *_Nonnull)toJson;
@end

@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    BugsnagConfiguration *config = [BugsnagConfiguration loadConfig];
    [config addOnSendErrorBlock:^BOOL (BugsnagEvent *event) {
        NSLog(@"%@", [event toJson]);
        
        return YES;
    }];
    [Bugsnag startWithConfiguration:config];
    
    return YES;
}
@end
```

**Comment by sobri909** [comment]
Hi Matt!

I'm not seeing an Encodable conformance on `BugsnagEvent`. I can't remember what the requirements are for `NSCoding` off the top of my head. But either way, I'm not seeing object properties for the bits that I need. 

This is my code, partially updated to the new API, before I realised it was now impossible to use: 

```swift
        bugsnagConfig.addOnSendError { report -> Bool in
            guard report.severity == .error else { return true }
            guard let session = report.toJson()["session"] as? [String: Any] else { return true }
            guard let startedAt = session["startedAt"] as? String else { return true }
            guard let date = ISO8601DateFormatter().date(from: startedAt) else { return true }
            do {
                let json = try JSONSerialization.data(withJSONObject: rawData, options: [.prettyPrinted])
                let crash = Crash(source: "Bugsnag", date: date, title: report.errorMessage, body: String(data: json, encoding: .utf8))
                crash.save()
                logToFile("SAVED CRASH: \(crash.displayTitle)")
            } catch {
                logToFile("Failed to save Bugsnag crash report")
            }
            return true
        }
```

Can you tell me how to achieve the same with the new API? 

I would appreciate the issue being reopened, as it does currently stand as a feature regression. And I hate to be that guy, but I am paying money for the features I was using, so when they're taken away that's a business issue.

**Comment by johnkiely1** [comment]
Hi @sobri909 

We would recommend you follow the instructions as posted by @mattdyoung above
This [guide] (https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW3) may be useful for defining class extensions.
Similarly [this](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift) this might also be helpful as explains about using bridging headers.

**Comment by sobri909** [comment]
Hi John! I don't need help with class extensions, thanks. I'm three decades deep in this career, so I've got a handle on the basics, and can google what I need to refresh my Objective-C memory 😉

The issue is that the property has been **removed**, but marked as *deprecated*. Deprecation does not mean removal, it means it has been marked as "will be removed in future". That gives developers time to transition, and to make decisions about how to use technologies going forward. 

To my knowledge the property was never marked as deprecated. It has simply transitioned directly from available to removed. For a fairly expensive service, that's not up to par.

It's likely that I will transition to making use of the new reports from MetricKit as a replacement. But in the meantime, given that Bugsnag is not cheap, I think it would be appropriate for the property go through proper deprecation flow management, rather than its current abrupt removal. Part of the purpose of marking a property as deprecated is to expose IDE warnings. The proposed extension would not provide those warnings. 

Apologies for being that guy, but this inappropriately handled API change cost me a chunk of time the other day, and as I said, Bugsnag is not a cheap service. Deprecation and then removal of an existing feature should be managed properly. 

As a way forward, I recommend making the property public again, but marking it as deprecated.

**Comment by sobri909** [comment]
As an addendum: If your intent is to only allow internal use of `toJson()` functionality, then it would make sense to add a *new* private method, with a different name from the previously public method, and make use of that internally.

That would allow you to transition the public method through a proper and normal available -> deprecated -> removed flow over a period of months, without interfering with your internal usage.

**Comment by snmaynard** [comment]
I would recommend you stay on version 5 of the notifier if you dont want to use the extension to make the `toJson` method visible to your code in version 6. We are not going to add a public `toJson` method into v6 because it means we can't change the format of the json without going through a major version change which slows down improvements for our customers.

**Comment by sobri909** [comment]
@snmaynard I described the de facto best practice method for making private a previously public method. Doing the job properly, as described, would allow you the freedom you require to change the format at will, without interfering with existing customers' use of the SDK. 

Given your negative response, I'll be moving on to another bug tracking provider.
