### ISSUE TITLE
Missing disk free/total size reporting

### ISSUE THREAD

**Issue by voidless** [bugsnag/bugsnag-cocoa#74]
Disk size reporting seems to be edited out since version 3.1.3, and Bugsnag site shows 0 bytes free disk for all crashes

**Comment by kattrali** [comment]
Thanks for the report, @voidless. Taking a look.

**Comment by kattrali** [comment]
Can you check if this is affecting particular devices or all iOS devices? In particular, I'm checking whether this only affects newer iOS devices or perhaps only iPads.

**Comment by voidless** [comment]
I have not found any crashes with disk statistics in my account

**Comment by kattrali** [comment]
Thanks, @voidless.

**Comment by anderscarling** [comment]
Can confirm this one as well, all my crash reports shows up as 0 bytes free.

**Comment by konomae** [comment]
There was `freeDisk` and `diskSize`.

https://github.com/bugsnag/bugsnag-cocoa/blob/3e1e351766314f7a2f5bffb5389133dd471216cc/bugsnag/BugsnagNotifier.m#L354
https://github.com/bugsnag/bugsnag-cocoa/blob/3e1e351766314f7a2f5bffb5389133dd471216cc/bugsnag/BugsnagNotifier.m#L396

But, they are not found in current version (5.6.5) :cry:.
