### ISSUE TITLE
Logging messages

### ISSUE THREAD

**Issue by RuiAAPeres** [bugsnag/bugsnag-cocoa#742]
### Description

I would like to start logging system metrics (e.g. request/response times, main thread load) and none of the `notify` family methods seems to be a good fit to log these. 

I would like for a new method to be introduced: `notifiy(message: String)`. This would belong to the `notify` methods family: By default the severity of events generated by this method are set to `.info`.

Thank you.

**Comment by phillipsam** [comment]
Hi @RuiAAPeres you can set the severity of any notification event sent to Bugsnag:
https://docs.bugsnag.com/platforms/ios/reporting-handled-exceptions/#customizing-diagnostic-data

If you would like to log additional metrics alongside your errors, you can make use of additional metadata which is also shown in the link above.

**Comment by RuiAAPeres** [comment]
Hi @phillipsam 

I think I didn't explain myself clearly. 

There are legitimate cases where, although there's no error or exception, I would still like to send logs. Hence why i gave the `notify(message: String)` as an example. For instance, if I want to log the main thread load and keep an eye on that, how would you recommend doing so with your lib?

Thank you

**Comment by phillipsam** [comment]
Hi @RuiAAPeres the way to do this in Bugsnag at the moment would be to create a new NSException or NSError with the message that you want and notify this to Bugsnag with any additional metadata that you require.
In general, Bugsnag is not a replacement for logging and is a way to notify of events that are occurring in your application.
