### ISSUE TITLE
BugsnagBreadcrumbs.arrayValue returns NSArray<NSDictionary*> * not NSArray<NSString*> * as documented

### ISSUE THREAD

**Issue by bolsinga** [bugsnag/bugsnag-cocoa#747]
https://github.com/bugsnag/bugsnag-cocoa/blob/2fd7c67e65bfc5523ecea4705066f9591c831aca/Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m#L170

We are going to pull the breadcrumbs into our internal bug reports. I found the types are incorrectly documented. I'm not sure how, but pre-6.0 the JSON data was decoded, but the dictionary was added to the array. In 6.0 the JSON is not decoded, but the dictionary is still in the array. it's still checked for JSON compatibility.

It should be documented correctly. I also think it would be good to have strings in the array, but that is an open question.

**Comment by phillipsam** [comment]
Hi @bolsinga - yes this has changed in v6, as you have suggested. Thanks for bringing this to our attention, we will look to fix the header docs in the next release.

This is not actually on a public method. The current recommended way of exposing breadcrumbs is by using an OnBreadcrumbCallback method: https://docs.bugsnag.com/platforms/android/configuration-options/#addonbreadcrumb

**Comment by bolsinga** [comment]
@phillipsam Thanks. Since our app is what is leaving the breadcrumbs, having a callback to know what breadcrumb was just sent seems redundant. If there is not a way to query the current breadcrumbs, then it would be best for us to cache the breadcrumbs being sent to Bugsnag and not implement a callback to get the same data. 

If possible, please re-consider having a way to request the current breadcrumbs. W e're working on making our internal bug reports and the data found by Bugsnag "line-up". Thanks.

**Comment by phillipsam** [comment]
Hi @bolsinga - thanks for the clarification. One option available is to use an `OnSendError` callback to get the breadcrumbs list in an event:
https://github.com/bugsnag/bugsnag-cocoa/blob/master/Bugsnag/include/Bugsnag/BugsnagEvent.h#L60

**Comment by bolsinga** [comment]
Hi @phillipsam I haven't been able to update to 6.0 yet because when I last checked, it isn't integrated into BugsnagReactNative / iOS yet. But when I search for "BugsnagEvent alloc" it seems it is created once a crash is detected.

I'd like to get the data Bugsnag is storing *before* a crash is reported. We have an internal bug reporter and it would be nice to be able to see the same data there as is found in our crash reports. I'd also not like to have to duplicate all of Bugsnag's data store. 

I'll state my problem in a less specific way than bread crumbs. How may I query the data Bugsnag is tracking for this app launch to gather it before a crash is detected?

**Comment by bolsinga** [comment]
> Hi @bolsinga thanks for the clarification. We will look into providing a getter for breadcrumbs so you can access this information prior to a crash.

Thanks! If the other meta data was available too, it would be terrific.

**Comment by mattdyoung** [comment]
@bolsinga This has now been added in https://github.com/bugsnag/bugsnag-cocoa/pull/813 and released. There was a separate issue with [v6.1.5](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.1.5) which we've now resolved so we'd recommend using [v6.1.6](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.1.6).
