### ISSUE TITLE
Bugsnag OOM events mix data from across sessions

### ISSUE THREAD

**Issue by jparise** [bugsnag/bugsnag-cocoa#751]
### Description

Bugsnag reports OOMs on the next launch, and the resulting bug report mixes some data from the previous (crashing session) with the current (reporting) session.

### Issue

Bugsnag reports OOMs on the next launch using this code: https://github.com/bugsnag/bugsnag-cocoa/blob/2fd7c67e65bfc5523ecea4705066f9591c831aca/Bugsnag/Client/BugsnagClient.m#L918-L954

It looks like only breadcrumbs and app state are preserved from the previous session. That means that the reported OOM event will "mix in" state from the current (reporting) session, including application version and any additional session data we attach in the crash handler and metadata calls.

It would be a large improvement if most/all of the data reported in the OOM event came from the previous session (which produced the OOM). In practice, this would mean either recording and restoring more crash data, or excluding data from the current session from these particular events, so that the resulted crash report's data was entirely consistent with the state of the application when it OOM'ed.

### Environment

BugsnagReactNative v2.23.9 (but the code looks the same in the latest release)

**Comment by steve-nester-uk** [comment]
@jparise thanks for raising this case.  To fully understand your scenario, could you describe what type of session data would be mixed in (e.g. are you thinking of cases where the app was updated between the crash and the reopen (app version), etc, what kind of session data do you attach)?

**Comment by jparise** [comment]
Some examples:

- We write some additional system state to crash reports via `onCrashHandler`, such as more detailed memory statistics. For OOMs, this state will be for the reporting session and not the crashing session. If we knew in that callback that the crash wasn't for the current session, we wouldn't write those fields.
- We attach the list of our experiment treatment as attributes (using `addAttribute:withValue:toTabWithName:`). Because these can vary across application launches, we see OOM reports associated with the wrong experiment treatments.
- The example you give (seeing crashes split between the crashing version and the new, reporting version) is also valid. We release a new version of our iOS app about once a week, so some (small) percentage of our OOM reports fall into this category.

**Comment by steve-nester-uk** [comment]
@jparise great, thanks for the examples.  We're reviewing options to improve this case

**Comment by mattdyoung** [comment]
Hi @jparise 

Just an update to say that the `onCrashHandler` will no longer run during the reporting session following the fix in [v6.2.4](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.4).
