### ISSUE TITLE
Error reports are dropped on the floor if the device doesn't have a network connection

### ISSUE THREAD

**Issue by mikelikespie** [bugsnag/bugsnag-cocoa#76]
To reproduce:

1. Turn off internet
2. Trigger a notification. note that there's an error sending the report in the log.
3. Quit app.
4. Re-enable internet
3. Relaunch the app. note that it says "0 reports sent"

**Comment by kattrali** [comment]
Thank you for the report, @mikelikespie. I confirmed the issue and am looking into a fix.

**Comment by snmaynard** [comment]
:+1:
