### ISSUE TITLE
Project won't build using SPM installation

### ISSUE THREAD

**Issue by ksullivan1-chwy** [bugsnag/bugsnag-cocoa#769]
### Description
I'm trying to move my Bugsnag dependency from being managed by Carthage to SPM.

### Issue
I removed Bugsnag from Carthage and added it to SPM, but my project can no longer build. The build errors out while linking with the following message: 

`ld: can't find ordinal for imported symbol for architecture x86_64`

### Environment

Library versions:

* Bugsnag version: 6.1.2
* Carthage version (if any): 0.35.0
* iOS/tvOS/macOS version(s): iOS 13.6
* debug mode or production?: Debug

No code changes were made.

**Comment by ksullivan1-chwy** [comment]
I'm not able to reproduce this in an example project, so I don't think action can be taken right now. I will update if I can share a reproduction scenario.

**Comment by xander-jones** [comment]
Hey @ksullivan1-chwy, do let us know if you manage to create a repro example. Have you managed to get your original project working with SPM now?

It's possible that there's some interference between the two dependencies, if Bugsnag's not been fully removed from your project (the one that was installed through Carthage).

Removing the dependency from your `Cartfile` will stop the framework from being updated and managed, but it'll still be in your project. Under the `Carthage` directory, make sure you remove 
* `./Build/iOS/Bugsnag.framework` 
* `./Build/iOS/Bugsnag.framework.dSYM`
* `./Checkouts/bugsnag-cocoa`

You'll then need to manually remove Bugsnag from your frameworks in your Xcode project.

We'll keep this open for a while in case there are any other comments and questions that need to be raised.

**Comment by phillipsam** [comment]
Hi @ksullivan1-chwy - closing this for now as we haven't heard back. Please feel free to comment below if you have further questions.
