### ISSUE TITLE
Xcode analyzer issues reported

### ISSUE THREAD

**Issue by mdcarter1** [bugsnag/bugsnag-cocoa#771]
### Description
Running the Xcode analyzer in combination with integrating Bugsnag via SPM results in 3 Xcode analyzer issues.  Our particular CI pipelines runs Xcode analyzer as part of our build workflow so ideally there should be no issues reported.

### Issue

These are the analyzer issues being reported by Xcode:

1. /bugsnag-cocoa/Bugsnag/KSCrash/Source/KSCrash/Recording/Tools/BSG_KSMachHeaders.m:211:1: warning: Potential leak of memory pointed to by 'newImage'

2. /bugsnag-cocoa/Bugsnag/KSCrash/Source/KSCrash/Recording/Tools/BSG_KSMach.c:345:18: warning: Although the value stored to 'kr' is used in the enclosing expression, the value is never actually read from 'kr'
            if ((kr = thread_suspend(thread)) != KERN_SUCCESS) {
                 ^    ~~~~~~~~~~~~~~~~~~~~~~
3. /bugsnag-cocoa/Bugsnag/KSCrash/Source/KSCrash/Recording/Tools/BSG_KSMach.c:384:18: warning: Although the value stored to 'kr' is used in the enclosing expression, the value is never actually read from 'kr'
            if ((kr = thread_resume(thread)) != KERN_SUCCESS) {

### Environment

Library versions:

* Bugsnag version 6.1.2 via Swift Package Manager

### Example code snippet

See above

**Comment by xander-jones** [comment]
Hey @mdcarter1, thanks for this report. We'll take a look into it!

**Comment by steve-nester-uk** [comment]
This has been released in [v6.1.4](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.1.4)
