### ISSUE TITLE
Type 'Bugsnag' has no member 'configuration'

### ISSUE THREAD

**Issue by michael-mckenna** [bugsnag/bugsnag-cocoa#773]
### Description
Set max breadcrumbs

### Issue
No longer have access to the configuration object after switching to SwiftPM

### Environment

Library versions:

* Bugsnag version (from your Podfile, Podfile.lock, or elsewhere): 6.1.2, SwiftPM
* How are you initializing Bugsnag? Can you share a snippet of your
  `AppDelegate` where Bugsnag is configured?

```
        #if DEBUG
        Bugsnag.start(withApiKey: "debug_key")
        #else
        Bugsnag.start(withApiKey: "release_key")
        #endif
```

### Example code snippet

```swift
import Bugsnag

```
        Bugsnag.configuration().setMaxBreadcrumbs(100)
```

**Comment by mdcarter1** [comment]
@michael-mckenna there were breaking API changes in the 6.x versions.  You will need to make some code changes.  https://github.com/bugsnag/bugsnag-cocoa/blob/master/UPGRADING.md

**Comment by michael-mckenna** [comment]
Oh, my bad. Thanks

**Comment by xander-jones** [comment]
Hi @michael-mckenna, the `BugsnagConfiguration` object is immutable once Bugnsag has started. You should set your maximum number of breadcrumbs prior to calling `Bugsnag.start()`.

For example, you may want to use something like:
```swift
#if DEBUG
  let config = BugsnagConfiguration("debug_key")
#else
  let config = BugsnagConfiguration("release_key")
#endif

config.maxBreadcrumbs = 100
Bugsnag.start(with: config)
```

@mdcarter1 has beaten me to it on this one! As above, if you're moving from a pre-v6 version, please check out the upgrade guide.

**Comment by michael-mckenna** [comment]
@xander-jones thanks for the specifics, I appreciate it!
