### ISSUE TITLE
Support MacCatalyst

### ISSUE THREAD

**Issue by ghazel** [bugsnag/bugsnag-cocoa#775]
Please support MacCatalyst.

This appears to be as simple as `SUPPORTS_MACCATALYST = YES` in the project (we've tested this successfully for the `BugsnagStatic` scheme).

**Comment by steve-nester-uk** [comment]
@ghazel thanks for raising, we'll look into options for adding this.

**Comment by mattdyoung** [comment]
This has been implemented in [v6.8.2](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.8.2).
