### ISSUE TITLE
Bitcode not supported 

### ISSUE THREAD

**Issue by KevinTheGray** [bugsnag/bugsnag-cocoa#78]
Bitcode is not supported, so I am unable to build with Bitcode enabled.
![image](https://cloud.githubusercontent.com/assets/9346834/11939514/a393733a-a7f0-11e5-8ffe-2dea430422f3.png)

To reproduce:
1.) Install Bugsnag without cocoapods
2.) Try to build with Bitcode enabled (Project/Build Settings -> Search for Bitcode)

I'm on version 7.1.1 of XCode, supporting iOS 8.1 and up.  If you need any more information let me know.  Thanks

**Comment by kattrali** [comment]
Thanks for the report, @KevinTheGray. Bugsnag-Cocoa does not yet support bitcode, but it is planned. We need to make some tweaks to the dSYM upload process to ensure crash reports are symbolicated properly

**Comment by thisisjeffwong** [comment]
Hi, is there any plan to update BugSnag to allow automatic uploading of dSYMs when BitCode is enabled? 

Is there something that makes this infeasible?

Thanks!

**Comment by thisisjeffwong** [comment]
According to these install instructions:

http://docs.bugsnag.com/api/dsym-upload/

There is no indication that Bitcode presents a problem for automated dSYM upload. Did the advice change?

**Comment by kattrali** [comment]
Hi @thisisjeffwong, 

The instructions mentioned relate to the dSYM files generated when compiling the app locally. When Bitcode is enabled, Apple recompiles apps to optimize them for each device type, so the dSYM content changes and must be downloaded first via Xcode or iTunes Connect. [Here is a gist of the process using Xcode](http://docs.bugsnag.com/platforms/ios/symbolication-guide/#with-bitcode). 

This could be better automated, though it would be best to open a separate issue for that. :)

**Comment by thisisjeffwong** [comment]
Hi @kattrali,

Thanks for responding. Do you think this fastlane tool would work?

https://krausefx.com/blog/download-dsym-symbolication-files-from-itunes-connect-for-bitcode-ios-apps
