### ISSUE TITLE
Bugsnag appears to block the main thread

### ISSUE THREAD

**Issue by coreyd303** [bugsnag/bugsnag-cocoa#780]
### Description
trying log bugsnag event with out impacting device UI. Dispatching the logging to async does not seem to fix the issue. Delaying dispatch to async does seem to fix it. Ideally bugsnag shouldn't need to be on the main thread.

### Issue
Reporting an even blocks progression of device UI (ie: blocks main thread)

### Environment
iOS 11+

Library versions:

* Bugsnag version (from your Podfile, Podfile.lock, or elsewhere): current
* CocoaPods version (if any) (`pod --version`): 1.9.3

* iOS/tvOS/macOS version(s): 11+
* debug mode or production?: both

**Comment by steve-nester-uk** [comment]
@coreyd303 If I understand the request correctly, it wouldn't work to have Bugsnag run outside of the main thread because Bugsnag requires the stacktrace from the main thread.  Closing for now but please comment if I misunderstood the request and we'll reopen if necessary.
