### ISSUE TITLE
Out of Memory errors appear to be ignoring custom configuration

### ISSUE THREAD

**Issue by Aquilosion** [bugsnag/bugsnag-cocoa#782]
### Description
I have a single Xcode codebase which compiles to many variant apps. Because I'm more interested in seeing errors as a whole rather than per app, they all report to the same Bugsnag project. I override the configuration's `appVersion` and `bundleVersion` to my custom codebase version, which is based on tagged commits, while reporting the app's _actual_ version and build number using custom metadata entries:

```
let config = BugsnagConfiguration.loadConfig()
config.appVersion = codebaseVersion
config.bundleVersion = codebaseVersion

config.addMetadata(Bundle.main.infoDictionary!["CFBundleVersion"] as! String, key: "appBuild", section: "SingleApp")
config.addMetadata(Bundle.main.infoDictionary!["CFBundleShortVersionString"] as! String, key: "appVersion", section: "SingleApp")

Bugsnag.start(with: config)
```

### Issue
Regular errors are coming through as I expect, but out of memory errors appear to be ignoring the configuration completely. They don't have my overridden app and bundle version keys, and they don't include the metadata. These errors are also causing problems in the Bugsnag dashboard because it is generating releases which don't match my codebase versions (but rather the specific app versions, which vary widely in version numbers).

### Environment

Library versions:

* Bugsnag 6.0.0 _(most variant apps are using this version, a few newer ones use newer versions of Bugsnag though I've not seen any OOM errors produced by them, probably due to low volume)_
* CocoaPods 1.9.3
* iOS/tvOS/macOS version(s): 10+
* debug mode or production?: Production

**Comment by steve-nester-uk** [comment]
@Aquilosion thanks for opening the issue.  Currently Out of Memory crash handling only supports a basic pre-determined dataset.  However, we do have a project open to review options for expanding that dataset to allow for the metadata, which would cover your example.  We'll keep this issue thread posted with any updates.
