### ISSUE TITLE
NSInvalidArgumentException: attempt to insert nil object from objects[2]

### ISSUE THREAD

**Issue by jpsim** [bugsnag/bugsnag-cocoa#788]
### Describe the bug

We're seeing an increase in uncaught runtime exceptions coming from Foundation in our latest integration of the Bugsnag SDK on iOS.

```
NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]

0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         _objc_exception_throw
2  CoreFoundation          __CFThrowFormattedException
3  CoreFoundation          -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
4  CoreFoundation          +[NSDictionary dictionaryWithObjects:forKeys:count:]
5  [REDACTED]              __58-[BugsnagSessionTrackingApiClient deliverSessionsInStore:]_block_invoke ([REDACTED])
6  Foundation              ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
7  Foundation              -[NSBlockOperation main]
8  Foundation              -[__NSOperationInternal _start:]
9  Foundation              ___NSOQSchedule_f
10 libdispatch.dylib       __dispatch_block_async_invoke2
11 libdispatch.dylib       __dispatch_client_callout
12 libdispatch.dylib       __dispatch_continuation_pop$VARIANT$mp
13 libdispatch.dylib       __dispatch_async_redirect_invoke
14 libdispatch.dylib       __dispatch_root_queue_drain
15 libdispatch.dylib       __dispatch_worker_thread2
16 libsystem_pthread.dylib __pthread_wqthread
17 libsystem_pthread.dylib _start_wqthread
```

### Steps to reproduce

We haven't pinned down steps to reproduce yet. We'll update this ticket when we find out more.

### Environment

* Bugsnag version: 6.1.2
* CocoaPods version: N/A
* Carthage version (if any): N/A
* iOS/tvOS/macOS version(s): 11.4.1 to 12.4.8. None on iOS 13 or 14 so far.
* Simulator or physical device: Physical Device
* Xcode version: Xcode 11.5 (11E608c)
* Swift version (if applicable): Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)

**Comment by steve-nester-uk** [comment]
@jpsim thanks for raising the issue, we have seen [similar](https://github.com/bugsnag/bugsnag-cocoa/issues/461) (but not exactly the same) issues before that was fixed in 6.1.0 by adding validation of configuration input.  I'm wondering if there was a case that was missed (of course it's also possible that is unrelated) - could you also provide snippets of your bugsnag configuration?

**Comment by jpsim** [comment]
Is there a private channel where I could share that information with you?

**Comment by steve-nester-uk** [comment]
@jpsim of course, please email support@bugsnag.com and we'll take a look.

**Comment by jpsim** [comment]
Sent an email. Thanks!

**Comment by xander-jones** [comment]
Hey @jpsim, a fix for this was released in https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.1.5, under PR https://github.com/bugsnag/bugsnag-cocoa/pull/807
