### ISSUE TITLE
Enable the "Require Only App-Extension-Safe API" build setting if possible

### ISSUE THREAD

**Issue by jeffhunter** [bugsnag/bugsnag-cocoa#795]
The docs for bugsnag-cocoa mention using it in app extensions:

https://docs.bugsnag.com/platforms/ios/#app-extensions

However, it does not appear that the Bugsnag project has the "Require Only App-Extension-Safe API" build setting enabled, which it should if it supports app extensions. Because of this I get the following warning when trying to use Bugsnag:

`ld: warning: linking against a dylib which is not safe for use in application extensions: .../Carthage/Build/iOS/Bugsnag.framework/Bugsnag`

I raised this issue awhile back: #117

I think this somehow got lost in the bugsnag-cocoa v6 upgrade, because now that I'm trying to use v6, I'm getting that message again.

Can you please enable "Require Only App-Extension-Safe API" build setting?

**Comment by steve-nester-uk** [comment]
@jeffhunter thanks for raising, we'll take a look and post any updates here.

**Comment by johnkiely1** [comment]
HI @jeffhunter,

This has now been fixed and has been released in [v6.1.7](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.1.7).
