### ISSUE TITLE
-[__NSDictionaryI setObject:forKeyedSubscript:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by jonahollman** [bugsnag/bugsnag-cocoa#817]
**Describe the bug**
We're seeing a crash on the launch of our app. When Bugsnag is uninstalled, the app works fine. 

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x283290fc0'`

When I add a breakpoint, it takes me to line 284 in BSGOutofMemoryWatchdog.m: 
`contents[BSGKeyApp][APP_KEY_IS_MONITORING_OOM] = [self.kvStore NSBooleanForKey:KV_KEY_IS_MONITORING_OOM defaultValue:false];`

**Steps to reproduce**
Launching the app and starting Bugsnag on launch.

**Environment**
Bugsnag version: 6.1.5
CocoaPods version: 1.9.3
Carthage version (if any): N/A
iOS/tvOS/macOS version(s): iOS 13 or 14 so far
Simulator or physical device: Physical device.
Xcode version: Xcode 12 (12A7209)
Swift version (if applicable): Swift 5

**Comment by xander-jones** [comment]
Hey @jonahollman, thanks for reporting this. Are you seeing the same issue with any previous versions of `bugsnag-cocoa`? If you point your `Podfile` to `v6.1.4`, do you see the same issue? There have been some changes in this area in `v6.1.5`. I am looking into reproducing this error now, but this sanity check would be very helpful to help expedite the check.

**Comment by jonahollman** [comment]
@xander-jones I'm not seeing the issue when I revert to v6.1.4. I'll use that as a workaround for the time-being. Thanks!

**Comment by randarnold** [comment]
I'm also seeing this exception, I just upgraded to 6.1.5 from 6.1.2 where There was no issue.

**Comment by randarnold** [comment]
6.1.4 is also not reproducing the crash for me.

**Comment by xander-jones** [comment]
Hey @randarnold, thank you for your feedback also. Could you please let us know which version of Xcode you seeing this on? And which iOS version are you targeting?

**Comment by randarnold** [comment]
Xcode 12, running on iOS 14 on an iPhone 11 Pro (targetting iOS 12 and later).

**Comment by xander-jones** [comment]
Thanks! I'm not seeing this crash just yet using Xcode 12.0, and running on iOS 14.0; I wonder if there's a commonality in your configurations that I don't have set at the moment. @randarnold @jonahollman, would you please drop us a message at support@bugsnag.com just detailing your configuration of Bugsnag? Additionally, do you see this issue when running in a simulator too?

For future travellers, if you see this issue, reverting to `bugsnag-cocoa` v6.1.4 is the best solution at present. You can do this by adjusting your `Podfile` to read:
```
  pod 'Bugsnag', '6.1.4'
```

**Comment by randarnold** [comment]
It doesn't happen for me in the simulator, will send my config.

**Comment by xander-jones** [comment]
Hey @jonahollman, @randarnold –– Thanks for highlighting this to us, a release will be coming very shortly!

**Comment by xander-jones** [comment]
This has been released in https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.1.6

**Comment by randarnold** [comment]
Looks good! 👍 Thank you.
