### ISSUE TITLE
How to upload dSYM

### ISSUE THREAD

**Issue by ppamorim** [bugsnag/bugsnag-cocoa#82]
Hi Bugsnag team.

I'm trying to upload the dSYM of my project from my Mac but I failed every time that I tried.

    curl https://upload.bugsnag.com/ -F dsym=@MyApp.app.dSYM
    curl -o /Users/Pedro/Desktop/MyApp.app.dSYM 'https://bugsnag.com/services/upload/xxxxxxxx' | ruby
    curl 'https://bugsnag.com/services/upload/xxxxxxxx' -F dsym='@/Users/Pedro/Desktop/MyApp.app.dSYM'

`xxxxxxxx` is the key of my app. 
Do you know any software or any code that help me to resolve it?

**Comment by kattrali** [comment]
Hi @ppamorim, thank you for the report. Your usage looks correct, do you receive any output from the `curl` command after it is completed?

    curl -F dsym=@MyApp.app.dSYM https://upload.bugsnag.com/

**Comment by snmaynard** [comment]
One thing to note is that the dsym "file" is actually a folder and the dsym itself is actually in Contents/Resources/DWARF/ inside the dsym folder. You need to upload the file itself using curl.

**Comment by kattrali** [comment]
That's a good point, I will submit a patch for the [upload API guide](https://bugsnag.com/docs/notifiers/ios/dsym) to be clearer about the likely usage of the command, perhaps like:

curl -F dsym=@MyApp.app.dSYM/Contents/Resources/DWARF/MyApp https://upload.bugsnag.com/

**Comment by snmaynard** [comment]
I've updated the documentation to hopefully clear this up for future travellers
