### ISSUE TITLE
Xcode Analyzer Issue in BSGConfigurationBuilder

### ISSUE THREAD

**Issue by mdcarter1** [bugsnag/bugsnag-cocoa#849]
### Describe the bug
Running the Xcode analyzer in combination with integrating Bugsnag via SPM results in 1 Xcode analyzer issues. Our particular CI pipelines runs Xcode analyzer as part of our build workflow so ideally there should be no issues reported.

### Steps to reproduce
These are the analyzer issues being reported by Xcode:
```
/bugsnag-cocoa/Bugsnag/Configuration/BSGConfigurationBuilder.m:21:36: warning: nil passed to a callee that requires a non-null 1st parameter
    BugsnagConfiguration *config = [[BugsnagConfiguration alloc] initWithApiKey:apiKey];
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

### Environment
* Bugsnag version: 6.2.1

**Comment by xander-jones** [comment]
Hey @mdcarter1, thanks for raising this with us. We'll take a look into it.

**Comment by xander-jones** [comment]
Hey @mdcarter1, a fix for this has been released in https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.4

Additionally, the clang static analyzer has now been added as part of our CI to pick up these issues in future.
