### ISSUE TITLE
Easy way to force a crash

### ISSUE THREAD

**Issue by asgeo1** [bugsnag/bugsnag-cocoa#85]
Could you add a method which forces a crash?  That would be handy for when testing.

Apologies if there is already such a thing, but I couldn't see it.

**Comment by kattrali** [comment]
Hi @asgeo1, to force a crash, you could add a button and method to your app directly to throw an exception or assertion failure. For example, in Swift:

```swift
let items = [1, 2, 3]
let item = items[5]
```

or Objective-C:

```objc
NSArray* items = @[@1, @2, @3];
NSNumber* item = items[5];
```

will cause the app to crash, and when bugsnag is configured correctly, the next successful launch of the app will then send the error reports generated.

**Comment by asgeo1** [comment]
Hi @kattrali,

Yes, I know I can do that. I was more thinking from the point of view that having a method to force a crash would just be easy and handy.

I guess I was coming from Crashlytics and they have a `[[Crashlytics sharedInstance] crash];` method, which I always found useful.
