### ISSUE TITLE
Not able to compile in release  build

### ISSUE THREAD

**Issue by manbir-app-curefit** [bugsnag/bugsnag-cocoa#876]
I am adding this in tv-OS, everything working perfectly fine if I run i debug mode, But as soon as I change the scheme to release it is not able to Find Bugsnag. 

I tried using cocoapod and manually linking both having same issue.

Tried on x-code 12.0.1
<img width="979" alt="Screenshot 2020-11-04 at 1 32 09 AM" src="https://user-images.githubusercontent.com/58170508/98034794-8fd6f600-1e3d-11eb-8e0a-9ce1086c06dd.png">

**Comment by xander-jones** [comment]
Hey @manbir-app-curefit, glad to see you've found a resolution for this. For the sake of future travellers, would you please share what your fix for this was?
