### ISSUE TITLE
'KSCrashReportWriter.h' file not found

### ISSUE THREAD

**Issue by ben-j69** [bugsnag/bugsnag-cocoa#91]
The project was working well, I ran pod update and then I got this error despite the file is in my project folder.

/Users/XXX/Desktop/XXXX/XXX-ios-client/Pods/Headers/Public/Bugsnag/BugsnagConfiguration.h:30:9: 'KSCrashReportWriter.h' file not found

**Comment by kattrali** [comment]
Hi @ben-j69, thank you for the report. Can you post your Podfile here? I'd like to double check the version used to ensure I'm debugging the correct issue.

**Comment by carrarodev** [comment]
Same error here. I've removed & installed bugsnag again after #92, but the error persist. I've also cleaned project.
Attached my podfile
![podfile](https://cloud.githubusercontent.com/assets/402719/12921547/163d4fd0-cf4e-11e5-9fab-3461e205f5ee.png)
