### ISSUE TITLE
Bugsnag fails to identify jailbroken device

### ISSUE THREAD

**Issue by zbencz3** [bugsnag/bugsnag-cocoa#913]
### Describe the bug
Device jailbroken with [Checkra1n](https://checkra.in/) or [Unc0ver](https://unc0ver.dev/) is not marked as jailbroken by Bugsnag.

### Steps to reproduce
1. Jailbreak the device with one of the above mentioned jailbreaks.
2. Use Bugsnag to send an event.
3. Inspect the Event > Device > jailbroken property.
4. Observe the property being false.

Expected outcome: the jailbroken property should be set to true.

### Environment
* Bugsnag version: 6.2.4
* CocoaPods version: 1.10.0
* Simulator or physical device: iPhone SE iOS 14.0.1 (Checkra1n), iPad Air 1 iOS 12.4.6 (Unc0ver)
* Xcode version: 12.2 (12B45b)

#### Additional details
Bugsnag [uses](https://github.com/bugsnag/bugsnag-cocoa/blob/d6509bf8f6c2687de477749a954e0dd2d022272a/Bugsnag/KSCrash/Source/KSCrash/Recording/BSG_KSSystemInfo.m#L263-L265) the `MobileSubstrate` image string to determine whether a device is jailbroken. 

With the above mentioned jailbreaks the `MobileSubstrate` image might not necessarily be there. See the list of loaded images:
[Checkra1n_iPhoneSE1_iOS14.0.1_loaded_images.txt](https://github.com/bugsnag/bugsnag-cocoa/files/5603431/Checkra1n_iPhoneSE1_iOS14.0.1_loaded_images.txt)
[Unc0ver_iPad1_iOS12.4.6_loaded_images.txt](https://github.com/bugsnag/bugsnag-cocoa/files/5603433/Unc0ver_iPad1_iOS12.4.6_loaded_images.txt)
It seems the `MobileSubstrate` image is loaded depending on the tweak used, e.g. [Kill Switch 2](https://github.com/nabla-c0d3/ssl-kill-switch2) would load it and then Bugsnag would mark the device as jailbroken, but having OpenSSL, Cydia, etc would not mark the device as jailbroken.

To improve detection I suggest adding additional image strings like `SubstrateBootstrap`, `substitute-inserter`, and possibly others for `Procursus` (OdysseyRa1n), `libhooker` (Chimera).

Also, if possible please expose the `isJailbroken` method to avoid having to replicate this basic detection.

Thanks.

EDIT:

KillSwitch2 related log with loaded frameworks:
[Checkra1n_iPhoneSE_iOS14.0.1_KillSwitch2.txt](https://github.com/bugsnag/bugsnag-cocoa/files/5603591/Checkra1n_iPhoneSE_iOS14.0.1_KillSwitch2.txt)
Note the `/Library/MobileSubstrate/DynamicLibraries/SSLKillSwitch2.dylib` which would trigger the detection because of the substring `MobileSubstrate`.

**Comment by mattdyoung** [comment]
Hi @zbencz3 

Thanks for the info! We have some planned work coming up to improve jailbroken/rooted detection on both iOS and Android so we'll look into factoring in your suggestions as part of that.

**Comment by zbencz3** [comment]
v6.6.4 includes More robust jailbreak detection https://github.com/bugsnag/bugsnag-cocoa/pull/1000

**Comment by mattdyoung** [comment]
Yes. This has been addressed in [v6.6.4](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.6.4).
