### ISSUE TITLE
Separate Bugsnag-defined context from user-defined context

### ISSUE THREAD

**Issue by sethfri** [bugsnag/bugsnag-cocoa#927]
### Description

Currently Bugsnag has a field, `context`, that they use to set what is deemed as the issue "title" from a UX perspective. Bugsnag allows this to be overridable, which can allow for very cool bookmarks to be set up - like [Bugsnag's search and segmentation guide](https://www.bugsnag.com/content/search-and-segmentation-guide) references. However, if you override this yourself to set which feature the error is coming from, you lose the "title" that Bugsnag sets in its context.

**Describe the solution you'd like**

I propose that Bugsnag introduce two new `beginTag` and `endTag` methods, which take in an `NSString *`. This would allow us to set "bookends" for a feature, so that if any crash happens between the beginning tag and the end tag, it would be tagged appropriately as belonging to that feature.

This would unlock huge segmentation opportunities for us, and allow us to create custom bookmarks/dashboards for various workstream teams that work on our app.

**Describe alternatives you've considered**

I've tried to hack around this problem, but it's very difficult. I wanted to do something like `"\(featureName): \(Bugsnag.context())", but the problem with that is Bugsnag doesn't set its own context until either right before it sends the report, or maybe even on the server side (I'm not sure which yet).

**Comment by xander-jones** [comment]
Hey @sethfri, cool idea! I think this could be really handy. Keeping the original context is likely something most people will want, so I've got a suggestion that I think will work for you in this case, giving you custom context, but also preserving the original context too by wrapping some already existing Bugsnag functions with `beginTag` and `endTag` methods.

You can call these methods at any time once Bugsnag is initialized as your app is navigated and will apply to all subsequent crashes and handled errors until `endTag` is called, or Bugsnag is re-initialized.

Obj-C example
```objc
NSString *const BugsnagFeatureContextSection = @"app";         /// The Bugsnag tab which the feature context will show on
NSString *const BugsnagFeatureContextKey = @"feature context"; /// The name of the key for which the feature value will be assigned to.
-(void)beginTag:(NSString *)feature {
    [Bugsnag addMetadata:feature withKey:BugsnagFeatureContextKey toSection:BugsnagFeatureContextSection];
}
-(void)endTag {
    [Bugsnag clearMetadataFromSection:BugsnagFeatureContextSection withKey:BugsnagFeatureContextKey];
}
```
Call with `[self beginTag:@"the best feature ever"];`. Additional calls to this will just overwrite the feature context.

For future travellers too, here's an equivalent Swift example
```swift
let BugsnagFeatureContextSection: String = "app"         /// The Bugsnag tab which the feature context will show on
let BugsnagFeatureContextKey: String = "feature context" /// The name of the key for which the feature value will be assigned to.
func beginTag(feature: String) {
    /// Calling this more than once will overwrite the feature context.
    Bugsnag.addMetadata(feature, key: BugsnagFeatureContextKey, section: BugsnagFeatureContextSection)
}
func endTag() {
    Bugsnag.clearMetadata(section: BugsnagFeatureContextSection, key: BugsnagFeatureContextKey)
}
```
Call with `beginTag(feature: "a potentially broken feature")`. As above, repeat calls to this will just overwrite the feature key.

Adding a custom filter on this key will allow you to produce bookmarks that relate specifically to features you want to know about. Will raise this to see if it's something we'd want to add to the core library, too.

**Comment by sethfri** [comment]
Thanks for the detailed reply @xander-jones! I think this solution could definitely work with some tweaking.

One issue I have with using custom metadata for this is the limit Bugsnag gives on custom filters. Having this constantly eat up a custom filter isn't ideal, so it'd be nice if this were just built into Bugsnag.

I also think we'd want to add a stack into the implementation so that `endTag` pops the most recent feature off the stack (for when one feature is presented from another). That's pretty straightforward, but again would be nice if the library could just handle this for us.

**Comment by johnkiely1** [comment]
Hi @sethfri,

I have added this to the backlog for consideration, we will let you know of any updates here. In the meantime let us know if need any help implementing the solution suggested by @xander-jones.

**Comment by sethfri** [comment]
Resolving in favor of #1087
