### ISSUE TITLE
Breadcrumbs not included in uncaught exceptions

### ISSUE THREAD

**Issue by anderscarling** [bugsnag/bugsnag-cocoa#93]
It seems like breadcrumbs logged with `Bugsnag+leaveBreadcrumbWithMessage:` is not included when logging uncaught nsexceptions.

Root cause seems to be that the breadcrumbs are only added to `configuration.metaData` in `notify:withData:atSeverity:atDepth:` which only seems to be used for manually reported exceptions. 
When KSCrash calls `serialize_bugsnag_data` (as it's `onCrash` callback) for other exception types breadcrumbs will not be in the meta data struct.

Manually hacking the situation by calling `[[Bugsnag performSelector:@selector(notifier)] performSelector:@selector(serializeBreadcrumbs)];` after each call to `leaveBreadcrumbWithMessage` seems to work around the issue.

**Comment by kattrali** [comment]
Thank you for the report, @anderscarling. You are correct that the latest release does not include breadcrumbs with uncaught exceptions. However this issue has been resolved per #86, which should be released later this week.

**Comment by anderscarling** [comment]
Cool, thanks! Sorry that I didn't check recent changes before writing up an issue.

**Comment by kattrali** [comment]
No problem, glad to help!
