### ISSUE TITLE
KSCrashReportWriter.h file not found

### ISSUE THREAD

**Issue by carrarodev** [bugsnag/bugsnag-cocoa#94]
I've removed & installed bugsnag again after #92, but the error persist. I've also cleaned project.
Here my podfile
![podfile](https://cloud.githubusercontent.com/assets/402719/12921612/60bab4f8-cf4e-11e5-8be1-9f0e51f2dbcf.png)

**Comment by jjohnsonvng** [comment]
Getting same Issue

Any updates?
