### ISSUE TITLE
Delete oldest breadcrumbs when over 1 MB limit

### ISSUE THREAD

**Issue by sethfri** [bugsnag/bugsnag-cocoa#942]
### Description

Currently, Bugsnag throws away errors when the payload breaches the 1 MB limit, typically due to too many breadcrumbs added.

**Describe the solution you'd like**

Bugsnag has a similar limit for the number of breadcrumbs, a max of 100. When you breach the 100 limit, my understanding is that the oldest breadcrumbs are thrown away, rather than the entire error being rejected. It would be nice if we could do the same thing here, throwing away the oldest breadcrumbs until the payload is under the 1 MB limit rather than losing the entire error

**Describe alternatives you've considered**
None

**Comment by johnkiely1** [comment]
Hi @sethfri,

This is something we are aware of and are looking at possible solutions. We hope to begin work on this soon.

**Comment by nickdowell** [comment]
As of [v6.22.0](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.22.0) Bugsnag throws away the oldest breadcrumbs until the payload is under the 1 MB limit, to prevent payloads being lost :tada:

We also increased the default and maximum values for `maxBreadcrumbs` to 100 and 500, respectively.
