### ISSUE TITLE
Add tvOS support

### ISSUE THREAD

**Issue by cemolcay** [bugsnag/bugsnag-cocoa#95]
please add tvos support to podspec

**Comment by kattrali** [comment]
Thank you for the request, @cemolcay. I'm adding this (and watchOS support) to the roadmap for the next minor release. The only reason to hold off at the moment is that the podspec upstream in https://github.com/kstenerud/KSCrash will need tvOS support and testing as well.

**Comment by YoavJivi** [comment]
hi is there an update about the upcoming support for tvOS?
