### ISSUE TITLE
Propagate Error from try!

### ISSUE THREAD

**Issue by sethfri** [bugsnag/bugsnag-cocoa#950]
When we crash by using `try!` on a method that throws an `Error`, right now we get a crash report in Bugsnag that tells us why we crashed, but we don't know what the error was. We'd like that error to propagate to Bugsnag, similar to the work to propagate errors out of `fatalError` in #318. We're not sure if the crash diagnostics provide this info, but we're opening the feature request optimistically :)

**Comment by xander-jones** [comment]
Hey @sethfri, this functionality should be covered by #318 so closing this one out to keep track in that issue. For future travellers, the PR of interest is near merging and can be found here: https://github.com/bugsnag/bugsnag-cocoa/pull/948
