### ISSUE TITLE
Symbolicating crash using build phase causes fastlane distribution error

### ISSUE THREAD

**Issue by prgorasiya** [bugsnag/bugsnag-cocoa#969]
I am using latest version of Bugsnag iOS SDK and have implemented manual build phase to upload symbols for symbolicating crashes.

I followed this doc [https://docs.bugsnag.com/platforms/ios/symbolication-guide/#adding-a-build-phase-manually](url)

After adding the script, my fastlane setup has started throwing issues. It cant export archives, neither for development nor for distribution.

Here is the snippet of my fastfile for archiving and uploading development build to firebase app distribution.

```
lane :beta do
    settings_to_override = {
      :BUNDLE_IDENTIFIER => "<Bundle ID>",
      :PROVISIONING_PROFILE_SPECIFIER => "<Profile Name>"
    }

    build_app(
        scheme: "<Scheme name>",
        export_method: "development",
        output_directory: "/Users/paras/Desktop",
	output_name: "<IPA>.ipa",
	xcargs: settings_to_override,
	export_options: {
       		provisioningProfiles: {"<bundle ID>" => "<profile name>"}
        }
    )
    
    firebase_app_distribution(
        app: "<ID>",
        groups: "Team"
    )
  end
```

I am not sure if I am doing anything wrong with the build phase but this issue started after we migrated to Bugsnag and changed the build phase.

Thanks

**Comment by xander-jones** [comment]
Hey @prgorasiya, what does the output look like when you run this lane? Can you please run Fastlane with `--verbose` to give us as much info as possible to take a look into.

If you remove the build phase script, does the Fastlane archive then work?

**Comment by prgorasiya** [comment]
Yes it does archive successfully without the Bugsnag phase script.
Here is the last part of fastlane action, the error fastlane shows is weird and irrelevant, I can assure that it has nothing to do with my `export_method` define in fastfile.
I can successfully archive just by removing the Bugsnag phase script.
I have added Bugsnag phase script at the last position in my project and thats where it throws me error, I have also checked the Xcode log file and it has no description about the error whatsoever.
```
Running script '[CP] Copy Pods Resources'
▸ Generating '<AppName>.app.dSYM'
▸ Running script 'Run Script'
▸ Running script 'Run Script'
▸ Running script 'Run Script'
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/paras/Library/Developer/Xcode/DerivedData/<AppName>-aydqlcjzjvbvrlcblnikdehxrfmy/Build/Intermediates.noindex/ArchiveIntermediates/<AppName>/IntermediateBuildFilesPath/<AppName>.build/Release-iphoneos/<AppName>.build/Script-6AB24C4825BFB3210093503A.sh
(1 failure)
ERROR [2021-01-26 10:37:27.92]: Exit status: 65

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.171.0                 |
| export_method | development             |
| sdk           | iPhoneOS14.3.sdk        |
+---------------+-------------------------+

INFO [2021-01-26 10:37:27.97]: ▸ 	from /Users/paras/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
INFO [2021-01-26 10:37:27.97]: ▸ 	from /Users/paras/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/setup.rb:20:in `<top (required)>'
INFO [2021-01-26 10:37:27.97]: ▸ 	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
INFO [2021-01-26 10:37:27.97]: ▸ 	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
INFO [2021-01-26 10:37:27.97]: ▸ Command PhaseScriptExecution failed with a nonzero exit code
INFO [2021-01-26 10:37:27.97]: 
ERROR [2021-01-26 10:37:27.97]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
WARN [2021-01-26 10:37:27.97]: 📋  For the complete and more detailed error log, check the full log at:
WARN [2021-01-26 10:37:27.97]: 📋  /Users/paras/Library/Logs/gym/<AppName>-<AppName>.log
INFO [2021-01-26 10:37:27.97]: 
ERROR [2021-01-26 10:37:27.98]: Your `export_method` in gym is defined as `development`
ERROR [2021-01-26 10:37:27.98]: which might cause problems when signing your application
ERROR [2021-01-26 10:37:27.98]: Are you sure want to build and export for development?
ERROR [2021-01-26 10:37:27.98]: Please make sure to define the correct export methods when calling
ERROR [2021-01-26 10:37:27.98]: gym in your Fastfile or from the command line
INFO [2021-01-26 10:37:27.98]: 
INFO [2021-01-26 10:37:27.98]: 
ERROR [2021-01-26 10:37:27.98]: Looks like fastlane ran into a build/archive error with your project
ERROR [2021-01-26 10:37:27.98]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2021-01-26 10:37:27.98]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2021-01-26 10:37:27.98]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2021-01-26 10:37:27.98]: sure your project is set up correctly.
ERROR [2021-01-26 10:37:27.98]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2021-01-26 10:37:27.98]: the full commands printed out in yellow in the above log.
ERROR [2021-01-26 10:37:27.98]: Make sure to inspect the output above, as usually you'll find more error information there
INFO [2021-01-26 10:37:27.98]: 
INFO [2021-01-26 10:37:27.98]: -------------------
INFO [2021-01-26 10:37:27.98]: --- Step: slack ---
INFO [2021-01-26 10:37:27.98]: -------------------
INFO [2021-01-26 10:37:32.33]: Successfully sent Slack notification
WARN [2021-01-26 10:37:32.33]: Lane Context:
INFO [2021-01-26 10:37:32.33]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
ERROR [2021-01-26 10:37:32.33]: Error building the application - see the log above
INFO [2021-01-26 10:37:32.33]: Successfully generated documentation at path '/Users/paras/<AppName>-ios/fastlane/README.md'

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | build_app                  | 273         |
| 4    | slack                      | 4           |
+------+----------------------------+-------------+

DEBUG [2021-01-26 10:37:32.34]: All plugins are up to date
ERROR [2021-01-26 10:37:32.34]: fastlane finished with errors
DEBUG [2021-01-26 10:37:32.34]: All plugins are up to date
```

Here is my fastfile just for the reference:
```
lane :beta do

    settings_to_override = {
      :BUNDLE_IDENTIFIER => "<Bundle ID>",
      :PROVISIONING_PROFILE_SPECIFIER => "<App name>"
    }

    build_app(
        scheme: "<App schemen>",
        export_method: "development",
        output_directory: "/Users/paras/Desktop",
	output_name: "<IPA name>.ipa",
	xcargs: settings_to_override,
	export_options: {
       		provisioningProfiles: {"<Bundle ID>" => "<Profile name>"}
        }
    )
    
    #upload_symbols_to_bugsnag

    slack(message: "Successfully Archived <App name> Build!!!")

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
```
Because the phase script doesnt work I am using `upload_symbols_to_bugsnag` fastlane plugin and to show you the logs I commented it out and used the phase sccript.

**Comment by xander-jones** [comment]
Thanks for the detailed response! 

`ERROR [2021-01-26 10:37:27.92]: Exit status: 65` is not an exit code that I have seen before whilst running the manual upload build phase. Is your shell set to `/usr/bin/ruby` for this script? Can you drop us a screenshot of your build phases in Xcode? Please feel free to send this to support@bugsnag.com quoting the issue ID here if you'd rather not share publicly.

For further debugging, you may also wish to drop a `--verbose` into the `curl` command of the build phase script to see whether it's this call to upload that's returning a non-zero exit code that's heading back up the stack. However, I suspect it's something more fundamental with the Ruby set up based on the stack trace making calls to `bundler`?

Just to confirm, using the `upload_symbols_to_bugsnag` Fastlane plugin is uploading symbols as expected for you, but the manual build phase is not? Out of interest, why are you opting to use the build phase to upload the symbols rather than the Fastlane plugin?

**Comment by prgorasiya** [comment]
Yes @xander-jones I did set `/usr/bin/ruby` for the script.
Here are my other 2 scripts
```
1st Script (Shell : /bin/sh)
/usr/local/bin/carthage copy-frameworks
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


2nd Script (Shell : /bin/sh)
echo "Target architectures: $ARCHS"

APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"
echo $(lipo -info "$FRAMEWORK_EXECUTABLE_PATH")

FRAMEWORK_TMP_PATH="$FRAMEWORK_EXECUTABLE_PATH-tmp"

# remove simulator's archs if location is not simulator's directory
case "${TARGET_BUILD_DIR}" in
*"iphonesimulator")
echo "No need to remove archs"
;;
*)
if $(lipo "$FRAMEWORK_EXECUTABLE_PATH" -verify_arch "i386") ; then
lipo -output "$FRAMEWORK_TMP_PATH" -remove "i386" "$FRAMEWORK_EXECUTABLE_PATH"
echo "i386 architecture removed"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_TMP_PATH" "$FRAMEWORK_EXECUTABLE_PATH"
fi
if $(lipo "$FRAMEWORK_EXECUTABLE_PATH" -verify_arch "x86_64") ; then
lipo -output "$FRAMEWORK_TMP_PATH" -remove "x86_64" "$FRAMEWORK_EXECUTABLE_PATH"
echo "x86_64 architecture removed"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_TMP_PATH" "$FRAMEWORK_EXECUTABLE_PATH"
fi
;;
esac

echo "Completed for executable $FRAMEWORK_EXECUTABLE_PATH"
echo $(lipo -info "$FRAMEWORK_EXECUTABLE_PATH")

done
```

Using `upload_symbols_to_bugsnag` plugin works just fine, but once I stop using the plugin and add Bugsnag script I start getting a non-zero exit code and cant archive.
I want to use build phase so that it will upload symbols even in development phase with every run from Xcode. 
One more thing which is just my observation but not sure if its true, using build phase script I seem to get more detailed crash logs on Bugsnag dashboard, but sometimes with fastlane plugin I dont see all the details, like Class and function of crash, full stack trace, user details etc.

**Comment by xander-jones** [comment]
The Fastlane `upload_symbols_to_bugsnag` and Build script phase both upload the same files to the same endpoint, so there should be no difference in the report you see on bugsnag if you're triggering the report with the same stack trace.

When you run the build as a Debug/Release through Xcode, does it also exit with the same status code?

Please can you swap out the script for the following script (also uses the shell `/usr/bin/ruby`, replacing `YOUR_API_KEY`, run the build, and let us know what the output looks like:

```ruby
fork do
  Process.setsid

  require 'shellwords'

  Dir["#{ENV["DWARF_DSYM_FOLDER_PATH"]}/*/Contents/Resources/DWARF/*"].each do |dsym|
    puts dsym
    system("dwarfdump -u #{Shellwords.escape(dsym)}")
    system("curl --http1.1 -F apiKey=YOUR_API_KEY -F dsym=@#{Shellwords.escape(dsym)} -F projectRoot=#{Shellwords.escape(ENV["PROJECT_DIR"])} https://upload.bugsnag.com/")
  end
end
```

If successful, it'll look a bit like the following, but if not we should see a more verbose error output here:

![image](https://user-images.githubusercontent.com/9535852/107063592-79409200-67d2-11eb-93f9-bfe50e05357c.png)

Please can you let us know what the output of this is?

**Comment by prgorasiya** [comment]
The new script also fails when archiving, and the error output is same as I shared earlier. Its strange that i dont face such issue when I run the build from Xcode on my test phone and I can also archive using Xcode without any issue.
Its just that I cant archive using fastlane if I use the build phase script.

**Comment by xander-jones** [comment]
Presumably it's either a warning/error that Xcode tolerates but Fastlane doesn't, or Xcode has some different privilege that Fastlane does not.

To eliminate more things from the script. Can you please try the same script as above, but just drop the `system` lines so that it rattles through the script quickly, but executes:
```ruby
fork do
  Process.setsid

  Dir["#{ENV["DWARF_DSYM_FOLDER_PATH"]}/*/Contents/Resources/DWARF/*"].each do |dsym|
    puts dsym
  end
end
```

The error you're seeing suggests code signing's failing, there may be a timeout between starting the process and archiving the application. Have you performed the troubleshooting in the error message at https://docs.fastlane.tools/codesigning/getting-started?

Also, when the Fastlane runs and if fails, please can you grab the script that's located in the output message, and ensure that is actually the script you're expecting to fail e.g.: 
```
The following build commands failed:
-->	PhaseScriptExecution Run\ Script /Users/paras/Library/Developer/Xcode/DerivedData/<AppName>-aydqlcjzjvbvrlcblnikdehxrfmy/Build/Intermediates.noindex/ArchiveIntermediates/<AppName>/IntermediateBuildFilesPath/<AppName>.build/Release-iphoneos/<AppName>.build/Script-6AB24C4825BFB3210093503A.sh <---
(1 failure)
```

**Comment by prgorasiya** [comment]
Fastlane archive fails even with above script.
I got the same error and its the same script I am expecting to fail
```
The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/paras/Library/Developer/Xcode/DerivedData/<App name>-aydqlcjzjvbvrlcblnikdehxrfmy/Build/Intermediates.noindex/ArchiveIntermediates/<App name>/IntermediateBuildFilesPath/<App name>.build/Release-iphoneos/<App name>.build/Script-6AF3456725D37FDD00B9510F.sh
(1 failure)
```

If it was code signing failure, it shouldnt work when Bugsnag script is not added as phase script.
I am only adding and removing Bugsnag script when testing Fastlane archive, it fails when I add the script and works when I dont.
> The error you're seeing suggests code signing's failing, there may be a timeout between starting the process and archiving the application. Have you performed the troubleshooting in the error message at https://docs.fastlane.tools/codesigning/getting-started?

**Comment by xander-jones** [comment]
The build phase has some requirements on your Ruby environment that are not being met, namely the root problem is `bundler` is missing. Note the script is using `/usr/bin/Ruby`, not the Ruby version that you have in `.rvm`

> To install the missing version, run `gem install bundler:2.0.2`

You'll likely need to switch to your system Ruby before installing this gem, use `$ rvm use system`: https://rvm.io/rubies/default

Your two other build phase scripts are using the `sh` shell, so the inclusion of a Ruby build phase script is throwing these errors, which would explain why removal of this only Ruby script allows your Fastlane build to pass.

**Comment by prgorasiya** [comment]
Thanks @xander-jones, its working fine now.

**Comment by reyalpsirc** [comment]
I was also having problems with this when building through jenkins + bitrise steps + fastlane and in my case it was complaining about a gem that was installed but that would throw a "not found" somehow (json 2.5.1 in this case).
In the end, since I didn't find what was causing the gem to not be found (even "bundler show" would display it), I ended up changing the upload script to /bin/bash. Here's how it looks (in case someone else faces the same problem):

	echo "DSYMS location: $DWARF_DSYM_FOLDER_PATH/<MyAppName>.app.dSYM/Contents/Resources/DWARF/"
	for dsym in "$DWARF_DSYM_FOLDER_PATH/<MyAppName>.app.dSYM/Contents/Resources/DWARF"/*; do
	    [ -e "$dsym" ] || continue
	    echo "@$dsym"
	    curl --http1.1 -F apiKey=<MyKey> -F dsym="@$dsym" -F projectRoot="$PROJECT_DIR" https://upload.bugsnag.com/
	done

Just trade **<MyAppName>** by the name of your target on XCode and **<MyKey>** by your Bugsnag API key
