### ISSUE TITLE
Using cocoa pod with swift generates error:include of non-modular header inside framework module 'Bugsnag.BugsnagSink'

### ISSUE THREAD

**Issue by abuobaida** [bugsnag/bugsnag-cocoa#98]
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "~/Pods/Target Support Files/Bugsnag/Bugsnag-umbrella.h"
        ^
/Users/new/Desktop/cashier/Pods/Target Support Files/Bugsnag/Bugsnag-umbrella.h:11:9: note: in file included from ~/Pods/Target Support Files/Bugsnag/Bugsnag-umbrella.h:11:
#import "BugsnagSink.h"
        ^
~//Pods/Bugsnag/Source/BugsnagSink.h:28:9: error: include of non-modular header inside framework module 'Bugsnag.BugsnagSink'
#import <KSCrash/KSCrash.h>
        ^
~//Source/Bugsnag.swift:2:8: error: could not build Objective-C module 'Bugsnag'
import Bugsnag
```

**Comment by kattrali** [comment]
Thank you for the report, @abuobaida. Could you post your Podfile (and possibly Podfile.lock) so we know you are using the latest version (5.0.0)? 

There is also an example project [here](https://github.com/bugsnag/bugsnag-cocoa-crashprobe) which is integrated with Bugsnag 5.0.0 via CocoaPods, has "Allow Non-modular Includes in Framework Modules" set to "No", and does not appear to have this issue.

**Comment by abuobaida** [comment]
Thanks @kattrali for your response. The issue appeared when Bugsnag is included as a dependency in another pod. It appeared after updating to Bugsnag 5.0.0. This is a sample project that has the issue [here](https://dl.dropboxusercontent.com/u/29841984/misc/TestBugsnag.zip).

**Comment by kattrali** [comment]
Thank you, the example project was perfect for figuring out what was going on. Fixing via #99.
