### ISSUE TITLE
Analyzer Issue in BugsnagClient.m

### ISSUE THREAD

**Issue by mdcarter1** [bugsnag/bugsnag-cocoa#989]
Describe the bug
Running the Xcode analyzer in combination with integrating Bugsnag via SPM results in 1 Xcode analyzer issues. Our particular CI pipelines runs Xcode analyzer as part of our build workflow so ideally there should be no issues reported.

Steps to reproduce
These are the analyzer issues being reported by Xcode:

bugsnag-cocoa/Bugsnag/Client/BugsnagClient.m:1028:35: warning: nil passed to a callee that requires a non-null 1st parameter
                      withMessage:[self.notificationBreadcrumbs messageForNotificationName:notification.name]
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
Environment
Bugsnag version: 6.6.0

**Comment by mdcarter1** [comment]
I seem to recall something in the past about including Analyzer in the CI pipeline... may want to check on that if it was implemented.

**Comment by xander-jones** [comment]
Hey @mdcarter1, I can confirm I'm seeing the same warning as you when running Xcode's analyzer on v6.6.0. We'll take a look into a fix for this now, and work out why the CI did not catch this. Thanks for raising the issue with us!

**Comment by xander-jones** [comment]
Ah, this warning exists when building with Xcode 11.x, but not Xcode 12. Our CI uses Xcode 12 to analyze. Can you please confirm which version of Xcode you're using?

**Comment by mdcarter1** [comment]
@xander-jones exists for me using Xcode 12.4
<img width="951" alt="Screen Shot 2021-02-05 at 3 04 35 PM" src="https://user-images.githubusercontent.com/954968/107083363-82763280-67c3-11eb-91f5-f4a515d5b4fa.png">

**Comment by mdcarter1** [comment]
If I Analyze for a non-simulator such as "Any iOS Device" it doesn't report any issue.   Hope that helps.

**Comment by phillipsam** [comment]
A fix for this has now been released in [v6.6.2](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.6.2). Let us know if you have any questions!
